// Generated by the Jungle engine-source miner
// (scripts/variant-lab/jungle-tactics-mine.ts). Do not hand-edit; re-run the
// miner and copy its `--emit-dir` output here.
//
// Source-linked puzzles mined from MistyJungle self-play games. Two kinds:
//   - `win`: a forced win the engine flagged (score >= WIN floor) that the kernel
//     solver then extracted as a unique win-in-k line — the DEEPER (k>=2) forced
//     wins random self-play can't reach cheaply. The kernel re-verifies these.
//   - `winning-advantage`: a non-terminal decisive edge with a unique best move.
//     Rare in Dou Shou Qi (decisive edges are forced den-races), so this set is
//     tiny by design; `centipawns` records the engine score (engine units).
// Each links to its game via sourceGame:{gameId, ply} (see JUNGLE_SOURCE_GAMES).
//
// The local structural type mirrors `JunglePuzzle` in puzzles-jungle.ts so the
// array is assignable when spread there, while keeping this file free of a
// circular import.

import { JUNGLE_SPEC_ID } from './game-specs.js';
import type { JungleColor, JungleGameState, JungleMove } from './variants-jungle.js';

type TacticJunglePuzzleTheme =
  | 'den-race'
  | 'capture-all'
  | 'stalemate'
  | 'trap'
  | 'water-leap'
  | 'rank-up'
  | 'rat'
  | 'elephant'
  | 'lion'
  | 'tiger'
  | 'winning';

type TacticJunglePuzzle = {
  id: string;
  variant: typeof JUNGLE_SPEC_ID;
  title: string;
  initial: JungleGameState;
  solution: JungleMove[];
  goal:
    | { type: 'win'; winner?: JungleColor }
    | { type: 'winning-advantage'; winner?: JungleColor; centipawns?: number };
  themes: TacticJunglePuzzleTheme[];
  sourceGame?: { gameId: string; ply: number };
};

export const TACTIC_JUNGLE_PUZZLES: readonly TacticJunglePuzzle[] = [
  {
    "id": "jungle-tactic-001",
    "variant": "jungle",
    "title": "Red Lion win in 3",
    "initial": {
      "id": "jungle-tactic-001",
      "board": {
        "f3": {
          "color": "black",
          "role": "lion"
        },
        "e3": {
          "color": "red",
          "role": "wolf"
        },
        "e8": {
          "color": "black",
          "role": "leopard"
        },
        "d4": {
          "color": "red",
          "role": "leopard"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "d2": {
          "color": "red",
          "role": "tiger"
        },
        "e7": {
          "color": "black",
          "role": "dog"
        },
        "f2": {
          "color": "red",
          "role": "elephant"
        },
        "a7": {
          "color": "black",
          "role": "tiger"
        },
        "b5": {
          "color": "red",
          "role": "rat"
        },
        "d5": {
          "color": "black",
          "role": "wolf"
        },
        "c2": {
          "color": "red",
          "role": "dog"
        },
        "d6": {
          "color": "black",
          "role": "elephant"
        },
        "a4": {
          "color": "black",
          "role": "cat"
        },
        "c7": {
          "color": "red",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 31,
      "progressClock": 0,
      "positionCounts": {
        "red|.........DT.E.....Wl.c..Pr...R.w......e...t.L.d......p.........": 1
      }
    },
    "solution": [
      {
        "from": "c7",
        "to": "c8"
      },
      {
        "from": "f3",
        "to": "g3"
      },
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "e8",
        "to": "f8"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0002",
      "ply": 60
    }
  },
  {
    "id": "jungle-tactic-002",
    "variant": "jungle",
    "title": "Red Lion win in 2",
    "initial": {
      "id": "jungle-tactic-002",
      "board": {
        "e3": {
          "color": "black",
          "role": "lion"
        },
        "e8": {
          "color": "black",
          "role": "leopard"
        },
        "d4": {
          "color": "red",
          "role": "leopard"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "d2": {
          "color": "red",
          "role": "tiger"
        },
        "e7": {
          "color": "black",
          "role": "dog"
        },
        "f2": {
          "color": "red",
          "role": "elephant"
        },
        "a7": {
          "color": "black",
          "role": "tiger"
        },
        "b5": {
          "color": "red",
          "role": "rat"
        },
        "d5": {
          "color": "black",
          "role": "wolf"
        },
        "c2": {
          "color": "red",
          "role": "dog"
        },
        "d6": {
          "color": "black",
          "role": "elephant"
        },
        "a4": {
          "color": "black",
          "role": "cat"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 32,
      "progressClock": 0,
      "positionCounts": {
        "red|.........DT.E.....l..c..Pr...R.w......e...t...d....L.p.........": 1
      }
    },
    "solution": [
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "e3",
        "to": "f3"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0002",
      "ply": 62
    }
  },
  {
    "id": "jungle-tactic-003",
    "variant": "jungle",
    "title": "Red Elephant win in 4",
    "initial": {
      "id": "jungle-tactic-003",
      "board": {
        "c3": {
          "color": "red",
          "role": "leopard"
        },
        "d3": {
          "color": "black",
          "role": "elephant"
        },
        "c1": {
          "color": "red",
          "role": "lion"
        },
        "e3": {
          "color": "red",
          "role": "elephant"
        },
        "e1": {
          "color": "red",
          "role": "cat"
        },
        "d5": {
          "color": "black",
          "role": "dog"
        },
        "f6": {
          "color": "black",
          "role": "rat"
        },
        "c7": {
          "color": "red",
          "role": "dog"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 47,
      "progressClock": 0,
      "positionCounts": {
        "red|..L.C...........PeE............d........r...D..................": 1
      }
    },
    "solution": [
      {
        "from": "e3",
        "to": "d3"
      },
      {
        "from": "d5",
        "to": "d6"
      },
      {
        "from": "c7",
        "to": "c8"
      },
      {
        "from": "f6",
        "to": "g6"
      },
      {
        "from": "c8",
        "to": "d8"
      },
      {
        "from": "d6",
        "to": "d7"
      },
      {
        "from": "d8",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "elephant",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0003",
      "ply": 92
    }
  },
  {
    "id": "jungle-tactic-004",
    "variant": "jungle",
    "title": "Red Dog win in 2",
    "initial": {
      "id": "jungle-tactic-004",
      "board": {
        "c3": {
          "color": "red",
          "role": "leopard"
        },
        "d3": {
          "color": "red",
          "role": "elephant"
        },
        "c1": {
          "color": "red",
          "role": "lion"
        },
        "e1": {
          "color": "red",
          "role": "cat"
        },
        "d5": {
          "color": "black",
          "role": "dog"
        },
        "d7": {
          "color": "red",
          "role": "dog"
        },
        "e5": {
          "color": "black",
          "role": "rat"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 49,
      "progressClock": 3,
      "positionCounts": {
        "red|..L.C...........PE.............dr............D.................": 1
      }
    },
    "solution": [
      {
        "from": "d7",
        "to": "d8"
      },
      {
        "from": "d5",
        "to": "d6"
      },
      {
        "from": "d8",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0003",
      "ply": 96
    }
  },
  {
    "id": "jungle-tactic-005",
    "variant": "jungle",
    "title": "Red Dog win in 3",
    "initial": {
      "id": "jungle-tactic-005",
      "board": {
        "b3": {
          "color": "red",
          "role": "leopard"
        },
        "d8": {
          "color": "black",
          "role": "wolf"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "e7": {
          "color": "black",
          "role": "leopard"
        },
        "f7": {
          "color": "black",
          "role": "dog"
        },
        "e3": {
          "color": "red",
          "role": "cat"
        },
        "a1": {
          "color": "black",
          "role": "tiger"
        },
        "c2": {
          "color": "red",
          "role": "dog"
        },
        "d2": {
          "color": "black",
          "role": "elephant"
        },
        "g5": {
          "color": "black",
          "role": "lion"
        },
        "g3": {
          "color": "red",
          "role": "elephant"
        },
        "d6": {
          "color": "red",
          "role": "rat"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 33,
      "progressClock": 0,
      "positionCounts": {
        "red|t........De....P..C.E....r........l...R.......pd...Lw..........": 1
      }
    },
    "solution": [
      {
        "from": "c2",
        "to": "d2"
      },
      {
        "from": "d8",
        "to": "e8"
      },
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "e4",
        "to": "f4"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "trap",
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0005",
      "ply": 64
    }
  },
  {
    "id": "jungle-tactic-006",
    "variant": "jungle",
    "title": "Red Lion win in 2",
    "initial": {
      "id": "jungle-tactic-006",
      "board": {
        "b3": {
          "color": "red",
          "role": "leopard"
        },
        "d8": {
          "color": "black",
          "role": "wolf"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "f7": {
          "color": "black",
          "role": "dog"
        },
        "e3": {
          "color": "red",
          "role": "cat"
        },
        "a1": {
          "color": "black",
          "role": "tiger"
        },
        "d2": {
          "color": "red",
          "role": "dog"
        },
        "g5": {
          "color": "black",
          "role": "lion"
        },
        "g3": {
          "color": "red",
          "role": "elephant"
        },
        "d6": {
          "color": "red",
          "role": "rat"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        },
        "d7": {
          "color": "black",
          "role": "leopard"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 34,
      "progressClock": 1,
      "positionCounts": {
        "red|t.........D....P..C.E....r........l...R......p.d...Lw..........": 1
      }
    },
    "solution": [
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "d8",
        "to": "e8"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0005",
      "ply": 66
    }
  },
  {
    "id": "jungle-tactic-007",
    "variant": "jungle",
    "title": "Red Tiger win in 3",
    "initial": {
      "id": "jungle-tactic-007",
      "board": {
        "g9": {
          "color": "black",
          "role": "lion"
        },
        "a9": {
          "color": "black",
          "role": "tiger"
        },
        "b2": {
          "color": "red",
          "role": "dog"
        },
        "b8": {
          "color": "black",
          "role": "cat"
        },
        "c3": {
          "color": "red",
          "role": "leopard"
        },
        "a8": {
          "color": "black",
          "role": "elephant"
        },
        "a3": {
          "color": "red",
          "role": "rat"
        },
        "f3": {
          "color": "red",
          "role": "cat"
        },
        "a2": {
          "color": "red",
          "role": "lion"
        },
        "g8": {
          "color": "black",
          "role": "dog"
        },
        "d3": {
          "color": "red",
          "role": "wolf"
        },
        "g2": {
          "color": "red",
          "role": "elephant"
        },
        "f4": {
          "color": "black",
          "role": "rat"
        },
        "d5": {
          "color": "black",
          "role": "leopard"
        },
        "c7": {
          "color": "red",
          "role": "tiger"
        },
        "d8": {
          "color": "black",
          "role": "wolf"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 14,
      "progressClock": 26,
      "positionCounts": {
        "red|.......LD....ER.PW.C......r....p............T....ec.w..dt.....l": 1
      }
    },
    "solution": [
      {
        "from": "c7",
        "to": "c8"
      },
      {
        "from": "g9",
        "to": "f9"
      },
      {
        "from": "c8",
        "to": "d8"
      },
      {
        "from": "a9",
        "to": "b9"
      },
      {
        "from": "d8",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "tiger",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0008",
      "ply": 26
    }
  },
  {
    "id": "jungle-tactic-008",
    "variant": "jungle",
    "title": "Red Tiger win in 2",
    "initial": {
      "id": "jungle-tactic-008",
      "board": {
        "g9": {
          "color": "black",
          "role": "lion"
        },
        "a9": {
          "color": "black",
          "role": "tiger"
        },
        "b2": {
          "color": "red",
          "role": "dog"
        },
        "b8": {
          "color": "black",
          "role": "cat"
        },
        "c3": {
          "color": "red",
          "role": "leopard"
        },
        "a8": {
          "color": "black",
          "role": "elephant"
        },
        "a3": {
          "color": "red",
          "role": "rat"
        },
        "f3": {
          "color": "red",
          "role": "cat"
        },
        "a2": {
          "color": "red",
          "role": "lion"
        },
        "g8": {
          "color": "black",
          "role": "dog"
        },
        "d3": {
          "color": "red",
          "role": "wolf"
        },
        "g2": {
          "color": "red",
          "role": "elephant"
        },
        "f4": {
          "color": "black",
          "role": "rat"
        },
        "d5": {
          "color": "black",
          "role": "leopard"
        },
        "c8": {
          "color": "red",
          "role": "tiger"
        },
        "d7": {
          "color": "black",
          "role": "wolf"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 15,
      "progressClock": 28,
      "positionCounts": {
        "red|.......LD....ER.PW.C......r....p.............w...ecT...dt.....l": 1
      }
    },
    "solution": [
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "g9",
        "to": "f9"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "tiger",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0008",
      "ply": 28
    }
  },
  {
    "id": "jungle-tactic-009",
    "variant": "jungle",
    "title": "Red Lion win in 3",
    "initial": {
      "id": "jungle-tactic-009",
      "board": {
        "g9": {
          "color": "black",
          "role": "lion"
        },
        "f8": {
          "color": "black",
          "role": "dog"
        },
        "e3": {
          "color": "red",
          "role": "wolf"
        },
        "f3": {
          "color": "red",
          "role": "cat"
        },
        "d3": {
          "color": "red",
          "role": "leopard"
        },
        "f2": {
          "color": "red",
          "role": "tiger"
        },
        "g2": {
          "color": "red",
          "role": "elephant"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "b3": {
          "color": "red",
          "role": "rat"
        },
        "d2": {
          "color": "red",
          "role": "dog"
        },
        "a5": {
          "color": "black",
          "role": "elephant"
        },
        "a7": {
          "color": "black",
          "role": "cat"
        },
        "b9": {
          "color": "black",
          "role": "tiger"
        },
        "e7": {
          "color": "red",
          "role": "lion"
        },
        "e9": {
          "color": "black",
          "role": "leopard"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 18,
      "progressClock": 3,
      "positionCounts": {
        "red|..........D.TE.R.PWC.....r..e.............c...L.......d..t..p.l": 1
      }
    },
    "solution": [
      {
        "from": "e7",
        "to": "e8"
      },
      {
        "from": "g9",
        "to": "f9"
      },
      {
        "from": "e8",
        "to": "d8"
      },
      {
        "from": "f8",
        "to": "g8"
      },
      {
        "from": "d8",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0009",
      "ply": 34
    }
  },
  {
    "id": "jungle-tactic-010",
    "variant": "jungle",
    "title": "Red Lion win in 2",
    "initial": {
      "id": "jungle-tactic-010",
      "board": {
        "f8": {
          "color": "black",
          "role": "dog"
        },
        "e3": {
          "color": "red",
          "role": "wolf"
        },
        "f3": {
          "color": "red",
          "role": "cat"
        },
        "d3": {
          "color": "red",
          "role": "leopard"
        },
        "f2": {
          "color": "red",
          "role": "tiger"
        },
        "g2": {
          "color": "red",
          "role": "elephant"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "b3": {
          "color": "red",
          "role": "rat"
        },
        "d2": {
          "color": "red",
          "role": "dog"
        },
        "a5": {
          "color": "black",
          "role": "elephant"
        },
        "a7": {
          "color": "black",
          "role": "cat"
        },
        "b9": {
          "color": "black",
          "role": "tiger"
        },
        "e9": {
          "color": "black",
          "role": "leopard"
        },
        "e8": {
          "color": "red",
          "role": "lion"
        },
        "f9": {
          "color": "black",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 19,
      "progressClock": 5,
      "positionCounts": {
        "red|..........D.TE.R.PWC.....r..e.............c..........Ld..t..pl.": 1
      }
    },
    "solution": [
      {
        "from": "e8",
        "to": "d8"
      },
      {
        "from": "f8",
        "to": "g8"
      },
      {
        "from": "d8",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0009",
      "ply": 36
    }
  },
  {
    "id": "jungle-tactic-011",
    "variant": "jungle",
    "title": "Black Lion win in 3",
    "initial": {
      "id": "jungle-tactic-011",
      "board": {
        "d7": {
          "color": "black",
          "role": "elephant"
        },
        "c7": {
          "color": "black",
          "role": "cat"
        },
        "d8": {
          "color": "black",
          "role": "wolf"
        },
        "b7": {
          "color": "black",
          "role": "tiger"
        },
        "d6": {
          "color": "black",
          "role": "leopard"
        },
        "d5": {
          "color": "red",
          "role": "lion"
        },
        "d4": {
          "color": "red",
          "role": "dog"
        },
        "b6": {
          "color": "red",
          "role": "rat"
        },
        "e8": {
          "color": "black",
          "role": "dog"
        },
        "c2": {
          "color": "red",
          "role": "cat"
        },
        "f3": {
          "color": "red",
          "role": "tiger"
        },
        "g2": {
          "color": "red",
          "role": "elephant"
        },
        "b3": {
          "color": "red",
          "role": "leopard"
        },
        "c3": {
          "color": "black",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 50,
      "progressClock": 0,
      "positionCounts": {
        "black|.........C...E.Pl..T....D......L....R.p....tce......wd.........": 1
      }
    },
    "solution": [
      {
        "from": "c3",
        "to": "c2"
      },
      {
        "from": "d5",
        "to": "d6"
      },
      {
        "from": "c2",
        "to": "d2"
      },
      {
        "from": "d6",
        "to": "d5"
      },
      {
        "from": "d2",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "lion",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0010",
      "ply": 99
    }
  },
  {
    "id": "jungle-tactic-012",
    "variant": "jungle",
    "title": "Black Lion win in 4",
    "initial": {
      "id": "jungle-tactic-012",
      "board": {
        "d7": {
          "color": "black",
          "role": "elephant"
        },
        "e7": {
          "color": "black",
          "role": "leopard"
        },
        "d6": {
          "color": "red",
          "role": "leopard"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "c6": {
          "color": "red",
          "role": "rat"
        },
        "a1": {
          "color": "red",
          "role": "lion"
        },
        "c7": {
          "color": "black",
          "role": "cat"
        },
        "c3": {
          "color": "red",
          "role": "dog"
        },
        "g3": {
          "color": "red",
          "role": "elephant"
        },
        "f8": {
          "color": "black",
          "role": "dog"
        },
        "d2": {
          "color": "red",
          "role": "cat"
        },
        "d3": {
          "color": "black",
          "role": "lion"
        },
        "e2": {
          "color": "red",
          "role": "wolf"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 38,
      "progressClock": 3,
      "positionCounts": {
        "black|L.........CW....Dl..E....r...........RP.....cep.......d........": 1
      }
    },
    "solution": [
      {
        "from": "d3",
        "to": "e3"
      },
      {
        "from": "d6",
        "to": "d5"
      },
      {
        "from": "e3",
        "to": "e2"
      },
      {
        "from": "c6",
        "to": "d6"
      },
      {
        "from": "e2",
        "to": "d2"
      },
      {
        "from": "a1",
        "to": "b1"
      },
      {
        "from": "d2",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "lion",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0013",
      "ply": 75
    }
  },
  {
    "id": "jungle-tactic-013",
    "variant": "jungle",
    "title": "Black Lion win in 3",
    "initial": {
      "id": "jungle-tactic-013",
      "board": {
        "d7": {
          "color": "black",
          "role": "elephant"
        },
        "e7": {
          "color": "black",
          "role": "leopard"
        },
        "d6": {
          "color": "red",
          "role": "leopard"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "c6": {
          "color": "red",
          "role": "rat"
        },
        "a1": {
          "color": "red",
          "role": "lion"
        },
        "c7": {
          "color": "black",
          "role": "cat"
        },
        "c3": {
          "color": "red",
          "role": "dog"
        },
        "g3": {
          "color": "red",
          "role": "elephant"
        },
        "f8": {
          "color": "black",
          "role": "dog"
        },
        "d2": {
          "color": "red",
          "role": "cat"
        },
        "e3": {
          "color": "black",
          "role": "lion"
        },
        "f2": {
          "color": "red",
          "role": "wolf"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 39,
      "progressClock": 5,
      "positionCounts": {
        "black|L.........C.W...D.l.E....r...........RP.....cep.......d........": 1
      }
    },
    "solution": [
      {
        "from": "e3",
        "to": "e2"
      },
      {
        "from": "d6",
        "to": "d5"
      },
      {
        "from": "e2",
        "to": "d2"
      },
      {
        "from": "c6",
        "to": "d6"
      },
      {
        "from": "d2",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "lion",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0013",
      "ply": 77
    }
  },
  {
    "id": "jungle-tactic-014",
    "variant": "jungle",
    "title": "Black Lion win in 2",
    "initial": {
      "id": "jungle-tactic-014",
      "board": {
        "d7": {
          "color": "black",
          "role": "elephant"
        },
        "e7": {
          "color": "black",
          "role": "leopard"
        },
        "d6": {
          "color": "red",
          "role": "leopard"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "c6": {
          "color": "red",
          "role": "rat"
        },
        "a1": {
          "color": "red",
          "role": "lion"
        },
        "c7": {
          "color": "black",
          "role": "cat"
        },
        "c3": {
          "color": "red",
          "role": "dog"
        },
        "g3": {
          "color": "red",
          "role": "elephant"
        },
        "f8": {
          "color": "black",
          "role": "dog"
        },
        "f2": {
          "color": "red",
          "role": "wolf"
        },
        "e2": {
          "color": "black",
          "role": "lion"
        },
        "d3": {
          "color": "red",
          "role": "cat"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 40,
      "progressClock": 7,
      "positionCounts": {
        "black|L..........lW...DC..E....r...........RP.....cep.......d........": 1
      }
    },
    "solution": [
      {
        "from": "e2",
        "to": "e1"
      },
      {
        "from": "d6",
        "to": "d5"
      },
      {
        "from": "e1",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0013",
      "ply": 79
    }
  },
  {
    "id": "jungle-tactic-015",
    "variant": "jungle",
    "title": "Black Lion win in 3",
    "initial": {
      "id": "jungle-tactic-015",
      "board": {
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "e3": {
          "color": "black",
          "role": "lion"
        },
        "d8": {
          "color": "black",
          "role": "wolf"
        },
        "f8": {
          "color": "black",
          "role": "dog"
        },
        "e8": {
          "color": "black",
          "role": "cat"
        },
        "e7": {
          "color": "black",
          "role": "leopard"
        },
        "d7": {
          "color": "black",
          "role": "tiger"
        },
        "d2": {
          "color": "red",
          "role": "wolf"
        },
        "a6": {
          "color": "red",
          "role": "lion"
        },
        "c2": {
          "color": "red",
          "role": "leopard"
        },
        "c3": {
          "color": "red",
          "role": "tiger"
        },
        "d6": {
          "color": "red",
          "role": "rat"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 48,
      "progressClock": 0,
      "positionCounts": {
        "black|.........PW.....T.l......r.........L..R......tp.....wcd........": 1
      }
    },
    "solution": [
      {
        "from": "e3",
        "to": "e2"
      },
      {
        "from": "d2",
        "to": "d3"
      },
      {
        "from": "e2",
        "to": "e1"
      },
      {
        "from": "a6",
        "to": "a7"
      },
      {
        "from": "e1",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0015",
      "ply": 95
    }
  },
  {
    "id": "jungle-tactic-016",
    "variant": "jungle",
    "title": "Black Lion win in 2",
    "initial": {
      "id": "jungle-tactic-016",
      "board": {
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "d8": {
          "color": "black",
          "role": "wolf"
        },
        "f8": {
          "color": "black",
          "role": "dog"
        },
        "e8": {
          "color": "black",
          "role": "cat"
        },
        "e7": {
          "color": "black",
          "role": "leopard"
        },
        "d7": {
          "color": "black",
          "role": "tiger"
        },
        "d2": {
          "color": "red",
          "role": "wolf"
        },
        "a6": {
          "color": "red",
          "role": "lion"
        },
        "c2": {
          "color": "red",
          "role": "leopard"
        },
        "d6": {
          "color": "red",
          "role": "rat"
        },
        "e2": {
          "color": "black",
          "role": "lion"
        },
        "c7": {
          "color": "red",
          "role": "tiger"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 49,
      "progressClock": 2,
      "positionCounts": {
        "black|.........PWl.............r.........L..R.....Ttp.....wcd........": 1
      }
    },
    "solution": [
      {
        "from": "e2",
        "to": "e1"
      },
      {
        "from": "d2",
        "to": "e2"
      },
      {
        "from": "e1",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0015",
      "ply": 97
    }
  },
  {
    "id": "jungle-tactic-017",
    "variant": "jungle",
    "title": "Black Tiger win in 3",
    "initial": {
      "id": "jungle-tactic-017",
      "board": {
        "d6": {
          "color": "red",
          "role": "lion"
        },
        "d4": {
          "color": "red",
          "role": "leopard"
        },
        "d7": {
          "color": "black",
          "role": "elephant"
        },
        "e3": {
          "color": "red",
          "role": "elephant"
        },
        "e7": {
          "color": "black",
          "role": "lion"
        },
        "d3": {
          "color": "red",
          "role": "dog"
        },
        "c6": {
          "color": "red",
          "role": "rat"
        },
        "f8": {
          "color": "black",
          "role": "dog"
        },
        "c8": {
          "color": "black",
          "role": "cat"
        },
        "d2": {
          "color": "red",
          "role": "wolf"
        },
        "e2": {
          "color": "red",
          "role": "tiger"
        },
        "g3": {
          "color": "red",
          "role": "cat"
        },
        "b2": {
          "color": "black",
          "role": "tiger"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 43,
      "progressClock": 0,
      "positionCounts": {
        "black|........t.WT.....DE.C...P............RL......el....c..d........": 1
      }
    },
    "solution": [
      {
        "from": "b2",
        "to": "c2"
      },
      {
        "from": "d6",
        "to": "d5"
      },
      {
        "from": "c2",
        "to": "c1"
      },
      {
        "from": "e3",
        "to": "f3"
      },
      {
        "from": "c1",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "tiger",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0017",
      "ply": 85
    }
  },
  {
    "id": "jungle-tactic-018",
    "variant": "jungle",
    "title": "Black Tiger win in 2",
    "initial": {
      "id": "jungle-tactic-018",
      "board": {
        "d6": {
          "color": "red",
          "role": "lion"
        },
        "d4": {
          "color": "red",
          "role": "leopard"
        },
        "d7": {
          "color": "black",
          "role": "elephant"
        },
        "e3": {
          "color": "red",
          "role": "elephant"
        },
        "e7": {
          "color": "black",
          "role": "lion"
        },
        "d3": {
          "color": "red",
          "role": "dog"
        },
        "c6": {
          "color": "red",
          "role": "rat"
        },
        "f8": {
          "color": "black",
          "role": "dog"
        },
        "c8": {
          "color": "black",
          "role": "cat"
        },
        "d2": {
          "color": "red",
          "role": "wolf"
        },
        "e2": {
          "color": "red",
          "role": "tiger"
        },
        "c2": {
          "color": "black",
          "role": "tiger"
        },
        "f3": {
          "color": "red",
          "role": "cat"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 44,
      "progressClock": 2,
      "positionCounts": {
        "black|.........tWT.....DEC....P............RL......el....c..d........": 1
      }
    },
    "solution": [
      {
        "from": "c2",
        "to": "c1"
      },
      {
        "from": "d6",
        "to": "d5"
      },
      {
        "from": "c1",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "tiger",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0017",
      "ply": 87
    }
  },
  {
    "id": "jungle-tactic-019",
    "variant": "jungle",
    "title": "Red Dog win in 3",
    "initial": {
      "id": "jungle-tactic-019",
      "board": {
        "f2": {
          "color": "red",
          "role": "cat"
        },
        "d7": {
          "color": "black",
          "role": "elephant"
        },
        "e7": {
          "color": "black",
          "role": "dog"
        },
        "d6": {
          "color": "black",
          "role": "wolf"
        },
        "e3": {
          "color": "red",
          "role": "elephant"
        },
        "f7": {
          "color": "black",
          "role": "lion"
        },
        "d5": {
          "color": "red",
          "role": "leopard"
        },
        "d4": {
          "color": "red",
          "role": "wolf"
        },
        "c6": {
          "color": "red",
          "role": "rat"
        },
        "d8": {
          "color": "black",
          "role": "leopard"
        },
        "c2": {
          "color": "red",
          "role": "dog"
        },
        "c7": {
          "color": "black",
          "role": "cat"
        },
        "d2": {
          "color": "red",
          "role": "tiger"
        },
        "f3": {
          "color": "black",
          "role": "rat"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        },
        "c1": {
          "color": "black",
          "role": "tiger"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 42,
      "progressClock": 82,
      "positionCounts": {
        "red|..t......DT.C.....Er....W......P.....Rw.....cedl...Lp..........": 1
      }
    },
    "solution": [
      {
        "from": "c2",
        "to": "c1"
      },
      {
        "from": "e7",
        "to": "e8"
      },
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "d7",
        "to": "e7"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "trap",
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0022",
      "ply": 82
    }
  },
  {
    "id": "jungle-tactic-020",
    "variant": "jungle",
    "title": "Red Lion win in 2",
    "initial": {
      "id": "jungle-tactic-020",
      "board": {
        "f2": {
          "color": "red",
          "role": "cat"
        },
        "d7": {
          "color": "black",
          "role": "elephant"
        },
        "e7": {
          "color": "black",
          "role": "dog"
        },
        "d6": {
          "color": "black",
          "role": "wolf"
        },
        "e3": {
          "color": "black",
          "role": "rat"
        },
        "f7": {
          "color": "black",
          "role": "lion"
        },
        "d5": {
          "color": "red",
          "role": "leopard"
        },
        "d4": {
          "color": "red",
          "role": "wolf"
        },
        "c6": {
          "color": "red",
          "role": "rat"
        },
        "d8": {
          "color": "black",
          "role": "leopard"
        },
        "c7": {
          "color": "black",
          "role": "cat"
        },
        "d2": {
          "color": "red",
          "role": "tiger"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        },
        "c1": {
          "color": "red",
          "role": "dog"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 43,
      "progressClock": 0,
      "positionCounts": {
        "red|..D.......T.C.....r.....W......P.....Rw.....cedl...Lp..........": 1
      }
    },
    "solution": [
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "e7",
        "to": "e8"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0022",
      "ply": 84
    }
  },
  {
    "id": "jungle-tactic-021",
    "variant": "jungle",
    "title": "Red Lion win in 3",
    "initial": {
      "id": "jungle-tactic-021",
      "board": {
        "g9": {
          "color": "black",
          "role": "lion"
        },
        "g3": {
          "color": "red",
          "role": "elephant"
        },
        "g8": {
          "color": "black",
          "role": "rat"
        },
        "f3": {
          "color": "red",
          "role": "cat"
        },
        "e2": {
          "color": "red",
          "role": "wolf"
        },
        "e1": {
          "color": "red",
          "role": "tiger"
        },
        "b3": {
          "color": "red",
          "role": "dog"
        },
        "b5": {
          "color": "red",
          "role": "rat"
        },
        "e7": {
          "color": "black",
          "role": "leopard"
        },
        "b7": {
          "color": "black",
          "role": "cat"
        },
        "f7": {
          "color": "black",
          "role": "dog"
        },
        "d8": {
          "color": "black",
          "role": "tiger"
        },
        "d5": {
          "color": "black",
          "role": "elephant"
        },
        "c7": {
          "color": "red",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 27,
      "progressClock": 0,
      "positionCounts": {
        "red|....T......W...D...CE........R.e...........cL.pd....t..r......l": 1
      }
    },
    "solution": [
      {
        "from": "c7",
        "to": "c8"
      },
      {
        "from": "g9",
        "to": "f9"
      },
      {
        "from": "c8",
        "to": "d8"
      },
      {
        "from": "g8",
        "to": "f8"
      },
      {
        "from": "d8",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0023",
      "ply": 52
    }
  },
  {
    "id": "jungle-tactic-022",
    "variant": "jungle",
    "title": "Red Lion win in 2",
    "initial": {
      "id": "jungle-tactic-022",
      "board": {
        "g9": {
          "color": "black",
          "role": "lion"
        },
        "g3": {
          "color": "red",
          "role": "elephant"
        },
        "g8": {
          "color": "black",
          "role": "rat"
        },
        "f3": {
          "color": "red",
          "role": "cat"
        },
        "e2": {
          "color": "red",
          "role": "wolf"
        },
        "e1": {
          "color": "red",
          "role": "tiger"
        },
        "b3": {
          "color": "red",
          "role": "dog"
        },
        "b5": {
          "color": "red",
          "role": "rat"
        },
        "b7": {
          "color": "black",
          "role": "cat"
        },
        "f7": {
          "color": "black",
          "role": "dog"
        },
        "d8": {
          "color": "black",
          "role": "tiger"
        },
        "d5": {
          "color": "black",
          "role": "elephant"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        },
        "d7": {
          "color": "black",
          "role": "leopard"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 28,
      "progressClock": 2,
      "positionCounts": {
        "red|....T......W...D...CE........R.e...........c.p.d...Lt..r......l": 1
      }
    },
    "solution": [
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "g9",
        "to": "f9"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0023",
      "ply": 54
    }
  },
  {
    "id": "jungle-tactic-023",
    "variant": "jungle",
    "title": "Black Leopard win in 3",
    "initial": {
      "id": "jungle-tactic-023",
      "board": {
        "g4": {
          "color": "red",
          "role": "cat"
        },
        "d4": {
          "color": "red",
          "role": "wolf"
        },
        "d6": {
          "color": "black",
          "role": "wolf"
        },
        "d7": {
          "color": "black",
          "role": "leopard"
        },
        "e7": {
          "color": "black",
          "role": "lion"
        },
        "g5": {
          "color": "black",
          "role": "dog"
        },
        "g3": {
          "color": "red",
          "role": "tiger"
        },
        "c3": {
          "color": "red",
          "role": "dog"
        },
        "b9": {
          "color": "black",
          "role": "cat"
        },
        "d2": {
          "color": "red",
          "role": "leopard"
        },
        "c2": {
          "color": "black",
          "role": "tiger"
        },
        "d8": {
          "color": "red",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 31,
      "progressClock": 41,
      "positionCounts": {
        "black|.........tP.....D...T...W..C......d...w......pl.....L....c.....": 1
      }
    },
    "solution": [
      {
        "from": "d7",
        "to": "d8"
      },
      {
        "from": "d4",
        "to": "d5"
      },
      {
        "from": "c2",
        "to": "d2"
      },
      {
        "from": "g3",
        "to": "f3"
      },
      {
        "from": "d2",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "trap",
      "tiger",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0024",
      "ply": 61
    }
  },
  {
    "id": "jungle-tactic-024",
    "variant": "jungle",
    "title": "Black Tiger win in 2",
    "initial": {
      "id": "jungle-tactic-024",
      "board": {
        "g4": {
          "color": "red",
          "role": "cat"
        },
        "d4": {
          "color": "red",
          "role": "wolf"
        },
        "d6": {
          "color": "black",
          "role": "wolf"
        },
        "e7": {
          "color": "black",
          "role": "lion"
        },
        "g5": {
          "color": "black",
          "role": "dog"
        },
        "g3": {
          "color": "red",
          "role": "tiger"
        },
        "b9": {
          "color": "black",
          "role": "cat"
        },
        "d2": {
          "color": "red",
          "role": "leopard"
        },
        "c2": {
          "color": "black",
          "role": "tiger"
        },
        "d8": {
          "color": "black",
          "role": "leopard"
        },
        "d3": {
          "color": "red",
          "role": "dog"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 32,
      "progressClock": 1,
      "positionCounts": {
        "black|.........tP......D..T...W..C......d...w.......l.....p....c.....": 1
      }
    },
    "solution": [
      {
        "from": "c2",
        "to": "c1"
      },
      {
        "from": "d4",
        "to": "d5"
      },
      {
        "from": "c1",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "tiger",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0024",
      "ply": 63
    }
  },
  {
    "id": "jungle-tactic-025",
    "variant": "jungle",
    "title": "Red Cat win in 3",
    "initial": {
      "id": "jungle-tactic-025",
      "board": {
        "d5": {
          "color": "black",
          "role": "elephant"
        },
        "d8": {
          "color": "black",
          "role": "wolf"
        },
        "d4": {
          "color": "red",
          "role": "rat"
        },
        "d7": {
          "color": "black",
          "role": "leopard"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        },
        "b9": {
          "color": "red",
          "role": "tiger"
        },
        "e7": {
          "color": "black",
          "role": "lion"
        },
        "f3": {
          "color": "red",
          "role": "elephant"
        },
        "f4": {
          "color": "black",
          "role": "rat"
        },
        "b1": {
          "color": "red",
          "role": "leopard"
        },
        "e2": {
          "color": "red",
          "role": "cat"
        },
        "d2": {
          "color": "black",
          "role": "tiger"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 49,
      "progressClock": 1,
      "positionCounts": {
        "red|.P........tC.......E....R.r....e.............pl....Lw....T.....": 1
      }
    },
    "solution": [
      {
        "from": "e2",
        "to": "d2"
      },
      {
        "from": "d5",
        "to": "d6"
      },
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "d8",
        "to": "e8"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "trap",
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0025",
      "ply": 96
    }
  },
  {
    "id": "jungle-tactic-026",
    "variant": "jungle",
    "title": "Black Lion win in 4",
    "initial": {
      "id": "jungle-tactic-026",
      "board": {
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "b7": {
          "color": "black",
          "role": "dog"
        },
        "b6": {
          "color": "red",
          "role": "rat"
        },
        "d8": {
          "color": "black",
          "role": "cat"
        },
        "b2": {
          "color": "red",
          "role": "elephant"
        },
        "f1": {
          "color": "black",
          "role": "lion"
        },
        "c3": {
          "color": "red",
          "role": "lion"
        },
        "e2": {
          "color": "red",
          "role": "wolf"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 51,
      "progressClock": 1,
      "positionCounts": {
        "black|.....l..E..W....L........r..........R......d........c..........": 1
      }
    },
    "solution": [
      {
        "from": "f1",
        "to": "f2"
      },
      {
        "from": "b6",
        "to": "c6"
      },
      {
        "from": "f2",
        "to": "e2"
      },
      {
        "from": "b2",
        "to": "c2"
      },
      {
        "from": "e2",
        "to": "e1"
      },
      {
        "from": "c3",
        "to": "d3"
      },
      {
        "from": "e1",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "lion",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0031",
      "ply": 101
    }
  },
  {
    "id": "jungle-tactic-027",
    "variant": "jungle",
    "title": "Black Lion win in 3",
    "initial": {
      "id": "jungle-tactic-027",
      "board": {
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "b7": {
          "color": "black",
          "role": "dog"
        },
        "b6": {
          "color": "red",
          "role": "rat"
        },
        "d8": {
          "color": "black",
          "role": "cat"
        },
        "b2": {
          "color": "red",
          "role": "elephant"
        },
        "c3": {
          "color": "red",
          "role": "lion"
        },
        "f2": {
          "color": "black",
          "role": "lion"
        },
        "e3": {
          "color": "red",
          "role": "wolf"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 52,
      "progressClock": 3,
      "positionCounts": {
        "black|........E...l...L.W......r..........R......d........c..........": 1
      }
    },
    "solution": [
      {
        "from": "f2",
        "to": "e2"
      },
      {
        "from": "b6",
        "to": "c6"
      },
      {
        "from": "e2",
        "to": "d2"
      },
      {
        "from": "b2",
        "to": "c2"
      },
      {
        "from": "d2",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0031",
      "ply": 103
    }
  },
  {
    "id": "jungle-tactic-028",
    "variant": "jungle",
    "title": "Red Lion win in 2",
    "initial": {
      "id": "jungle-tactic-028",
      "board": {
        "d6": {
          "color": "black",
          "role": "elephant"
        },
        "e3": {
          "color": "red",
          "role": "wolf"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "d3": {
          "color": "red",
          "role": "leopard"
        },
        "e2": {
          "color": "red",
          "role": "cat"
        },
        "c3": {
          "color": "red",
          "role": "dog"
        },
        "e8": {
          "color": "black",
          "role": "dog"
        },
        "g8": {
          "color": "black",
          "role": "lion"
        },
        "b8": {
          "color": "red",
          "role": "rat"
        },
        "c1": {
          "color": "red",
          "role": "tiger"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 39,
      "progressClock": 0,
      "positionCounts": {
        "red|..T........C....DPW......r............e...........RL.d.l.......": 1
      }
    },
    "solution": [
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "d6",
        "to": "d7"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0034",
      "ply": 76
    }
  },
  {
    "id": "jungle-tactic-029",
    "variant": "jungle",
    "title": "Red Cat win in 3",
    "initial": {
      "id": "jungle-tactic-029",
      "board": {
        "g9": {
          "color": "black",
          "role": "lion"
        },
        "a9": {
          "color": "black",
          "role": "tiger"
        },
        "c3": {
          "color": "red",
          "role": "leopard"
        },
        "g3": {
          "color": "red",
          "role": "elephant"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        },
        "g8": {
          "color": "black",
          "role": "dog"
        },
        "a5": {
          "color": "red",
          "role": "rat"
        },
        "e2": {
          "color": "red",
          "role": "cat"
        },
        "e1": {
          "color": "red",
          "role": "tiger"
        },
        "d2": {
          "color": "black",
          "role": "leopard"
        },
        "d5": {
          "color": "black",
          "role": "elephant"
        },
        "g4": {
          "color": "black",
          "role": "rat"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 21,
      "progressClock": 0,
      "positionCounts": {
        "red|....T.....pC....P...E......rR..e...................L...dt.....l": 1
      }
    },
    "solution": [
      {
        "from": "e2",
        "to": "d2"
      },
      {
        "from": "g9",
        "to": "f9"
      },
      {
        "from": "c8",
        "to": "d8"
      },
      {
        "from": "a9",
        "to": "b9"
      },
      {
        "from": "d8",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "trap",
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0035",
      "ply": 40
    }
  },
  {
    "id": "jungle-tactic-030",
    "variant": "jungle",
    "title": "Red Lion win in 2",
    "initial": {
      "id": "jungle-tactic-030",
      "board": {
        "g9": {
          "color": "black",
          "role": "lion"
        },
        "e7": {
          "color": "black",
          "role": "leopard"
        },
        "e3": {
          "color": "black",
          "role": "wolf"
        },
        "f3": {
          "color": "red",
          "role": "cat"
        },
        "d2": {
          "color": "red",
          "role": "tiger"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "e2": {
          "color": "red",
          "role": "elephant"
        },
        "c5": {
          "color": "red",
          "role": "rat"
        },
        "a8": {
          "color": "black",
          "role": "tiger"
        },
        "b2": {
          "color": "red",
          "role": "leopard"
        },
        "d6": {
          "color": "black",
          "role": "elephant"
        },
        "d7": {
          "color": "black",
          "role": "cat"
        },
        "f8": {
          "color": "black",
          "role": "dog"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 28,
      "progressClock": 0,
      "positionCounts": {
        "red|........P.TE......wC.....r....R.......e......cp..t.L..d.......l": 1
      }
    },
    "solution": [
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "g9",
        "to": "f9"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0036",
      "ply": 54
    }
  },
  {
    "id": "jungle-tactic-031",
    "variant": "jungle",
    "title": "Black Tiger win in 3",
    "initial": {
      "id": "jungle-tactic-031",
      "board": {
        "c3": {
          "color": "black",
          "role": "tiger"
        },
        "b3": {
          "color": "red",
          "role": "dog"
        },
        "f3": {
          "color": "red",
          "role": "wolf"
        },
        "f9": {
          "color": "black",
          "role": "dog"
        },
        "b6": {
          "color": "red",
          "role": "rat"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "d2": {
          "color": "red",
          "role": "cat"
        },
        "d6": {
          "color": "black",
          "role": "wolf"
        },
        "d7": {
          "color": "black",
          "role": "leopard"
        },
        "e3": {
          "color": "red",
          "role": "tiger"
        },
        "d8": {
          "color": "black",
          "role": "elephant"
        },
        "c8": {
          "color": "black",
          "role": "cat"
        },
        "g6": {
          "color": "red",
          "role": "elephant"
        },
        "d5": {
          "color": "red",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 28,
      "progressClock": 1,
      "positionCounts": {
        "black|..........C....Dt.TW.....r.....L....R.w..E...p.....ce........d.": 1
      }
    },
    "solution": [
      {
        "from": "c3",
        "to": "c2"
      },
      {
        "from": "b3",
        "to": "c3"
      },
      {
        "from": "c2",
        "to": "d2"
      },
      {
        "from": "f3",
        "to": "g3"
      },
      {
        "from": "d2",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "tiger",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0037",
      "ply": 55
    }
  },
  {
    "id": "jungle-tactic-032",
    "variant": "jungle",
    "title": "Red Lion win in 2",
    "initial": {
      "id": "jungle-tactic-032",
      "board": {
        "d5": {
          "color": "black",
          "role": "leopard"
        },
        "d3": {
          "color": "red",
          "role": "cat"
        },
        "d2": {
          "color": "red",
          "role": "dog"
        },
        "b9": {
          "color": "black",
          "role": "tiger"
        },
        "f3": {
          "color": "red",
          "role": "elephant"
        },
        "f7": {
          "color": "black",
          "role": "dog"
        },
        "g5": {
          "color": "red",
          "role": "wolf"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        },
        "g3": {
          "color": "black",
          "role": "rat"
        },
        "d8": {
          "color": "black",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 54,
      "progressClock": 0,
      "positionCounts": {
        "red|..........D......C.Er..........p..W............d...Ll....t.....": 1
      }
    },
    "solution": [
      {
        "from": "c8",
        "to": "d8"
      },
      {
        "from": "d5",
        "to": "d6"
      },
      {
        "from": "d8",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0041",
      "ply": 106
    }
  },
  {
    "id": "jungle-tactic-033",
    "variant": "jungle",
    "title": "Black Elephant win in 3",
    "initial": {
      "id": "jungle-tactic-033",
      "board": {
        "g9": {
          "color": "black",
          "role": "lion"
        },
        "a9": {
          "color": "red",
          "role": "lion"
        },
        "b8": {
          "color": "black",
          "role": "cat"
        },
        "e3": {
          "color": "red",
          "role": "wolf"
        },
        "e8": {
          "color": "black",
          "role": "leopard"
        },
        "a4": {
          "color": "red",
          "role": "rat"
        },
        "f3": {
          "color": "red",
          "role": "elephant"
        },
        "e9": {
          "color": "black",
          "role": "dog"
        },
        "g3": {
          "color": "red",
          "role": "tiger"
        },
        "d8": {
          "color": "black",
          "role": "wolf"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "d2": {
          "color": "red",
          "role": "leopard"
        },
        "c2": {
          "color": "red",
          "role": "dog"
        },
        "c3": {
          "color": "black",
          "role": "elephant"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 25,
      "progressClock": 0,
      "positionCounts": {
        "black|.........DP.....e.WETR...r........................c.wp..L...d.l": 1
      }
    },
    "solution": [
      {
        "from": "c3",
        "to": "c2"
      },
      {
        "from": "a9",
        "to": "b9"
      },
      {
        "from": "c2",
        "to": "d2"
      },
      {
        "from": "e3",
        "to": "d3"
      },
      {
        "from": "d2",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "elephant",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0044",
      "ply": 49
    }
  },
  {
    "id": "jungle-tactic-034",
    "variant": "jungle",
    "title": "Black Elephant win in 2",
    "initial": {
      "id": "jungle-tactic-034",
      "board": {
        "g9": {
          "color": "black",
          "role": "lion"
        },
        "a9": {
          "color": "red",
          "role": "lion"
        },
        "b8": {
          "color": "black",
          "role": "cat"
        },
        "e3": {
          "color": "red",
          "role": "wolf"
        },
        "e8": {
          "color": "black",
          "role": "leopard"
        },
        "a4": {
          "color": "red",
          "role": "rat"
        },
        "f3": {
          "color": "red",
          "role": "elephant"
        },
        "e9": {
          "color": "black",
          "role": "dog"
        },
        "g3": {
          "color": "red",
          "role": "tiger"
        },
        "d8": {
          "color": "black",
          "role": "wolf"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "c2": {
          "color": "black",
          "role": "elephant"
        },
        "d3": {
          "color": "red",
          "role": "leopard"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 26,
      "progressClock": 1,
      "positionCounts": {
        "black|.........e.......PWETR...r........................c.wp..L...d.l": 1
      }
    },
    "solution": [
      {
        "from": "c2",
        "to": "c1"
      },
      {
        "from": "a9",
        "to": "b9"
      },
      {
        "from": "c1",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "elephant",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0044",
      "ply": 51
    }
  },
  {
    "id": "jungle-tactic-035",
    "variant": "jungle",
    "title": "Red Lion win in 2",
    "initial": {
      "id": "jungle-tactic-035",
      "board": {
        "b3": {
          "color": "red",
          "role": "leopard"
        },
        "c3": {
          "color": "red",
          "role": "wolf"
        },
        "f3": {
          "color": "red",
          "role": "cat"
        },
        "d3": {
          "color": "red",
          "role": "dog"
        },
        "c7": {
          "color": "black",
          "role": "cat"
        },
        "b7": {
          "color": "black",
          "role": "tiger"
        },
        "g8": {
          "color": "black",
          "role": "dog"
        },
        "f9": {
          "color": "red",
          "role": "lion"
        },
        "d8": {
          "color": "black",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 38,
      "progressClock": 0,
      "positionCounts": {
        "red|...............PWD.C.......................tc.......l..d.....L.": 1
      }
    },
    "solution": [
      {
        "from": "f9",
        "to": "e9"
      },
      {
        "from": "c7",
        "to": "d7"
      },
      {
        "from": "e9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0046",
      "ply": 74
    }
  },
  {
    "id": "jungle-tactic-036",
    "variant": "jungle",
    "title": "Red Elephant win in 2",
    "initial": {
      "id": "jungle-tactic-036",
      "board": {
        "a9": {
          "color": "black",
          "role": "tiger"
        },
        "c3": {
          "color": "red",
          "role": "leopard"
        },
        "f3": {
          "color": "red",
          "role": "cat"
        },
        "f9": {
          "color": "black",
          "role": "dog"
        },
        "b3": {
          "color": "red",
          "role": "rat"
        },
        "d2": {
          "color": "red",
          "role": "wolf"
        },
        "e8": {
          "color": "red",
          "role": "elephant"
        },
        "c2": {
          "color": "red",
          "role": "dog"
        },
        "b7": {
          "color": "black",
          "role": "cat"
        },
        "e2": {
          "color": "red",
          "role": "tiger"
        },
        "f6": {
          "color": "black",
          "role": "rat"
        },
        "g8": {
          "color": "black",
          "role": "lion"
        },
        "a4": {
          "color": "black",
          "role": "elephant"
        },
        "d8": {
          "color": "black",
          "role": "wolf"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 26,
      "progressClock": 0,
      "positionCounts": {
        "red|.........DWT...RP..C.e..................r..c........wE.lt....d.": 1
      }
    },
    "solution": [
      {
        "from": "e8",
        "to": "d8"
      },
      {
        "from": "a9",
        "to": "b9"
      },
      {
        "from": "d8",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "elephant",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0050",
      "ply": 50
    }
  },
  {
    "id": "jungle-tactic-037",
    "variant": "jungle",
    "title": "Black Lion win in 4",
    "initial": {
      "id": "jungle-tactic-037",
      "board": {
        "a3": {
          "color": "red",
          "role": "rat"
        },
        "d8": {
          "color": "black",
          "role": "leopard"
        },
        "c8": {
          "color": "black",
          "role": "cat"
        },
        "d3": {
          "color": "black",
          "role": "lion"
        },
        "c3": {
          "color": "red",
          "role": "dog"
        },
        "d7": {
          "color": "black",
          "role": "elephant"
        },
        "g3": {
          "color": "red",
          "role": "cat"
        },
        "b3": {
          "color": "red",
          "role": "lion"
        },
        "c2": {
          "color": "red",
          "role": "leopard"
        },
        "c7": {
          "color": "black",
          "role": "tiger"
        },
        "d2": {
          "color": "red",
          "role": "tiger"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 26,
      "progressClock": 5,
      "positionCounts": {
        "black|.........PT...RLDl..C.......................te.....cp..........": 1
      }
    },
    "solution": [
      {
        "from": "d3",
        "to": "e3"
      },
      {
        "from": "a3",
        "to": "a4"
      },
      {
        "from": "e3",
        "to": "e2"
      },
      {
        "from": "c3",
        "to": "d3"
      },
      {
        "from": "e2",
        "to": "e1"
      },
      {
        "from": "g3",
        "to": "f3"
      },
      {
        "from": "e1",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0051",
      "ply": 51
    }
  },
  {
    "id": "jungle-tactic-038",
    "variant": "jungle",
    "title": "Black Lion win in 3",
    "initial": {
      "id": "jungle-tactic-038",
      "board": {
        "a3": {
          "color": "red",
          "role": "rat"
        },
        "d8": {
          "color": "black",
          "role": "leopard"
        },
        "c8": {
          "color": "black",
          "role": "cat"
        },
        "c3": {
          "color": "red",
          "role": "dog"
        },
        "d7": {
          "color": "black",
          "role": "elephant"
        },
        "g3": {
          "color": "red",
          "role": "cat"
        },
        "c2": {
          "color": "red",
          "role": "leopard"
        },
        "c7": {
          "color": "black",
          "role": "tiger"
        },
        "d2": {
          "color": "red",
          "role": "tiger"
        },
        "e3": {
          "color": "black",
          "role": "lion"
        },
        "b7": {
          "color": "red",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 27,
      "progressClock": 7,
      "positionCounts": {
        "black|.........PT...R.D.l.C......................Lte.....cp..........": 1
      }
    },
    "solution": [
      {
        "from": "e3",
        "to": "e2"
      },
      {
        "from": "a3",
        "to": "b3"
      },
      {
        "from": "e2",
        "to": "e1"
      },
      {
        "from": "c3",
        "to": "d3"
      },
      {
        "from": "e1",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0051",
      "ply": 53
    }
  },
  {
    "id": "jungle-tactic-039",
    "variant": "jungle",
    "title": "Black Lion win in 2",
    "initial": {
      "id": "jungle-tactic-039",
      "board": {
        "a3": {
          "color": "red",
          "role": "rat"
        },
        "d8": {
          "color": "black",
          "role": "leopard"
        },
        "c8": {
          "color": "black",
          "role": "cat"
        },
        "c3": {
          "color": "red",
          "role": "dog"
        },
        "d7": {
          "color": "black",
          "role": "elephant"
        },
        "g3": {
          "color": "red",
          "role": "cat"
        },
        "c2": {
          "color": "red",
          "role": "leopard"
        },
        "c7": {
          "color": "red",
          "role": "lion"
        },
        "d2": {
          "color": "red",
          "role": "tiger"
        },
        "e2": {
          "color": "black",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "black"
      },
      "moveNumber": 28,
      "progressClock": 0,
      "positionCounts": {
        "black|.........PTl..R.D...C.......................Le.....cp..........": 1
      }
    },
    "solution": [
      {
        "from": "e2",
        "to": "e1"
      },
      {
        "from": "a3",
        "to": "b3"
      },
      {
        "from": "e1",
        "to": "d1"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "black"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0051",
      "ply": 55
    }
  },
  {
    "id": "jungle-tactic-040",
    "variant": "jungle",
    "title": "Red Wolf win in 3",
    "initial": {
      "id": "jungle-tactic-040",
      "board": {
        "c3": {
          "color": "red",
          "role": "leopard"
        },
        "g8": {
          "color": "black",
          "role": "rat"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        },
        "f3": {
          "color": "red",
          "role": "elephant"
        },
        "c6": {
          "color": "red",
          "role": "rat"
        },
        "c7": {
          "color": "black",
          "role": "cat"
        },
        "e2": {
          "color": "red",
          "role": "wolf"
        },
        "e8": {
          "color": "black",
          "role": "elephant"
        },
        "d2": {
          "color": "black",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 47,
      "progressClock": 1,
      "positionCounts": {
        "red|..........lW....P..E.................R......c......L.e.r.......": 1
      }
    },
    "solution": [
      {
        "from": "e2",
        "to": "d2"
      },
      {
        "from": "g8",
        "to": "f8"
      },
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "c7",
        "to": "d7"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "trap",
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0053",
      "ply": 92
    }
  },
  {
    "id": "jungle-tactic-041",
    "variant": "jungle",
    "title": "Red Lion win in 2",
    "initial": {
      "id": "jungle-tactic-041",
      "board": {
        "c3": {
          "color": "red",
          "role": "leopard"
        },
        "g8": {
          "color": "black",
          "role": "rat"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        },
        "f3": {
          "color": "red",
          "role": "elephant"
        },
        "c6": {
          "color": "red",
          "role": "rat"
        },
        "e8": {
          "color": "black",
          "role": "elephant"
        },
        "d2": {
          "color": "red",
          "role": "wolf"
        },
        "d7": {
          "color": "black",
          "role": "cat"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 48,
      "progressClock": 1,
      "positionCounts": {
        "red|..........W.....P..E.................R.......c.....L.e.r.......": 1
      }
    },
    "solution": [
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "g8",
        "to": "f8"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0053",
      "ply": 94
    }
  },
  {
    "id": "jungle-tactic-042",
    "variant": "jungle",
    "title": "Red Lion win in 4",
    "initial": {
      "id": "jungle-tactic-042",
      "board": {
        "f3": {
          "color": "red",
          "role": "cat"
        },
        "c3": {
          "color": "red",
          "role": "dog"
        },
        "e3": {
          "color": "red",
          "role": "wolf"
        },
        "e8": {
          "color": "black",
          "role": "dog"
        },
        "d3": {
          "color": "red",
          "role": "tiger"
        },
        "b5": {
          "color": "red",
          "role": "rat"
        },
        "e2": {
          "color": "red",
          "role": "elephant"
        },
        "d8": {
          "color": "black",
          "role": "tiger"
        },
        "b3": {
          "color": "red",
          "role": "leopard"
        },
        "f7": {
          "color": "black",
          "role": "lion"
        },
        "d7": {
          "color": "red",
          "role": "lion"
        },
        "f4": {
          "color": "black",
          "role": "rat"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 45,
      "progressClock": 17,
      "positionCounts": {
        "red|...........E...PDTWC......r..R...............L.l....td.........": 1
      }
    },
    "solution": [
      {
        "from": "d7",
        "to": "c7"
      },
      {
        "from": "e8",
        "to": "f8"
      },
      {
        "from": "c7",
        "to": "c8"
      },
      {
        "from": "d8",
        "to": "e8"
      },
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "f7",
        "to": "g7"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0054",
      "ply": 88
    }
  },
  {
    "id": "jungle-tactic-043",
    "variant": "jungle",
    "title": "Red Lion win in 3",
    "initial": {
      "id": "jungle-tactic-043",
      "board": {
        "f3": {
          "color": "red",
          "role": "cat"
        },
        "c3": {
          "color": "red",
          "role": "dog"
        },
        "e3": {
          "color": "red",
          "role": "wolf"
        },
        "e8": {
          "color": "black",
          "role": "dog"
        },
        "d3": {
          "color": "red",
          "role": "tiger"
        },
        "b5": {
          "color": "red",
          "role": "rat"
        },
        "e2": {
          "color": "red",
          "role": "elephant"
        },
        "d8": {
          "color": "black",
          "role": "tiger"
        },
        "b3": {
          "color": "red",
          "role": "leopard"
        },
        "f7": {
          "color": "black",
          "role": "lion"
        },
        "c7": {
          "color": "red",
          "role": "lion"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 46,
      "progressClock": 19,
      "positionCounts": {
        "red|...........E...PDTWC.....r...R..............L..l....td.........": 1
      }
    },
    "solution": [
      {
        "from": "c7",
        "to": "c8"
      },
      {
        "from": "e8",
        "to": "f8"
      },
      {
        "from": "c8",
        "to": "d8"
      },
      {
        "from": "f7",
        "to": "g7"
      },
      {
        "from": "d8",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "rank-up",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0054",
      "ply": 90
    }
  },
  {
    "id": "jungle-tactic-044",
    "variant": "jungle",
    "title": "Red Lion win in 2",
    "initial": {
      "id": "jungle-tactic-044",
      "board": {
        "f3": {
          "color": "black",
          "role": "lion"
        },
        "c3": {
          "color": "red",
          "role": "dog"
        },
        "e3": {
          "color": "red",
          "role": "wolf"
        },
        "e8": {
          "color": "black",
          "role": "dog"
        },
        "d3": {
          "color": "red",
          "role": "tiger"
        },
        "b5": {
          "color": "red",
          "role": "rat"
        },
        "e2": {
          "color": "red",
          "role": "elephant"
        },
        "d8": {
          "color": "black",
          "role": "tiger"
        },
        "b3": {
          "color": "red",
          "role": "leopard"
        },
        "e4": {
          "color": "black",
          "role": "rat"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 47,
      "progressClock": 0,
      "positionCounts": {
        "red|...........E...PDTWl.....r...R.....................Ltd.........": 1
      }
    },
    "solution": [
      {
        "from": "c8",
        "to": "c9"
      },
      {
        "from": "f3",
        "to": "g3"
      },
      {
        "from": "c9",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0054",
      "ply": 92
    }
  },
  {
    "id": "jungle-tactic-045",
    "variant": "jungle",
    "title": "Red Cat win in 3",
    "initial": {
      "id": "jungle-tactic-045",
      "board": {
        "g3": {
          "color": "red",
          "role": "elephant"
        },
        "b3": {
          "color": "red",
          "role": "dog"
        },
        "b9": {
          "color": "black",
          "role": "tiger"
        },
        "d2": {
          "color": "black",
          "role": "lion"
        },
        "e3": {
          "color": "red",
          "role": "wolf"
        },
        "a6": {
          "color": "black",
          "role": "elephant"
        },
        "e2": {
          "color": "red",
          "role": "cat"
        },
        "b8": {
          "color": "black",
          "role": "dog"
        },
        "b6": {
          "color": "red",
          "role": "rat"
        },
        "g5": {
          "color": "black",
          "role": "rat"
        },
        "c8": {
          "color": "red",
          "role": "lion"
        }
      },
      "status": {
        "type": "playing",
        "turn": "red"
      },
      "moveNumber": 35,
      "progressClock": 0,
      "positionCounts": {
        "red|..........lC...D..W.E.............reR.............dL.....t.....": 1
      }
    },
    "solution": [
      {
        "from": "e2",
        "to": "d2"
      },
      {
        "from": "b9",
        "to": "c9"
      },
      {
        "from": "c8",
        "to": "d8"
      },
      {
        "from": "a6",
        "to": "a7"
      },
      {
        "from": "d8",
        "to": "d9"
      }
    ],
    "goal": {
      "type": "win",
      "winner": "red"
    },
    "themes": [
      "trap",
      "lion",
      "den-race"
    ],
    "sourceGame": {
      "gameId": "jungle-sp-0056",
      "ply": 68
    }
  }
];
