// Generated by the Jungle material-tactic miner
// (scripts/variant-lab/jungle-material-miner.ts). Do not hand-edit; re-run the
// miner and paste its `--emit-module` output here.
//
// Material tactics: the solver forces a decisive material gain (a captured piece)
// with the game still in progress. Found by a pure-material minimax with
// quiescence, so the gain is exact; `centipawns` = the guaranteed value won.
//
// The local structural type mirrors `JunglePuzzle` in puzzles-jungle.ts so the
// array is assignable when spread there, while keeping this file free of a
// circular import.

import type { JUNGLE_SPEC_ID } from './game-specs.js';
import type { JungleColor, JungleGameState, JungleMove } from './variants-jungle.js';

type MaterialJunglePuzzleTheme =
  | 'trap'
  | 'water-leap'
  | 'rank-up'
  | 'rat'
  | 'elephant'
  | 'lion'
  | 'tiger'
  | 'winning';

type MaterialJunglePuzzle = {
  id: string;
  variant: typeof JUNGLE_SPEC_ID;
  title: string;
  initial: JungleGameState;
  solution: JungleMove[];
  goal: { type: 'winning-advantage'; winner?: JungleColor; centipawns?: number };
  themes: MaterialJunglePuzzleTheme[];
};

export const MATERIAL_JUNGLE_PUZZLES: readonly MaterialJunglePuzzle[] = [
  {
    id: 'jungle-material-001',
    variant: 'jungle',
    title: 'Black Cat wins material (+65)',
    initial: {
      id: 'jungle-material-001',
      board: {
        a9: {
          color: 'black',
          role: 'tiger',
        },
        a6: {
          color: 'red',
          role: 'rat',
        },
        a2: {
          color: 'red',
          role: 'lion',
        },
        f2: {
          color: 'red',
          role: 'tiger',
        },
        b1: {
          color: 'red',
          role: 'dog',
        },
        b3: {
          color: 'red',
          role: 'leopard',
        },
        e7: {
          color: 'black',
          role: 'leopard',
        },
        g1: {
          color: 'red',
          role: 'cat',
        },
        g8: {
          color: 'black',
          role: 'dog',
        },
        d2: {
          color: 'red',
          role: 'wolf',
        },
        b8: {
          color: 'black',
          role: 'wolf',
        },
        e6: {
          color: 'black',
          role: 'rat',
        },
        g5: {
          color: 'red',
          role: 'elephant',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 28,
      progressClock: 0,
      positionCounts: {
        'black|.D....CL..W.T..P..................ER...r..c...p...w....dt......': 1,
      },
    },
    solution: [
      {
        from: 'a7',
        to: 'a6',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 65,
    },
    themes: ['winning', 'rank-up'],
  },
  {
    id: 'jungle-material-002',
    variant: 'jungle',
    title: 'Black Rat wins material (+100)',
    initial: {
      id: 'jungle-material-002',
      board: {
        a6: {
          color: 'black',
          role: 'cat',
        },
        f2: {
          color: 'red',
          role: 'tiger',
        },
        g1: {
          color: 'red',
          role: 'cat',
        },
        g8: {
          color: 'black',
          role: 'dog',
        },
        g5: {
          color: 'red',
          role: 'elephant',
        },
        b8: {
          color: 'black',
          role: 'wolf',
        },
        a1: {
          color: 'red',
          role: 'lion',
        },
        d7: {
          color: 'black',
          role: 'leopard',
        },
        a3: {
          color: 'red',
          role: 'leopard',
        },
        a8: {
          color: 'black',
          role: 'tiger',
        },
        b2: {
          color: 'red',
          role: 'dog',
        },
        g6: {
          color: 'black',
          role: 'rat',
        },
        d2: {
          color: 'red',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 35,
      progressClock: 11,
      positionCounts: {
        'black|L.....C.D.W.T.P...................Ec.....r...p...tw....d.......': 1,
      },
    },
    solution: [
      {
        from: 'g6',
        to: 'g5',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 100,
    },
    themes: ['winning', 'rat', 'rank-up'],
  },
  {
    id: 'jungle-material-003',
    variant: 'jungle',
    title: 'Red Tiger wins material (+40)',
    initial: {
      id: 'jungle-material-003',
      board: {
        g8: {
          color: 'black',
          role: 'dog',
        },
        g5: {
          color: 'black',
          role: 'rat',
        },
        a1: {
          color: 'red',
          role: 'lion',
        },
        a3: {
          color: 'red',
          role: 'leopard',
        },
        f1: {
          color: 'red',
          role: 'cat',
        },
        a2: {
          color: 'red',
          role: 'dog',
        },
        b8: {
          color: 'black',
          role: 'tiger',
        },
        a5: {
          color: 'black',
          role: 'cat',
        },
        e3: {
          color: 'red',
          role: 'wolf',
        },
        f8: {
          color: 'black',
          role: 'wolf',
        },
        f7: {
          color: 'red',
          role: 'tiger',
        },
        d5: {
          color: 'black',
          role: 'leopard',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 46,
      progressClock: 14,
      positionCounts: {
        'red|L....C.D......P...W.........c..p..r............T..t...wd.......': 1,
      },
    },
    solution: [
      {
        from: 'f7',
        to: 'f8',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 40,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-004',
    variant: 'jungle',
    title: 'Black Tiger wins material (+40)',
    initial: {
      id: 'jungle-material-004',
      board: {
        g5: {
          color: 'black',
          role: 'rat',
        },
        a1: {
          color: 'red',
          role: 'lion',
        },
        a2: {
          color: 'red',
          role: 'dog',
        },
        e1: {
          color: 'red',
          role: 'cat',
        },
        a4: {
          color: 'red',
          role: 'leopard',
        },
        d6: {
          color: 'black',
          role: 'leopard',
        },
        d2: {
          color: 'red',
          role: 'wolf',
        },
        d3: {
          color: 'black',
          role: 'tiger',
        },
        g9: {
          color: 'red',
          role: 'tiger',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 52,
      progressClock: 4,
      positionCounts: {
        'black|L...C..D..W......t...P............r...p.......................T': 1,
      },
    },
    solution: [
      {
        from: 'd3',
        to: 'd2',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 40,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-005',
    variant: 'jungle',
    title: 'Red Leopard wins material (+40)',
    initial: {
      id: 'jungle-material-005',
      board: {
        d4: {
          color: 'red',
          role: 'leopard',
        },
        e1: {
          color: 'red',
          role: 'tiger',
        },
        f1: {
          color: 'red',
          role: 'wolf',
        },
        e4: {
          color: 'black',
          role: 'rat',
        },
        d2: {
          color: 'red',
          role: 'lion',
        },
        e8: {
          color: 'black',
          role: 'leopard',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        f8: {
          color: 'black',
          role: 'lion',
        },
        g5: {
          color: 'black',
          role: 'dog',
        },
        c7: {
          color: 'black',
          role: 'cat',
        },
        a5: {
          color: 'black',
          role: 'tiger',
        },
        c3: {
          color: 'red',
          role: 'dog',
        },
        d5: {
          color: 'black',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 65,
      progressClock: 6,
      positionCounts: {
        'red|....TW....L.E...D.......Pr..t..w..d.........c........pl........': 1,
      },
    },
    solution: [
      {
        from: 'd4',
        to: 'd5',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 40,
    },
    themes: ['winning', 'rank-up'],
  },
  {
    id: 'jungle-material-006',
    variant: 'jungle',
    title: 'Black Lion wins material (+40)',
    initial: {
      id: 'jungle-material-006',
      board: {
        g2: {
          color: 'red',
          role: 'cat',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
        c6: {
          color: 'red',
          role: 'rat',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        c7: {
          color: 'black',
          role: 'wolf',
        },
        b7: {
          color: 'black',
          role: 'tiger',
        },
        f9: {
          color: 'black',
          role: 'rat',
        },
        b2: {
          color: 'red',
          role: 'leopard',
        },
        c1: {
          color: 'red',
          role: 'dog',
        },
        f7: {
          color: 'black',
          role: 'lion',
        },
        f1: {
          color: 'red',
          role: 'tiger',
        },
        b1: {
          color: 'red',
          role: 'lion',
        },
        a9: {
          color: 'black',
          role: 'elephant',
        },
        g5: {
          color: 'red',
          role: 'elephant',
        },
        f8: {
          color: 'black',
          role: 'leopard',
        },
        f3: {
          color: 'red',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 41,
      progressClock: 81,
      positionCounts: {
        'black|.LD..T..P....C.....W..............E..R.....tw..l...c..p.e...dr.': 1,
      },
    },
    solution: [
      {
        from: 'f7',
        to: 'f3',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 40,
    },
    themes: ['winning', 'lion', 'water-leap', 'rank-up'],
  },
  {
    id: 'jungle-material-007',
    variant: 'jungle',
    title: 'Black Lion wins material (+75)',
    initial: {
      id: 'jungle-material-007',
      board: {
        g2: {
          color: 'red',
          role: 'cat',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        c7: {
          color: 'black',
          role: 'wolf',
        },
        b7: {
          color: 'black',
          role: 'tiger',
        },
        f9: {
          color: 'black',
          role: 'rat',
        },
        b2: {
          color: 'red',
          role: 'leopard',
        },
        c1: {
          color: 'red',
          role: 'dog',
        },
        b1: {
          color: 'red',
          role: 'lion',
        },
        a9: {
          color: 'black',
          role: 'elephant',
        },
        g5: {
          color: 'red',
          role: 'elephant',
        },
        f8: {
          color: 'black',
          role: 'leopard',
        },
        f3: {
          color: 'black',
          role: 'lion',
        },
        e8: {
          color: 'black',
          role: 'dog',
        },
        d6: {
          color: 'red',
          role: 'rat',
        },
        f2: {
          color: 'red',
          role: 'tiger',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 43,
      progressClock: 1,
      positionCounts: {
        'black|.LD.....P...TC.....l..............E...R....tw......c.dp.e....r.': 1,
      },
    },
    solution: [
      {
        from: 'f3',
        to: 'f2',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 75,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-008',
    variant: 'jungle',
    title: 'Red Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-008',
      board: {
        b2: {
          color: 'red',
          role: 'leopard',
        },
        c1: {
          color: 'red',
          role: 'dog',
        },
        a9: {
          color: 'black',
          role: 'elephant',
        },
        f8: {
          color: 'black',
          role: 'leopard',
        },
        e8: {
          color: 'black',
          role: 'dog',
        },
        d8: {
          color: 'black',
          role: 'wolf',
        },
        a8: {
          color: 'black',
          role: 'cat',
        },
        a2: {
          color: 'red',
          role: 'lion',
        },
        g8: {
          color: 'black',
          role: 'rat',
        },
        g4: {
          color: 'red',
          role: 'elephant',
        },
        b8: {
          color: 'black',
          role: 'tiger',
        },
        e7: {
          color: 'red',
          role: 'tiger',
        },
        g3: {
          color: 'black',
          role: 'lion',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 53,
      progressClock: 4,
      positionCounts: {
        'red|..D....LP...........l......E..................T..ct.wdpre......': 1,
      },
    },
    solution: [
      {
        from: 'g4',
        to: 'g3',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-009',
    variant: 'jungle',
    title: 'Red Tiger wins material (+50)',
    initial: {
      id: 'jungle-material-009',
      board: {
        b2: {
          color: 'red',
          role: 'leopard',
        },
        c1: {
          color: 'red',
          role: 'dog',
        },
        f8: {
          color: 'black',
          role: 'leopard',
        },
        e8: {
          color: 'red',
          role: 'tiger',
        },
        d8: {
          color: 'black',
          role: 'wolf',
        },
        a8: {
          color: 'black',
          role: 'cat',
        },
        a2: {
          color: 'red',
          role: 'lion',
        },
        g8: {
          color: 'black',
          role: 'rat',
        },
        g3: {
          color: 'red',
          role: 'elephant',
        },
        c8: {
          color: 'black',
          role: 'tiger',
        },
        b9: {
          color: 'black',
          role: 'elephant',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 55,
      progressClock: 1,
      positionCounts: {
        'red|..D....LP...........E............................c.twTpr.e.....': 1,
      },
    },
    solution: [
      {
        from: 'e8',
        to: 'f8',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 50,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-010',
    variant: 'jungle',
    title: 'Red Lion wins material (+90)',
    initial: {
      id: 'jungle-material-010',
      board: {
        g9: {
          color: 'black',
          role: 'dog',
        },
        g1: {
          color: 'red',
          role: 'wolf',
        },
        g2: {
          color: 'red',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'leopard',
        },
        d8: {
          color: 'black',
          role: 'rat',
        },
        c2: {
          color: 'red',
          role: 'lion',
        },
        g3: {
          color: 'red',
          role: 'tiger',
        },
        f7: {
          color: 'black',
          role: 'wolf',
        },
        c9: {
          color: 'black',
          role: 'tiger',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        c3: {
          color: 'black',
          role: 'lion',
        },
        b2: {
          color: 'red',
          role: 'rat',
        },
        b9: {
          color: 'black',
          role: 'elephant',
        },
        f3: {
          color: 'red',
          role: 'leopard',
        },
        c1: {
          color: 'red',
          role: 'cat',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 48,
      progressClock: 0,
      positionCounts: {
        'red|..C...W.RL...E..l..PT..........................w...crp...et...d': 1,
      },
    },
    solution: [
      {
        from: 'c2',
        to: 'c3',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 90,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-011',
    variant: 'jungle',
    title: 'Black Lion wins material (+90)',
    initial: {
      id: 'jungle-material-011',
      board: {
        g9: {
          color: 'black',
          role: 'dog',
        },
        g1: {
          color: 'red',
          role: 'wolf',
        },
        g2: {
          color: 'red',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'leopard',
        },
        d8: {
          color: 'black',
          role: 'rat',
        },
        c2: {
          color: 'red',
          role: 'lion',
        },
        g3: {
          color: 'red',
          role: 'tiger',
        },
        f7: {
          color: 'black',
          role: 'wolf',
        },
        c9: {
          color: 'black',
          role: 'tiger',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        c3: {
          color: 'black',
          role: 'lion',
        },
        b2: {
          color: 'red',
          role: 'rat',
        },
        b9: {
          color: 'black',
          role: 'elephant',
        },
        c1: {
          color: 'red',
          role: 'cat',
        },
        f2: {
          color: 'red',
          role: 'leopard',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 48,
      progressClock: 1,
      positionCounts: {
        'black|..C...W.RL..PE..l...T..........................w...crp...et...d': 1,
      },
    },
    solution: [
      {
        from: 'c3',
        to: 'c2',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 90,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-012',
    variant: 'jungle',
    title: 'Black Lion wins material (+65)',
    initial: {
      id: 'jungle-material-012',
      board: {
        g9: {
          color: 'black',
          role: 'dog',
        },
        g1: {
          color: 'red',
          role: 'wolf',
        },
        g2: {
          color: 'red',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'leopard',
        },
        d8: {
          color: 'black',
          role: 'rat',
        },
        c2: {
          color: 'black',
          role: 'lion',
        },
        g3: {
          color: 'red',
          role: 'tiger',
        },
        f7: {
          color: 'black',
          role: 'wolf',
        },
        c9: {
          color: 'black',
          role: 'tiger',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        b2: {
          color: 'red',
          role: 'rat',
        },
        b9: {
          color: 'black',
          role: 'elephant',
        },
        c1: {
          color: 'red',
          role: 'cat',
        },
        f1: {
          color: 'red',
          role: 'leopard',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 49,
      progressClock: 1,
      positionCounts: {
        'black|..C..PW.Rl...E......T..........................w...crp...et...d': 1,
      },
    },
    solution: [
      {
        from: 'c2',
        to: 'b2',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 65,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-013',
    variant: 'jungle',
    title: 'Red Rat wins material (+90)',
    initial: {
      id: 'jungle-material-013',
      board: {
        g9: {
          color: 'black',
          role: 'dog',
        },
        g1: {
          color: 'red',
          role: 'wolf',
        },
        g2: {
          color: 'red',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'leopard',
        },
        d8: {
          color: 'black',
          role: 'rat',
        },
        g3: {
          color: 'red',
          role: 'tiger',
        },
        c9: {
          color: 'black',
          role: 'tiger',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        b9: {
          color: 'black',
          role: 'elephant',
        },
        c1: {
          color: 'black',
          role: 'lion',
        },
        f1: {
          color: 'red',
          role: 'leopard',
        },
        f8: {
          color: 'black',
          role: 'wolf',
        },
        b1: {
          color: 'red',
          role: 'rat',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 51,
      progressClock: 0,
      positionCounts: {
        'red|.Rl..PW......E......T..............................crpw..et...d': 1,
      },
    },
    solution: [
      {
        from: 'b1',
        to: 'c1',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 90,
    },
    themes: ['winning', 'rat', 'trap'],
  },
  {
    id: 'jungle-material-014',
    variant: 'jungle',
    title: 'Red Tiger wins material (+40)',
    initial: {
      id: 'jungle-material-014',
      board: {
        g1: {
          color: 'red',
          role: 'wolf',
        },
        d8: {
          color: 'black',
          role: 'rat',
        },
        c2: {
          color: 'black',
          role: 'lion',
        },
        a9: {
          color: 'black',
          role: 'elephant',
        },
        f7: {
          color: 'black',
          role: 'wolf',
        },
        f1: {
          color: 'red',
          role: 'leopard',
        },
        c8: {
          color: 'black',
          role: 'tiger',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        b7: {
          color: 'black',
          role: 'cat',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
        g7: {
          color: 'red',
          role: 'tiger',
        },
        e7: {
          color: 'black',
          role: 'leopard',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 64,
      progressClock: 24,
      positionCounts: {
        'red|.....PW..l..E..............................c..pwT..tr...e...d..': 1,
      },
    },
    solution: [
      {
        from: 'g7',
        to: 'f7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 40,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-015',
    variant: 'jungle',
    title: 'Red Tiger wins material (+50)',
    initial: {
      id: 'jungle-material-015',
      board: {
        g1: {
          color: 'red',
          role: 'wolf',
        },
        d8: {
          color: 'black',
          role: 'rat',
        },
        c2: {
          color: 'black',
          role: 'lion',
        },
        a9: {
          color: 'black',
          role: 'elephant',
        },
        f7: {
          color: 'red',
          role: 'tiger',
        },
        f1: {
          color: 'red',
          role: 'leopard',
        },
        c8: {
          color: 'black',
          role: 'tiger',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
        e7: {
          color: 'black',
          role: 'leopard',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 65,
      progressClock: 1,
      positionCounts: {
        'red|.....PW..l..E.............................c...pT...tr...e...d..': 1,
      },
    },
    solution: [
      {
        from: 'f7',
        to: 'e7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 50,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-016',
    variant: 'jungle',
    title: 'Red Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-016',
      board: {
        g1: {
          color: 'red',
          role: 'wolf',
        },
        d8: {
          color: 'black',
          role: 'rat',
        },
        a9: {
          color: 'black',
          role: 'elephant',
        },
        f7: {
          color: 'red',
          role: 'tiger',
        },
        f1: {
          color: 'red',
          role: 'leopard',
        },
        c8: {
          color: 'black',
          role: 'tiger',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
        e7: {
          color: 'black',
          role: 'leopard',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
        e2: {
          color: 'red',
          role: 'elephant',
        },
        d2: {
          color: 'black',
          role: 'lion',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 66,
      progressClock: 3,
      positionCounts: {
        'red|.....PW...lE..............................c...pT...tr...e...d..': 1,
      },
    },
    solution: [
      {
        from: 'e2',
        to: 'd2',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'trap'],
  },
  {
    id: 'jungle-material-017',
    variant: 'jungle',
    title: 'Red Lion wins material (+75)',
    initial: {
      id: 'jungle-material-017',
      board: {
        c9: {
          color: 'black',
          role: 'cat',
        },
        f3: {
          color: 'red',
          role: 'elephant',
        },
        e7: {
          color: 'black',
          role: 'leopard',
        },
        c3: {
          color: 'red',
          role: 'leopard',
        },
        g4: {
          color: 'red',
          role: 'cat',
        },
        c2: {
          color: 'red',
          role: 'dog',
        },
        f1: {
          color: 'red',
          role: 'wolf',
        },
        g9: {
          color: 'black',
          role: 'rat',
        },
        g3: {
          color: 'red',
          role: 'tiger',
        },
        a7: {
          color: 'black',
          role: 'tiger',
        },
        b4: {
          color: 'red',
          role: 'rat',
        },
        e8: {
          color: 'black',
          role: 'dog',
        },
        f8: {
          color: 'black',
          role: 'lion',
        },
        b9: {
          color: 'black',
          role: 'wolf',
        },
        a6: {
          color: 'red',
          role: 'lion',
        },
        d7: {
          color: 'black',
          role: 'elephant',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 24,
      progressClock: 46,
      positionCounts: {
        'red|.....W...D......P..ET.R....C.......L......t..ep......dl..wc...r': 1,
      },
    },
    solution: [
      {
        from: 'a6',
        to: 'a7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 75,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-018',
    variant: 'jungle',
    title: 'Red Lion wins material (+90)',
    initial: {
      id: 'jungle-material-018',
      board: {
        e7: {
          color: 'black',
          role: 'leopard',
        },
        f1: {
          color: 'red',
          role: 'wolf',
        },
        c9: {
          color: 'black',
          role: 'wolf',
        },
        b3: {
          color: 'red',
          role: 'leopard',
        },
        d7: {
          color: 'black',
          role: 'elephant',
        },
        d2: {
          color: 'red',
          role: 'dog',
        },
        a4: {
          color: 'red',
          role: 'rat',
        },
        g9: {
          color: 'black',
          role: 'rat',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        c7: {
          color: 'black',
          role: 'cat',
        },
        g2: {
          color: 'red',
          role: 'tiger',
        },
        d5: {
          color: 'black',
          role: 'lion',
        },
        d6: {
          color: 'red',
          role: 'lion',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 41,
      progressClock: 10,
      positionCounts: {
        'red|.....W....D.ET.P.....R.........l......L.....cep...........w.d.r': 1,
      },
    },
    solution: [
      {
        from: 'd6',
        to: 'd5',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 90,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-019',
    variant: 'jungle',
    title: 'Black Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-019',
      board: {
        e7: {
          color: 'black',
          role: 'leopard',
        },
        f1: {
          color: 'red',
          role: 'wolf',
        },
        c9: {
          color: 'black',
          role: 'wolf',
        },
        b3: {
          color: 'red',
          role: 'leopard',
        },
        a4: {
          color: 'red',
          role: 'rat',
        },
        g9: {
          color: 'black',
          role: 'rat',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        d3: {
          color: 'red',
          role: 'dog',
        },
        g3: {
          color: 'red',
          role: 'tiger',
        },
        d7: {
          color: 'black',
          role: 'elephant',
        },
        d6: {
          color: 'red',
          role: 'lion',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 44,
      progressClock: 6,
      positionCounts: {
        'black|.....W......E..P.D..TR................L......ep....c......w.d.r': 1,
      },
    },
    solution: [
      {
        from: 'd7',
        to: 'd6',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-020',
    variant: 'jungle',
    title: 'Red Tiger wins material (+50)',
    initial: {
      id: 'jungle-material-020',
      board: {
        c9: {
          color: 'black',
          role: 'wolf',
        },
        a4: {
          color: 'red',
          role: 'rat',
        },
        g9: {
          color: 'black',
          role: 'rat',
        },
        e9: {
          color: 'black',
          role: 'dog',
        },
        d3: {
          color: 'red',
          role: 'dog',
        },
        b2: {
          color: 'red',
          role: 'leopard',
        },
        e2: {
          color: 'red',
          role: 'elephant',
        },
        f7: {
          color: 'black',
          role: 'leopard',
        },
        e1: {
          color: 'red',
          role: 'wolf',
        },
        a8: {
          color: 'black',
          role: 'cat',
        },
        f3: {
          color: 'red',
          role: 'tiger',
        },
        d5: {
          color: 'black',
          role: 'elephant',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 49,
      progressClock: 8,
      positionCounts: {
        'red|....W...P..E.....D.T.R.........e...............p.c........w.d.r': 1,
      },
    },
    solution: [
      {
        from: 'f3',
        to: 'f7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 50,
    },
    themes: ['winning', 'tiger', 'water-leap', 'rank-up'],
  },
  {
    id: 'jungle-material-021',
    variant: 'jungle',
    title: 'Red Tiger wins material (+65)',
    initial: {
      id: 'jungle-material-021',
      board: {
        a4: {
          color: 'red',
          role: 'rat',
        },
        g9: {
          color: 'black',
          role: 'rat',
        },
        b2: {
          color: 'red',
          role: 'leopard',
        },
        e2: {
          color: 'red',
          role: 'elephant',
        },
        e1: {
          color: 'red',
          role: 'wolf',
        },
        d5: {
          color: 'black',
          role: 'elephant',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
        f8: {
          color: 'red',
          role: 'tiger',
        },
        c8: {
          color: 'black',
          role: 'wolf',
        },
        e3: {
          color: 'red',
          role: 'dog',
        },
        f9: {
          color: 'black',
          role: 'dog',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 52,
      progressClock: 5,
      positionCounts: {
        'red|....W...P..E......D..R.........e..........c........w..T......dr': 1,
      },
    },
    solution: [
      {
        from: 'f8',
        to: 'g8',
      },
      {
        from: 'd5',
        to: 'd6',
      },
      {
        from: 'g8',
        to: 'g9',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 65,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-022',
    variant: 'jungle',
    title: 'Red Tiger wins material (+65)',
    initial: {
      id: 'jungle-material-022',
      board: {
        a4: {
          color: 'red',
          role: 'rat',
        },
        g9: {
          color: 'black',
          role: 'rat',
        },
        b2: {
          color: 'red',
          role: 'leopard',
        },
        e2: {
          color: 'red',
          role: 'elephant',
        },
        e1: {
          color: 'red',
          role: 'wolf',
        },
        d5: {
          color: 'black',
          role: 'elephant',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
        e3: {
          color: 'red',
          role: 'dog',
        },
        f9: {
          color: 'red',
          role: 'tiger',
        },
        c9: {
          color: 'black',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 53,
      progressClock: 1,
      positionCounts: {
        'red|....W...P..E......D..R.........e..........c...............w..Tr': 1,
      },
    },
    solution: [
      {
        from: 'f9',
        to: 'g9',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 65,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-023',
    variant: 'jungle',
    title: 'Black Tiger wins material (+75)',
    initial: {
      id: 'jungle-material-023',
      board: {
        e9: {
          color: 'black',
          role: 'lion',
        },
        c1: {
          color: 'red',
          role: 'dog',
        },
        g9: {
          color: 'black',
          role: 'leopard',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
        c4: {
          color: 'red',
          role: 'rat',
        },
        g7: {
          color: 'black',
          role: 'rat',
        },
        a3: {
          color: 'red',
          role: 'lion',
        },
        g2: {
          color: 'red',
          role: 'elephant',
        },
        d6: {
          color: 'black',
          role: 'wolf',
        },
        f2: {
          color: 'red',
          role: 'cat',
        },
        e1: {
          color: 'red',
          role: 'wolf',
        },
        b8: {
          color: 'black',
          role: 'elephant',
        },
        f7: {
          color: 'red',
          role: 'tiger',
        },
        f8: {
          color: 'black',
          role: 'tiger',
        },
        a1: {
          color: 'red',
          role: 'leopard',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 56,
      progressClock: 24,
      positionCounts: {
        'black|P.D.W.......CEL........R..............w...c....Tr.e...t.....l.p': 1,
      },
    },
    solution: [
      {
        from: 'f8',
        to: 'f7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 75,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-024',
    variant: 'jungle',
    title: 'Black Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-024',
      board: {
        c1: {
          color: 'red',
          role: 'dog',
        },
        g9: {
          color: 'black',
          role: 'leopard',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
        g7: {
          color: 'black',
          role: 'rat',
        },
        e1: {
          color: 'red',
          role: 'wolf',
        },
        f7: {
          color: 'black',
          role: 'tiger',
        },
        a1: {
          color: 'red',
          role: 'leopard',
        },
        c3: {
          color: 'red',
          role: 'rat',
        },
        c7: {
          color: 'black',
          role: 'wolf',
        },
        d2: {
          color: 'red',
          role: 'cat',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        b8: {
          color: 'black',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'lion',
        },
        b7: {
          color: 'red',
          role: 'lion',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 62,
      progressClock: 11,
      positionCounts: {
        'black|P.D.W.....C.E...R.........................cLw..tr.e..l........p': 1,
      },
    },
    solution: [
      {
        from: 'b8',
        to: 'b7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-025',
    variant: 'jungle',
    title: 'Red Lion wins material (+40)',
    initial: {
      id: 'jungle-material-025',
      board: {
        c1: {
          color: 'red',
          role: 'dog',
        },
        g9: {
          color: 'black',
          role: 'leopard',
        },
        g7: {
          color: 'black',
          role: 'rat',
        },
        e1: {
          color: 'red',
          role: 'wolf',
        },
        f7: {
          color: 'black',
          role: 'tiger',
        },
        a1: {
          color: 'red',
          role: 'leopard',
        },
        c3: {
          color: 'red',
          role: 'rat',
        },
        c7: {
          color: 'black',
          role: 'wolf',
        },
        d2: {
          color: 'red',
          role: 'cat',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        b8: {
          color: 'black',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'lion',
        },
        b7: {
          color: 'red',
          role: 'lion',
        },
        a6: {
          color: 'black',
          role: 'cat',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 63,
      progressClock: 12,
      positionCounts: {
        'red|P.D.W.....C.E...R..................c.......Lw..tr.e..l........p': 1,
      },
    },
    solution: [
      {
        from: 'b7',
        to: 'c7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 40,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-026',
    variant: 'jungle',
    title: 'Black Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-026',
      board: {
        c1: {
          color: 'red',
          role: 'dog',
        },
        g9: {
          color: 'black',
          role: 'leopard',
        },
        g7: {
          color: 'black',
          role: 'rat',
        },
        e1: {
          color: 'red',
          role: 'wolf',
        },
        f7: {
          color: 'black',
          role: 'tiger',
        },
        a1: {
          color: 'red',
          role: 'leopard',
        },
        c3: {
          color: 'red',
          role: 'rat',
        },
        c7: {
          color: 'red',
          role: 'lion',
        },
        d2: {
          color: 'red',
          role: 'cat',
        },
        e8: {
          color: 'black',
          role: 'lion',
        },
        a6: {
          color: 'black',
          role: 'cat',
        },
        e2: {
          color: 'red',
          role: 'elephant',
        },
        c8: {
          color: 'black',
          role: 'elephant',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 64,
      progressClock: 0,
      positionCounts: {
        'black|P.D.W.....CE....R..................c........L..tr..e.l........p': 1,
      },
    },
    solution: [
      {
        from: 'c8',
        to: 'c7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-027',
    variant: 'jungle',
    title: 'Red Leopard wins material (+40)',
    initial: {
      id: 'jungle-material-027',
      board: {
        g1: {
          color: 'red',
          role: 'tiger',
        },
        b3: {
          color: 'red',
          role: 'dog',
        },
        d8: {
          color: 'black',
          role: 'dog',
        },
        a8: {
          color: 'black',
          role: 'elephant',
        },
        d7: {
          color: 'black',
          role: 'leopard',
        },
        e3: {
          color: 'red',
          role: 'elephant',
        },
        e2: {
          color: 'red',
          role: 'wolf',
        },
        b8: {
          color: 'black',
          role: 'tiger',
        },
        d3: {
          color: 'red',
          role: 'leopard',
        },
        e7: {
          color: 'black',
          role: 'lion',
        },
        f7: {
          color: 'black',
          role: 'rat',
        },
        a3: {
          color: 'red',
          role: 'rat',
        },
        c9: {
          color: 'black',
          role: 'cat',
        },
        c1: {
          color: 'red',
          role: 'lion',
        },
        g3: {
          color: 'red',
          role: 'cat',
        },
        d4: {
          color: 'black',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 26,
      progressClock: 50,
      positionCounts: {
        'red|..L...T....W..RD.PE.C...w....................plr.et.d.....c....': 1,
      },
    },
    solution: [
      {
        from: 'd3',
        to: 'd4',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 40,
    },
    themes: ['winning', 'rank-up'],
  },
  {
    id: 'jungle-material-028',
    variant: 'jungle',
    title: 'Red Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-028',
      board: {
        g3: {
          color: 'red',
          role: 'cat',
        },
        e8: {
          color: 'black',
          role: 'dog',
        },
        d6: {
          color: 'black',
          role: 'leopard',
        },
        e1: {
          color: 'red',
          role: 'tiger',
        },
        d2: {
          color: 'red',
          role: 'leopard',
        },
        c8: {
          color: 'black',
          role: 'tiger',
        },
        c1: {
          color: 'red',
          role: 'lion',
        },
        b2: {
          color: 'red',
          role: 'dog',
        },
        g8: {
          color: 'black',
          role: 'rat',
        },
        f2: {
          color: 'red',
          role: 'wolf',
        },
        a5: {
          color: 'black',
          role: 'elephant',
        },
        d3: {
          color: 'red',
          role: 'elephant',
        },
        b9: {
          color: 'black',
          role: 'cat',
        },
        b3: {
          color: 'red',
          role: 'rat',
        },
        e3: {
          color: 'black',
          role: 'lion',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 41,
      progressClock: 23,
      positionCounts: {
        'red|..L.T...D.P.W..R.El.C.......e.........p............t.d.r.c.....': 1,
      },
    },
    solution: [
      {
        from: 'd3',
        to: 'e3',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-029',
    variant: 'jungle',
    title: 'Black Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-029',
      board: {
        e8: {
          color: 'black',
          role: 'dog',
        },
        d6: {
          color: 'black',
          role: 'leopard',
        },
        d2: {
          color: 'red',
          role: 'leopard',
        },
        e3: {
          color: 'red',
          role: 'elephant',
        },
        e2: {
          color: 'red',
          role: 'tiger',
        },
        d8: {
          color: 'black',
          role: 'tiger',
        },
        e9: {
          color: 'black',
          role: 'rat',
        },
        g4: {
          color: 'red',
          role: 'cat',
        },
        b5: {
          color: 'red',
          role: 'rat',
        },
        b3: {
          color: 'black',
          role: 'elephant',
        },
        f3: {
          color: 'red',
          role: 'wolf',
        },
        c7: {
          color: 'black',
          role: 'cat',
        },
        b2: {
          color: 'red',
          role: 'lion',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 57,
      progressClock: 17,
      positionCounts: {
        'black|........L.PT...e..EW.......C.R........p.....c.......td......r..': 1,
      },
    },
    solution: [
      {
        from: 'b3',
        to: 'b2',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-030',
    variant: 'jungle',
    title: 'Black Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-030',
      board: {
        e8: {
          color: 'black',
          role: 'dog',
        },
        e3: {
          color: 'red',
          role: 'elephant',
        },
        g4: {
          color: 'red',
          role: 'cat',
        },
        f3: {
          color: 'red',
          role: 'wolf',
        },
        c7: {
          color: 'black',
          role: 'cat',
        },
        d5: {
          color: 'black',
          role: 'leopard',
        },
        a3: {
          color: 'black',
          role: 'elephant',
        },
        e1: {
          color: 'red',
          role: 'tiger',
        },
        d8: {
          color: 'black',
          role: 'tiger',
        },
        c5: {
          color: 'red',
          role: 'rat',
        },
        e2: {
          color: 'red',
          role: 'leopard',
        },
        f8: {
          color: 'black',
          role: 'rat',
        },
        a2: {
          color: 'red',
          role: 'lion',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 63,
      progressClock: 29,
      positionCounts: {
        'black|....T..L...P..e...EW.......C..Rp............c.......tdr........': 1,
      },
    },
    solution: [
      {
        from: 'a3',
        to: 'a2',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-031',
    variant: 'jungle',
    title: 'Red Tiger wins material (+65)',
    initial: {
      id: 'jungle-material-031',
      board: {
        g9: {
          color: 'black',
          role: 'lion',
        },
        g3: {
          color: 'black',
          role: 'rat',
        },
        a7: {
          color: 'black',
          role: 'elephant',
        },
        b7: {
          color: 'black',
          role: 'wolf',
        },
        g2: {
          color: 'red',
          role: 'tiger',
        },
        a9: {
          color: 'black',
          role: 'tiger',
        },
        a8: {
          color: 'black',
          role: 'cat',
        },
        f1: {
          color: 'red',
          role: 'wolf',
        },
        e3: {
          color: 'red',
          role: 'leopard',
        },
        f8: {
          color: 'black',
          role: 'dog',
        },
        e1: {
          color: 'red',
          role: 'cat',
        },
        b3: {
          color: 'red',
          role: 'rat',
        },
        f9: {
          color: 'black',
          role: 'leopard',
        },
        c2: {
          color: 'red',
          role: 'dog',
        },
        b1: {
          color: 'red',
          role: 'lion',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 16,
      progressClock: 0,
      positionCounts: {
        'red|.L..CW...D...T.R..P.r.....................ew.....c....d.t....pl': 1,
      },
    },
    solution: [
      {
        from: 'g2',
        to: 'g3',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 65,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-032',
    variant: 'jungle',
    title: 'Black Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-032',
      board: {
        g1: {
          color: 'red',
          role: 'tiger',
        },
        a1: {
          color: 'red',
          role: 'dog',
        },
        g6: {
          color: 'red',
          role: 'leopard',
        },
        d3: {
          color: 'red',
          role: 'rat',
        },
        f8: {
          color: 'black',
          role: 'lion',
        },
        f9: {
          color: 'black',
          role: 'leopard',
        },
        e1: {
          color: 'red',
          role: 'cat',
        },
        e7: {
          color: 'black',
          role: 'wolf',
        },
        c8: {
          color: 'black',
          role: 'tiger',
        },
        g3: {
          color: 'red',
          role: 'wolf',
        },
        c7: {
          color: 'black',
          role: 'elephant',
        },
        b7: {
          color: 'black',
          role: 'cat',
        },
        d7: {
          color: 'red',
          role: 'lion',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 63,
      progressClock: 18,
      positionCounts: {
        'black|D...C.T..........R..W....................P.ceLw....t..l......p.': 1,
      },
    },
    solution: [
      {
        from: 'c7',
        to: 'd7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-033',
    variant: 'jungle',
    title: 'Red Lion wins material (+40)',
    initial: {
      id: 'jungle-material-033',
      board: {
        g1: {
          color: 'red',
          role: 'tiger',
        },
        a1: {
          color: 'red',
          role: 'dog',
        },
        g6: {
          color: 'red',
          role: 'leopard',
        },
        d3: {
          color: 'red',
          role: 'rat',
        },
        f8: {
          color: 'black',
          role: 'lion',
        },
        f9: {
          color: 'black',
          role: 'leopard',
        },
        e1: {
          color: 'red',
          role: 'cat',
        },
        e7: {
          color: 'black',
          role: 'wolf',
        },
        g3: {
          color: 'red',
          role: 'wolf',
        },
        c7: {
          color: 'black',
          role: 'elephant',
        },
        b7: {
          color: 'black',
          role: 'cat',
        },
        d7: {
          color: 'red',
          role: 'lion',
        },
        b8: {
          color: 'black',
          role: 'tiger',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 64,
      progressClock: 19,
      positionCounts: {
        'red|D...C.T..........R..W....................P.ceLw...t...l......p.': 1,
      },
    },
    solution: [
      {
        from: 'd7',
        to: 'e7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 40,
    },
    themes: ['winning', 'lion', 'rank-up'],
  },
  {
    id: 'jungle-material-034',
    variant: 'jungle',
    title: 'Black Wolf wins material (+90)',
    initial: {
      id: 'jungle-material-034',
      board: {
        g1: {
          color: 'red',
          role: 'tiger',
        },
        a1: {
          color: 'red',
          role: 'dog',
        },
        d3: {
          color: 'red',
          role: 'rat',
        },
        f9: {
          color: 'black',
          role: 'leopard',
        },
        e1: {
          color: 'red',
          role: 'cat',
        },
        c7: {
          color: 'black',
          role: 'elephant',
        },
        b7: {
          color: 'black',
          role: 'cat',
        },
        b8: {
          color: 'black',
          role: 'tiger',
        },
        d8: {
          color: 'red',
          role: 'lion',
        },
        f7: {
          color: 'black',
          role: 'lion',
        },
        g5: {
          color: 'red',
          role: 'leopard',
        },
        e8: {
          color: 'black',
          role: 'wolf',
        },
        f3: {
          color: 'red',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 66,
      progressClock: 24,
      positionCounts: {
        'black|D...C.T..........R.W..............P........ce..l..t.Lw.......p.': 1,
      },
    },
    solution: [
      {
        from: 'e8',
        to: 'd8',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 90,
    },
    themes: ['winning', 'trap'],
  },
  {
    id: 'jungle-material-035',
    variant: 'jungle',
    title: 'Black Tiger wins material (+65)',
    initial: {
      id: 'jungle-material-035',
      board: {
        b2: {
          color: 'red',
          role: 'dog',
        },
        g9: {
          color: 'black',
          role: 'lion',
        },
        a4: {
          color: 'red',
          role: 'rat',
        },
        c8: {
          color: 'black',
          role: 'elephant',
        },
        g1: {
          color: 'red',
          role: 'tiger',
        },
        g8: {
          color: 'black',
          role: 'leopard',
        },
        c2: {
          color: 'red',
          role: 'leopard',
        },
        d7: {
          color: 'black',
          role: 'wolf',
        },
        a7: {
          color: 'black',
          role: 'cat',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        f7: {
          color: 'black',
          role: 'dog',
        },
        c3: {
          color: 'red',
          role: 'wolf',
        },
        e7: {
          color: 'black',
          role: 'rat',
        },
        b3: {
          color: 'red',
          role: 'lion',
        },
        a5: {
          color: 'black',
          role: 'tiger',
        },
        g5: {
          color: 'red',
          role: 'cat',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 39,
      progressClock: 77,
      positionCounts: {
        'black|......T.DP..E..LW....R......t.....C.......c..wrd...e...p......l': 1,
      },
    },
    solution: [
      {
        from: 'a5',
        to: 'a4',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 65,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-036',
    variant: 'jungle',
    title: 'Black Elephant wins material (+90)',
    initial: {
      id: 'jungle-material-036',
      board: {
        g9: {
          color: 'black',
          role: 'lion',
        },
        a4: {
          color: 'black',
          role: 'tiger',
        },
        a7: {
          color: 'red',
          role: 'lion',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        f7: {
          color: 'black',
          role: 'dog',
        },
        g5: {
          color: 'red',
          role: 'cat',
        },
        a2: {
          color: 'red',
          role: 'dog',
        },
        g2: {
          color: 'red',
          role: 'tiger',
        },
        d2: {
          color: 'red',
          role: 'leopard',
        },
        g8: {
          color: 'black',
          role: 'leopard',
        },
        c7: {
          color: 'black',
          role: 'wolf',
        },
        c3: {
          color: 'red',
          role: 'wolf',
        },
        e6: {
          color: 'black',
          role: 'rat',
        },
        a8: {
          color: 'black',
          role: 'elephant',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 46,
      progressClock: 0,
      positionCounts: {
        'black|.......D..P.ET..W....t............C....r..L.w..d.e.....p......l': 1,
      },
    },
    solution: [
      {
        from: 'a8',
        to: 'a7',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 90,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-037',
    variant: 'jungle',
    title: 'Black Tiger wins material (+40)',
    initial: {
      id: 'jungle-material-037',
      board: {
        g9: {
          color: 'black',
          role: 'lion',
        },
        f7: {
          color: 'black',
          role: 'dog',
        },
        a2: {
          color: 'black',
          role: 'tiger',
        },
        g2: {
          color: 'red',
          role: 'tiger',
        },
        c7: {
          color: 'black',
          role: 'wolf',
        },
        d3: {
          color: 'red',
          role: 'leopard',
        },
        a8: {
          color: 'black',
          role: 'elephant',
        },
        f8: {
          color: 'black',
          role: 'leopard',
        },
        f2: {
          color: 'red',
          role: 'elephant',
        },
        g5: {
          color: 'red',
          role: 'cat',
        },
        e6: {
          color: 'black',
          role: 'rat',
        },
        b2: {
          color: 'red',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 53,
      progressClock: 3,
      positionCounts: {
        'black|.......tW...ET...P................C....r....w..d.e....p.......l': 1,
      },
    },
    solution: [
      {
        from: 'a2',
        to: 'b2',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 40,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-038',
    variant: 'jungle',
    title: 'Black Tiger wins material (+50)',
    initial: {
      id: 'jungle-material-038',
      board: {
        f7: {
          color: 'black',
          role: 'dog',
        },
        c7: {
          color: 'black',
          role: 'wolf',
        },
        a8: {
          color: 'black',
          role: 'elephant',
        },
        f8: {
          color: 'black',
          role: 'leopard',
        },
        g5: {
          color: 'red',
          role: 'cat',
        },
        e6: {
          color: 'black',
          role: 'rat',
        },
        g8: {
          color: 'black',
          role: 'lion',
        },
        f2: {
          color: 'red',
          role: 'tiger',
        },
        c3: {
          color: 'red',
          role: 'leopard',
        },
        c2: {
          color: 'black',
          role: 'tiger',
        },
        e2: {
          color: 'red',
          role: 'elephant',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 60,
      progressClock: 13,
      positionCounts: {
        'black|.........t.ET...P.................C....r....w..d.e....pl.......': 1,
      },
    },
    solution: [
      {
        from: 'c2',
        to: 'c3',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 50,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-039',
    variant: 'jungle',
    title: 'Red Elephant wins material (+75)',
    initial: {
      id: 'jungle-material-039',
      board: {
        f7: {
          color: 'black',
          role: 'dog',
        },
        f8: {
          color: 'black',
          role: 'leopard',
        },
        e6: {
          color: 'black',
          role: 'rat',
        },
        g8: {
          color: 'black',
          role: 'lion',
        },
        c3: {
          color: 'red',
          role: 'leopard',
        },
        f1: {
          color: 'red',
          role: 'tiger',
        },
        d2: {
          color: 'red',
          role: 'elephant',
        },
        b8: {
          color: 'black',
          role: 'elephant',
        },
        d7: {
          color: 'black',
          role: 'wolf',
        },
        g2: {
          color: 'red',
          role: 'cat',
        },
        c2: {
          color: 'black',
          role: 'tiger',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 66,
      progressClock: 24,
      positionCounts: {
        'red|.....T...tE..C..P......................r.....w.d..e...pl.......': 1,
      },
    },
    solution: [
      {
        from: 'd2',
        to: 'c2',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 75,
    },
    themes: ['winning', 'elephant', 'rank-up'],
  },
  {
    id: 'jungle-material-040',
    variant: 'jungle',
    title: 'Black Rat wins material (+100)',
    initial: {
      id: 'jungle-material-040',
      board: {
        a1: {
          color: 'red',
          role: 'lion',
        },
        g9: {
          color: 'black',
          role: 'lion',
        },
        g1: {
          color: 'red',
          role: 'tiger',
        },
        a9: {
          color: 'black',
          role: 'tiger',
        },
        g8: {
          color: 'black',
          role: 'dog',
        },
        a3: {
          color: 'red',
          role: 'rat',
        },
        g4: {
          color: 'red',
          role: 'elephant',
        },
        f7: {
          color: 'black',
          role: 'leopard',
        },
        c8: {
          color: 'black',
          role: 'cat',
        },
        c2: {
          color: 'red',
          role: 'leopard',
        },
        a5: {
          color: 'black',
          role: 'elephant',
        },
        b2: {
          color: 'red',
          role: 'dog',
        },
        b8: {
          color: 'black',
          role: 'wolf',
        },
        e3: {
          color: 'red',
          role: 'cat',
        },
        g5: {
          color: 'black',
          role: 'rat',
        },
        f2: {
          color: 'red',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 12,
      progressClock: 23,
      positionCounts: {
        'black|L.....T.DP..W.R...C........Ee.....r............p..wc...dt.....l': 1,
      },
    },
    solution: [
      {
        from: 'g5',
        to: 'g4',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 100,
    },
    themes: ['winning', 'rat', 'rank-up'],
  },
  {
    id: 'jungle-material-041',
    variant: 'jungle',
    title: 'Red Rat wins material (+100)',
    initial: {
      id: 'jungle-material-041',
      board: {
        g9: {
          color: 'black',
          role: 'lion',
        },
        g1: {
          color: 'red',
          role: 'tiger',
        },
        g8: {
          color: 'black',
          role: 'dog',
        },
        b3: {
          color: 'red',
          role: 'rat',
        },
        a9: {
          color: 'black',
          role: 'tiger',
        },
        a8: {
          color: 'black',
          role: 'wolf',
        },
        c9: {
          color: 'black',
          role: 'cat',
        },
        f2: {
          color: 'red',
          role: 'cat',
        },
        e3: {
          color: 'red',
          role: 'leopard',
        },
        a3: {
          color: 'black',
          role: 'elephant',
        },
        f6: {
          color: 'black',
          role: 'rat',
        },
        d7: {
          color: 'black',
          role: 'leopard',
        },
        d2: {
          color: 'red',
          role: 'wolf',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 32,
      progressClock: 0,
      positionCounts: {
        'red|......T...W.C.eR..P.....................r....p...w.....dt.c...l': 1,
      },
    },
    solution: [
      {
        from: 'b3',
        to: 'a3',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 100,
    },
    themes: ['winning', 'rat', 'rank-up'],
  },
  {
    id: 'jungle-material-042',
    variant: 'jungle',
    title: 'Red Wolf wins material (+65)',
    initial: {
      id: 'jungle-material-042',
      board: {
        a9: {
          color: 'black',
          role: 'tiger',
        },
        g4: {
          color: 'red',
          role: 'wolf',
        },
        f1: {
          color: 'red',
          role: 'tiger',
        },
        a2: {
          color: 'red',
          role: 'leopard',
        },
        e7: {
          color: 'black',
          role: 'leopard',
        },
        g5: {
          color: 'black',
          role: 'rat',
        },
        a5: {
          color: 'red',
          role: 'rat',
        },
        c8: {
          color: 'black',
          role: 'wolf',
        },
        d7: {
          color: 'black',
          role: 'lion',
        },
        b9: {
          color: 'black',
          role: 'cat',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 69,
      progressClock: 1,
      positionCounts: {
        'red|.....T.P...................WR.....r..........lp....w....tc.....': 1,
      },
    },
    solution: [
      {
        from: 'g4',
        to: 'g5',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 65,
    },
    themes: ['winning', 'rank-up'],
  },
  {
    id: 'jungle-material-043',
    variant: 'jungle',
    title: 'Black Wolf wins material (+50)',
    initial: {
      id: 'jungle-material-043',
      board: {
        a1: {
          color: 'red',
          role: 'lion',
        },
        a9: {
          color: 'black',
          role: 'tiger',
        },
        e3: {
          color: 'red',
          role: 'wolf',
        },
        a2: {
          color: 'red',
          role: 'rat',
        },
        g8: {
          color: 'black',
          role: 'lion',
        },
        b7: {
          color: 'black',
          role: 'elephant',
        },
        e1: {
          color: 'red',
          role: 'cat',
        },
        f3: {
          color: 'red',
          role: 'elephant',
        },
        d2: {
          color: 'red',
          role: 'dog',
        },
        g7: {
          color: 'black',
          role: 'leopard',
        },
        e6: {
          color: 'black',
          role: 'rat',
        },
        d7: {
          color: 'black',
          role: 'wolf',
        },
        g1: {
          color: 'red',
          role: 'tiger',
        },
        b9: {
          color: 'black',
          role: 'cat',
        },
        d8: {
          color: 'red',
          role: 'leopard',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 18,
      progressClock: 6,
      positionCounts: {
        'black|L...C.TR..D.......WE...................r...e.w..p...P..ltc.....': 1,
      },
    },
    solution: [
      {
        from: 'd7',
        to: 'd8',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 50,
    },
    themes: ['winning', 'trap'],
  },
  {
    id: 'jungle-material-044',
    variant: 'jungle',
    title: 'Red Tiger wins material (+50)',
    initial: {
      id: 'jungle-material-044',
      board: {
        e1: {
          color: 'red',
          role: 'cat',
        },
        c3: {
          color: 'red',
          role: 'rat',
        },
        c5: {
          color: 'black',
          role: 'rat',
        },
        c9: {
          color: 'black',
          role: 'cat',
        },
        f3: {
          color: 'red',
          role: 'tiger',
        },
        b7: {
          color: 'black',
          role: 'elephant',
        },
        f1: {
          color: 'red',
          role: 'elephant',
        },
        g8: {
          color: 'black',
          role: 'lion',
        },
        b1: {
          color: 'red',
          role: 'lion',
        },
        c8: {
          color: 'black',
          role: 'tiger',
        },
        f2: {
          color: 'red',
          role: 'wolf',
        },
        d4: {
          color: 'black',
          role: 'wolf',
        },
        g1: {
          color: 'red',
          role: 'dog',
        },
        g3: {
          color: 'black',
          role: 'leopard',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 66,
      progressClock: 94,
      positionCounts: {
        'red|.L..CED.....W...R..Tp...w.....r............e.......t...l..c....': 1,
      },
    },
    solution: [
      {
        from: 'f3',
        to: 'g3',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'red',
      centipawns: 50,
    },
    themes: ['winning', 'tiger', 'rank-up'],
  },
  {
    id: 'jungle-material-045',
    variant: 'jungle',
    title: 'Black Wolf wins material (+65)',
    initial: {
      id: 'jungle-material-045',
      board: {
        e1: {
          color: 'red',
          role: 'cat',
        },
        c5: {
          color: 'black',
          role: 'rat',
        },
        c9: {
          color: 'black',
          role: 'cat',
        },
        b7: {
          color: 'black',
          role: 'elephant',
        },
        f1: {
          color: 'red',
          role: 'elephant',
        },
        g8: {
          color: 'black',
          role: 'lion',
        },
        b1: {
          color: 'red',
          role: 'lion',
        },
        c8: {
          color: 'black',
          role: 'tiger',
        },
        f2: {
          color: 'red',
          role: 'wolf',
        },
        g1: {
          color: 'red',
          role: 'dog',
        },
        f3: {
          color: 'red',
          role: 'tiger',
        },
        d3: {
          color: 'black',
          role: 'wolf',
        },
        c3: {
          color: 'red',
          role: 'rat',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 69,
      progressClock: 4,
      positionCounts: {
        'black|.L..CED.....W...Rw.T..........r............e.......t...l..c....': 1,
      },
    },
    solution: [
      {
        from: 'd3',
        to: 'c3',
      },
    ],
    goal: {
      type: 'winning-advantage',
      winner: 'black',
      centipawns: 65,
    },
    themes: ['winning', 'rank-up'],
  },
];
