// Generated by the standard-xiangqi puzzle miner
// (scripts/variant-lab/xiangqi-puzzle-miner.ts, `--emit-module`). Do not
// hand-edit; re-run the miner and let it overwrite this file.
//
// Lichess-style puzzles mined from REAL historical games (not engine
// self-play): a MultiPV Pikafish scan finds moments where the game move lost
// decisively, a deeper verify pass confirms the refutation is winning AND
// unique, and the whole solution line is kernel-replayed for legality. Each
// puzzle links back to its game via sourceGame:{gameId, ply}: gameId is the
// historical_xiangqi_games row id (db mode) or the input file name (dir mode),
// and replaying that game's first `ply` moves reproduces `initial`.
//
// The local structural type mirrors `XiangqiPuzzle` in puzzles-xiangqi.ts so
// the array is assignable when spread there, while keeping this file free of a
// circular import.

import type { XIANGQI_SPEC_ID } from './game-specs.js';
import type { XiangqiColor, XiangqiGameState, XiangqiMove } from './variants-xiangqi.js';

type MinedXiangqiPuzzleTheme =
  | 'checkmate'
  | 'matein1'
  | 'matein2'
  | 'matein3'
  | 'winning'
  | 'winning-material'
  | 'crushing'
  | 'endgame'
  | 'middlegame';

type MinedXiangqiPuzzle = {
  id: string;
  variant: typeof XIANGQI_SPEC_ID;
  title: string;
  initial: XiangqiGameState;
  solution: XiangqiMove[];
  goal:
    | { type: 'checkmate'; winner?: XiangqiColor }
    | { type: 'winning-advantage'; winner?: XiangqiColor; centipawns?: number };
  themes: MinedXiangqiPuzzleTheme[];
  sourceGame?: { gameId: string; ply: number };
};

export const MINED_XIANGQI_PUZZLES: readonly MinedXiangqiPuzzle[] = [];
