// Generated by the Drop Mini Xiangqi mining pass.
// Demo filter: later positions, exact solution-label diversity, and drop moves preferred.

import { DROP_MINI_XIANGQI_SPEC_ID } from './game-specs.js';
import type {
  DropMiniXiangqiGameState,
  DropMiniXiangqiMove,
} from './variants-drop-mini-xiangqi.js';
import type { MiniXiangqiColor } from './variants-mini-xiangqi.js';

type MinedDropMiniXiangqiPuzzleTheme =
  | 'back-rank'
  | 'checkmate'
  | 'chariot'
  | 'drop'
  | 'palace-net';

type MinedDropMiniXiangqiPuzzle = {
  id: string;
  variant: typeof DROP_MINI_XIANGQI_SPEC_ID;
  title: string;
  initial: DropMiniXiangqiGameState;
  solution: DropMiniXiangqiMove[];
  goal: { type: 'checkmate'; winner?: MiniXiangqiColor };
  themes: MinedDropMiniXiangqiPuzzleTheme[];
};

export const MINED_DROP_MINI_XIANGQI_PUZZLES: readonly MinedDropMiniXiangqiPuzzle[] = [
  {
    id: 'drop-mini-xiangqi-mined-001',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 1',
    initial: {
      id: 'drop-mini-xiangqi-mined-001',
      board: {
        e7: {
          color: 'black',
          role: 'horse',
        },
        f7: {
          color: 'black',
          role: 'chariot',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        g5: {
          color: 'red',
          role: 'soldier',
        },
        f6: {
          color: 'black',
          role: 'soldier',
        },
        c5: {
          color: 'black',
          role: 'soldier',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        a4: {
          color: 'black',
          role: 'chariot',
        },
        g4: {
          color: 'black',
          role: 'cannon',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        c4: {
          color: 'black',
          role: 'cannon',
        },
        b4: {
          color: 'black',
          role: 'soldier',
        },
        d5: {
          color: 'red',
          role: 'soldier',
        },
        d3: {
          color: 'red',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'chariot',
        },
        b1: {
          color: 'black',
          role: 'cannon',
        },
        d2: {
          color: 'red',
          role: 'general',
        },
        e4: {
          color: 'black',
          role: 'cannon',
        },
        b3: {
          color: 'red',
          role: 'horse',
        },
        c6: {
          color: 'black',
          role: 'general',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 31,
      progressClock: 1,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          soldier: 1,
        },
        black: {
          chariot: 1,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a2rs,a4br,b1bn,b2rr,b3rh,b4bs,c4bn,c5bs,c6bg,c7bh,d2rg,d3rs,d5rs,e1rh,e2rs,e4bn,e6bs,e7bh,f6bs,f7br,g4bn,g5rs|h:r:h0c0c0s1|b:h0c0c1s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'soldier',
        to: 'b6',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-002',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 2',
    initial: {
      id: 'drop-mini-xiangqi-mined-002',
      board: {
        a1: {
          color: 'red',
          role: 'chariot',
        },
        b1: {
          color: 'red',
          role: 'cannon',
        },
        c7: {
          color: 'black',
          role: 'general',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c6: {
          color: 'black',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        g5: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'chariot',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        c3: {
          color: 'red',
          role: 'soldier',
        },
        f3: {
          color: 'red',
          role: 'soldier',
        },
        b7: {
          color: 'black',
          role: 'horse',
        },
        f5: {
          color: 'black',
          role: 'horse',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        c1: {
          color: 'red',
          role: 'chariot',
        },
        d2: {
          color: 'black',
          role: 'cannon',
        },
        d3: {
          color: 'red',
          role: 'chariot',
        },
        b4: {
          color: 'red',
          role: 'soldier',
        },
        d4: {
          color: 'black',
          role: 'cannon',
        },
        g4: {
          color: 'red',
          role: 'horse',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 20,
      progressClock: 0,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {},
        black: {
          cannon: 1,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|black|a1rr,a2rs,a6bs,b1rn,b4rs,b7bh,c1rr,c3rs,c6bs,c7bg,d1rg,d2bn,d3rr,d4bn,e1rh,e6bs,f3rs,f5bh,g2rr,g3rs,g4rh,g5bs,g6bs|h:r:h0c0c0s0|b:h0c1c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'cannon',
        to: 'f1',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-003',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 3',
    initial: {
      id: 'drop-mini-xiangqi-mined-003',
      board: {
        c7: {
          color: 'black',
          role: 'horse',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        c6: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        g5: {
          color: 'black',
          role: 'soldier',
        },
        d3: {
          color: 'red',
          role: 'horse',
        },
        c4: {
          color: 'red',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'chariot',
        },
        c2: {
          color: 'red',
          role: 'general',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        f1: {
          color: 'red',
          role: 'cannon',
        },
        f3: {
          color: 'red',
          role: 'cannon',
        },
        e7: {
          color: 'black',
          role: 'general',
        },
        e4: {
          color: 'red',
          role: 'soldier',
        },
        b5: {
          color: 'black',
          role: 'soldier',
        },
        b3: {
          color: 'red',
          role: 'chariot',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        d4: {
          color: 'red',
          role: 'cannon',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        b4: {
          color: 'black',
          role: 'horse',
        },
        a3: {
          color: 'black',
          role: 'chariot',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 20,
      progressClock: 1,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          cannon: 1,
        },
        black: {},
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a2rs,a3br,b3rr,b4bh,b5bs,c2rg,c4rs,c6bs,c7bh,d2rs,d3rh,d4rn,e1rh,e2rs,e4rs,e6bs,e7bg,f1rn,f3rn,g1rr,g2rs,g5bs,g6br|h:r:h0c1c0s0|b:h0c0c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'cannon',
        to: 'b7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-004',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 4',
    initial: {
      id: 'drop-mini-xiangqi-mined-004',
      board: {
        a1: {
          color: 'red',
          role: 'chariot',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        f7: {
          color: 'black',
          role: 'cannon',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'soldier',
        },
        c4: {
          color: 'red',
          role: 'soldier',
        },
        b5: {
          color: 'black',
          role: 'soldier',
        },
        d3: {
          color: 'red',
          role: 'cannon',
        },
        b6: {
          color: 'black',
          role: 'soldier',
        },
        f5: {
          color: 'red',
          role: 'horse',
        },
        a7: {
          color: 'black',
          role: 'chariot',
        },
        g6: {
          color: 'black',
          role: 'chariot',
        },
        d4: {
          color: 'red',
          role: 'horse',
        },
        e5: {
          color: 'black',
          role: 'general',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 19,
      progressClock: 1,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          soldier: 3,
        },
        black: {
          cannon: 2,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a1rr,a2rs,a7br,b5bs,b6bs,c1rh,c2rs,c4rs,d1rg,d3rn,d4rh,e1rh,e2rs,e5bg,f5rh,f7bn,g1rr,g2rs,g6br|h:r:h0c0c0s3|b:h0c2c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'soldier',
        to: 'e4',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-005',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 5',
    initial: {
      id: 'drop-mini-xiangqi-mined-005',
      board: {
        a7: {
          color: 'red',
          role: 'soldier',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        a5: {
          color: 'black',
          role: 'soldier',
        },
        f6: {
          color: 'red',
          role: 'chariot',
        },
        f1: {
          color: 'red',
          role: 'chariot',
        },
        a1: {
          color: 'red',
          role: 'cannon',
        },
        b6: {
          color: 'black',
          role: 'cannon',
        },
        b5: {
          color: 'black',
          role: 'soldier',
        },
        a6: {
          color: 'red',
          role: 'chariot',
        },
        d5: {
          color: 'black',
          role: 'cannon',
        },
        c5: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'chariot',
        },
        f4: {
          color: 'black',
          role: 'horse',
        },
        e3: {
          color: 'red',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'general',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 24,
      progressClock: 1,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {},
        black: {
          cannon: 1,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|black|a1rn,a2rs,a5bs,a6rr,a7rs,b5bs,b6bn,c1rh,c2rs,c5bs,c7bh,d1rg,d5bn,d6bg,e1rh,e2rs,e3rs,e6bs,f1rr,f4bh,f6rr,f7br,g3rs|h:r:h0c0c0s0|b:h0c1c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'cannon',
        to: 'd4',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-006',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 6',
    initial: {
      id: 'drop-mini-xiangqi-mined-006',
      board: {
        a7: {
          color: 'black',
          role: 'chariot',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d7: {
          color: 'black',
          role: 'general',
        },
        e1: {
          color: 'black',
          role: 'cannon',
        },
        e7: {
          color: 'black',
          role: 'horse',
        },
        f1: {
          color: 'red',
          role: 'chariot',
        },
        g7: {
          color: 'black',
          role: 'chariot',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c6: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        e3: {
          color: 'black',
          role: 'chariot',
        },
        c4: {
          color: 'black',
          role: 'horse',
        },
        c2: {
          color: 'red',
          role: 'general',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 16,
      progressClock: 3,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {},
        black: {
          soldier: 2,
          cannon: 3,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|black|a2rs,a6bs,a7br,c1rh,c2rg,c4bh,c6bs,c7bh,d6bs,d7bg,e1bn,e3br,e6bs,e7bh,f1rr,f2rs,g2rs,g6bs,g7br|h:r:h0c0c0s0|b:h0c3c0s2|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'cannon',
        to: 'c5',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-007',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 7',
    initial: {
      id: 'drop-mini-xiangqi-mined-007',
      board: {
        a7: {
          color: 'black',
          role: 'chariot',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        f7: {
          color: 'black',
          role: 'cannon',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        g7: {
          color: 'red',
          role: 'horse',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        c5: {
          color: 'black',
          role: 'soldier',
        },
        d4: {
          color: 'red',
          role: 'cannon',
        },
        e5: {
          color: 'black',
          role: 'soldier',
        },
        b5: {
          color: 'red',
          role: 'chariot',
        },
        f5: {
          color: 'black',
          role: 'cannon',
        },
        e6: {
          color: 'red',
          role: 'chariot',
        },
        d5: {
          color: 'black',
          role: 'general',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 14,
      progressClock: 1,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          soldier: 1,
          cannon: 1,
        },
        black: {},
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a2rs,a6bs,a7br,b5rr,c1rh,c2rs,c5bs,c7bh,d1rg,d2rs,d4rn,d5bg,e1rh,e2rs,e5bs,e6rr,f5bn,f7bn,g1rr,g2rs,g6bs,g7rh|h:r:h0c1c0s1|b:h0c0c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'cannon',
        to: 'd3',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-008',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 8',
    initial: {
      id: 'drop-mini-xiangqi-mined-008',
      board: {
        a7: {
          color: 'black',
          role: 'chariot',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        e7: {
          color: 'black',
          role: 'general',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        d5: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        c6: {
          color: 'black',
          role: 'cannon',
        },
        b3: {
          color: 'black',
          role: 'cannon',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 12,
      progressClock: 0,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          cannon: 2,
          chariot: 1,
          horse: 1,
        },
        black: {
          chariot: 1,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a6bs,a7br,b2rs,b3bn,c1rh,c2rs,c6bn,c7bh,d1rg,d2rs,d5bs,d6bs,e1rh,e2rs,e6bs,e7bg,g1rr,g2rs,g6bs|h:r:h1c2c1s0|b:h0c0c1s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'chariot',
        to: 'f7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'drop', 'chariot'],
  },
  {
    id: 'drop-mini-xiangqi-mined-009',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini mate 9',
    initial: {
      id: 'drop-mini-xiangqi-mined-009',
      board: {
        b7: {
          color: 'black',
          role: 'cannon',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d7: {
          color: 'black',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        e7: {
          color: 'black',
          role: 'horse',
        },
        b4: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        a7: {
          color: 'black',
          role: 'chariot',
        },
        f7: {
          color: 'black',
          role: 'cannon',
        },
        c3: {
          color: 'red',
          role: 'soldier',
        },
        e4: {
          color: 'red',
          role: 'soldier',
        },
        f4: {
          color: 'red',
          role: 'soldier',
        },
        b5: {
          color: 'red',
          role: 'soldier',
        },
        b1: {
          color: 'red',
          role: 'chariot',
        },
        e5: {
          color: 'black',
          role: 'soldier',
        },
        g6: {
          color: 'red',
          role: 'chariot',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        g2: {
          color: 'black',
          role: 'chariot',
        },
        d2: {
          color: 'red',
          role: 'general',
        },
        b3: {
          color: 'red',
          role: 'soldier',
        },
        f5: {
          color: 'black',
          role: 'cannon',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        a2: {
          color: 'black',
          role: 'soldier',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 30,
      progressClock: 2,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          cannon: 1,
        },
        black: {},
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a2bs,a7br,b1rr,b3rs,b4bs,b5rs,b7bn,c1rh,c3rs,c7bh,d2rg,d6bs,d7bg,e1rh,e2rs,e4rs,e5bs,e7bh,f4rs,f5bn,f7bn,g2br,g6rr|h:r:h0c1c0s0|b:h0c0c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        from: 'g6',
        to: 'd6',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'chariot'],
  },
  {
    id: 'drop-mini-xiangqi-mined-010',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini mate 10',
    initial: {
      id: 'drop-mini-xiangqi-mined-010',
      board: {
        c1: {
          color: 'red',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        g2: {
          color: 'black',
          role: 'cannon',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        f6: {
          color: 'black',
          role: 'soldier',
        },
        c5: {
          color: 'black',
          role: 'soldier',
        },
        c3: {
          color: 'black',
          role: 'chariot',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        c7: {
          color: 'black',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'chariot',
        },
        e5: {
          color: 'red',
          role: 'horse',
        },
        e4: {
          color: 'red',
          role: 'cannon',
        },
        a4: {
          color: 'red',
          role: 'horse',
        },
        g4: {
          color: 'red',
          role: 'cannon',
        },
        c6: {
          color: 'black',
          role: 'horse',
        },
        d4: {
          color: 'black',
          role: 'soldier',
        },
        e3: {
          color: 'red',
          role: 'soldier',
        },
        d3: {
          color: 'black',
          role: 'cannon',
        },
        b2: {
          color: 'red',
          role: 'chariot',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 30,
      progressClock: 0,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {},
        black: {
          soldier: 2,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a2rs,a4rh,b2rr,c1rh,c3br,c5bs,c6bh,c7bg,d1rg,d3bn,d4bs,e1rs,e3rs,e4rn,e5rh,f2rs,f6bs,f7br,g1rr,g2bn,g4rn,g6bs|h:r:h0c0c0s0|b:h0c0c0s2|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        from: 'b2',
        to: 'b7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'chariot'],
  },
  {
    id: 'drop-mini-xiangqi-mined-011',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini mate 11',
    initial: {
      id: 'drop-mini-xiangqi-mined-011',
      board: {
        c1: {
          color: 'red',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        g2: {
          color: 'black',
          role: 'cannon',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        f6: {
          color: 'black',
          role: 'soldier',
        },
        c5: {
          color: 'black',
          role: 'soldier',
        },
        c3: {
          color: 'black',
          role: 'chariot',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        b5: {
          color: 'red',
          role: 'chariot',
        },
        c7: {
          color: 'black',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'chariot',
        },
        e5: {
          color: 'red',
          role: 'horse',
        },
        e4: {
          color: 'red',
          role: 'cannon',
        },
        a4: {
          color: 'red',
          role: 'horse',
        },
        g4: {
          color: 'red',
          role: 'cannon',
        },
        c6: {
          color: 'black',
          role: 'horse',
        },
        d4: {
          color: 'black',
          role: 'soldier',
        },
        e3: {
          color: 'red',
          role: 'soldier',
        },
        d3: {
          color: 'red',
          role: 'soldier',
        },
        d5: {
          color: 'black',
          role: 'cannon',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 29,
      progressClock: 2,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {},
        black: {
          soldier: 1,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a2rs,a4rh,b5rr,c1rh,c3br,c5bs,c6bh,c7bg,d1rg,d3rs,d4bs,d5bn,e1rs,e3rs,e4rn,e5rh,f2rs,f6bs,f7br,g1rr,g2bn,g4rn,g6bs|h:r:h0c0c0s0|b:h0c0c0s1|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        from: 'b5',
        to: 'b7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'chariot'],
  },
  {
    id: 'drop-mini-xiangqi-mined-012',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini mate 12',
    initial: {
      id: 'drop-mini-xiangqi-mined-012',
      board: {
        a1: {
          color: 'red',
          role: 'chariot',
        },
        b1: {
          color: 'red',
          role: 'cannon',
        },
        c7: {
          color: 'black',
          role: 'general',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c6: {
          color: 'black',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        g5: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'chariot',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        c3: {
          color: 'red',
          role: 'soldier',
        },
        f5: {
          color: 'black',
          role: 'horse',
        },
        c1: {
          color: 'red',
          role: 'chariot',
        },
        e5: {
          color: 'black',
          role: 'soldier',
        },
        d5: {
          color: 'red',
          role: 'chariot',
        },
        a5: {
          color: 'red',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'cannon',
        },
        f4: {
          color: 'red',
          role: 'soldier',
        },
        e2: {
          color: 'black',
          role: 'cannon',
        },
        f1: {
          color: 'red',
          role: 'horse',
        },
        b3: {
          color: 'black',
          role: 'horse',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 27,
      progressClock: 0,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          cannon: 1,
        },
        black: {},
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a1rr,a2rs,a5rs,a6bs,b1rn,b3bh,c1rr,c3rs,c6bs,c7bg,d1rg,d5rr,e1rh,e2bn,e5bs,f1rh,f4rs,f5bh,f7bn,g2rr,g3rs,g5bs,g6bs|h:r:h0c1c0s0|b:h0c0c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        from: 'd5',
        to: 'd7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'chariot'],
  },
  {
    id: 'drop-mini-xiangqi-mined-013',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini mate 13',
    initial: {
      id: 'drop-mini-xiangqi-mined-013',
      board: {
        c1: {
          color: 'red',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        d7: {
          color: 'black',
          role: 'general',
        },
        e7: {
          color: 'black',
          role: 'horse',
        },
        f7: {
          color: 'black',
          role: 'chariot',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        g5: {
          color: 'red',
          role: 'soldier',
        },
        f6: {
          color: 'black',
          role: 'soldier',
        },
        g7: {
          color: 'black',
          role: 'cannon',
        },
        c5: {
          color: 'black',
          role: 'soldier',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        a4: {
          color: 'black',
          role: 'chariot',
        },
        f4: {
          color: 'black',
          role: 'cannon',
        },
        g4: {
          color: 'red',
          role: 'chariot',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        c4: {
          color: 'red',
          role: 'cannon',
        },
        e5: {
          color: 'black',
          role: 'cannon',
        },
        b1: {
          color: 'red',
          role: 'chariot',
        },
        b4: {
          color: 'black',
          role: 'soldier',
        },
        d4: {
          color: 'red',
          role: 'soldier',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 24,
      progressClock: 19,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {},
        black: {},
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|black|a2rs,a4br,b1rr,b4bs,c1rh,c4rn,c5bs,c7bh,d1rg,d2rs,d4rs,d6bs,d7bg,e1rh,e2rs,e5bn,e6bs,e7bh,f4bn,f6bs,f7br,g4rr,g5rs,g7bn|h:r:h0c0c0s0|b:h0c0c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        from: 'f4',
        to: 'f1',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate'],
  },
  {
    id: 'drop-mini-xiangqi-mined-014',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 14',
    initial: {
      id: 'drop-mini-xiangqi-mined-014',
      board: {
        c1: {
          color: 'black',
          role: 'chariot',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d7: {
          color: 'black',
          role: 'general',
        },
        e7: {
          color: 'black',
          role: 'horse',
        },
        g7: {
          color: 'black',
          role: 'chariot',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c6: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        f2: {
          color: 'red',
          role: 'cannon',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        d3: {
          color: 'red',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'general',
        },
        f3: {
          color: 'black',
          role: 'cannon',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'horse',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 10,
      progressClock: 1,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {},
        black: {
          chariot: 2,
          cannon: 2,
          horse: 1,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|black|a2rs,a6bs,b2rs,c1br,c2rh,c6bs,c7bh,d2rg,d3rs,d6bs,d7bg,e2rs,e6bs,e7bh,f2rn,f3bn,g3rs,g6bs,g7br|h:r:h0c0c0s0|b:h1c2c2s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'horse',
        to: 'f1',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-015',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 15',
    initial: {
      id: 'drop-mini-xiangqi-mined-015',
      board: {
        a1: {
          color: 'red',
          role: 'chariot',
        },
        a7: {
          color: 'red',
          role: 'horse',
        },
        b7: {
          color: 'black',
          role: 'cannon',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        e7: {
          color: 'black',
          role: 'horse',
        },
        f7: {
          color: 'red',
          role: 'chariot',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        g7: {
          color: 'black',
          role: 'chariot',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        b6: {
          color: 'black',
          role: 'soldier',
        },
        c4: {
          color: 'red',
          role: 'cannon',
        },
        b5: {
          color: 'black',
          role: 'soldier',
        },
        c6: {
          color: 'black',
          role: 'general',
        },
        b4: {
          color: 'black',
          role: 'cannon',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 10,
      progressClock: 0,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          cannon: 1,
        },
        black: {},
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a1rr,a2rs,a7rh,b4bn,b5bs,b6bs,b7bn,c1rh,c2rs,c4rn,c6bg,d1rg,d2rs,d6bs,e1rh,e2rs,e6bs,e7bh,f7rr,g1rr,g2rs,g6bs,g7br|h:r:h0c1c0s0|b:h0c0c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'cannon',
        to: 'c3',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-016',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 16',
    initial: {
      id: 'drop-mini-xiangqi-mined-016',
      board: {
        a7: {
          color: 'black',
          role: 'chariot',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        d7: {
          color: 'black',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        e7: {
          color: 'black',
          role: 'horse',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        f4: {
          color: 'red',
          role: 'chariot',
        },
        d5: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'chariot',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        c6: {
          color: 'black',
          role: 'cannon',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 9,
      progressClock: 0,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          cannon: 2,
        },
        black: {
          cannon: 1,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|black|a6bs,a7br,b2rs,c1rh,c2rs,c6bn,c7bh,d1rg,d2rs,d5bs,d6bs,d7bg,e1rh,e2rs,e6bs,e7bh,f4rr,f7br,g1rr,g2rs,g6bs|h:r:h0c2c0s0|b:h0c1c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'cannon',
        to: 'b1',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-017',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 17',
    initial: {
      id: 'drop-mini-xiangqi-mined-017',
      board: {
        a1: {
          color: 'black',
          role: 'cannon',
        },
        a7: {
          color: 'black',
          role: 'chariot',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d7: {
          color: 'black',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        e7: {
          color: 'black',
          role: 'horse',
        },
        g7: {
          color: 'black',
          role: 'chariot',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        c6: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        d3: {
          color: 'red',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'general',
        },
        f5: {
          color: 'black',
          role: 'chariot',
        },
        b3: {
          color: 'red',
          role: 'cannon',
        },
        a4: {
          color: 'red',
          role: 'cannon',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 9,
      progressClock: 1,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {},
        black: {
          horse: 1,
          cannon: 1,
          chariot: 1,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|black|a1bn,a2rs,a4rn,a6bs,a7br,b3rn,c2rs,c6bs,c7bh,d2rg,d3rs,d6bs,d7bg,e1rh,e2rs,e6bs,e7bh,f5br,g2rs,g6bs,g7br|h:r:h0c0c0s0|b:h1c1c1s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'horse',
        to: 'b1',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-018',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 18',
    initial: {
      id: 'drop-mini-xiangqi-mined-018',
      board: {
        a7: {
          color: 'black',
          role: 'chariot',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d7: {
          color: 'black',
          role: 'general',
        },
        e7: {
          color: 'black',
          role: 'horse',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        c6: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        e4: {
          color: 'black',
          role: 'chariot',
        },
        d3: {
          color: 'red',
          role: 'soldier',
        },
        b3: {
          color: 'red',
          role: 'chariot',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'general',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 9,
      progressClock: 0,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          cannon: 2,
        },
        black: {
          cannon: 2,
          chariot: 1,
          horse: 1,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a6bs,a7br,b2rs,b3rr,c1rh,c2rs,c6bs,c7bh,d2rg,d3rs,d6bs,d7bg,e4br,e6bs,e7bh,f2rs,g2rs,g6bs|h:r:h0c2c0s0|b:h1c2c1s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'cannon',
        to: 'f7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-019',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 19',
    initial: {
      id: 'drop-mini-xiangqi-mined-019',
      board: {
        c1: {
          color: 'red',
          role: 'horse',
        },
        c7: {
          color: 'black',
          role: 'general',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        e7: {
          color: 'black',
          role: 'horse',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        g7: {
          color: 'black',
          role: 'chariot',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        c6: {
          color: 'black',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'soldier',
        },
        g5: {
          color: 'black',
          role: 'soldier',
        },
        d5: {
          color: 'black',
          role: 'soldier',
        },
        f4: {
          color: 'red',
          role: 'cannon',
        },
        d6: {
          color: 'black',
          role: 'cannon',
        },
        f6: {
          color: 'black',
          role: 'cannon',
        },
        f3: {
          color: 'black',
          role: 'cannon',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 9,
      progressClock: 0,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          chariot: 1,
          horse: 1,
        },
        black: {
          chariot: 1,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a2rs,a6bs,c1rh,c2rs,c6bs,c7bg,d1rg,d2rs,d5bs,d6bn,e1rh,e2rs,e6bs,e7bh,f3bn,f4rn,f6bn,g1rr,g2rs,g5bs,g7br|h:r:h1c0c1s0|b:h0c0c1s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'chariot',
        to: 'b7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'drop', 'chariot'],
  },
  {
    id: 'drop-mini-xiangqi-mined-020',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 20',
    initial: {
      id: 'drop-mini-xiangqi-mined-020',
      board: {
        a1: {
          color: 'red',
          role: 'chariot',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        d7: {
          color: 'black',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        e7: {
          color: 'black',
          role: 'horse',
        },
        f7: {
          color: 'black',
          role: 'chariot',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        d4: {
          color: 'red',
          role: 'cannon',
        },
        d5: {
          color: 'black',
          role: 'cannon',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        b6: {
          color: 'black',
          role: 'soldier',
        },
        b7: {
          color: 'red',
          role: 'cannon',
        },
        f5: {
          color: 'black',
          role: 'soldier',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 8,
      progressClock: 1,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          cannon: 1,
          horse: 1,
          chariot: 1,
        },
        black: {},
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a1rr,a2rs,a6bs,b6bs,b7rn,c1rh,c2rs,d1rg,d2rs,d4rn,d5bn,d6bs,d7bg,e1rh,e2rs,e6bs,e7bh,f2rs,f5bs,f7br,g1rr|h:r:h1c1c1s0|b:h0c0c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'cannon',
        to: 'a7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'drop'],
  },
  {
    id: 'drop-mini-xiangqi-mined-021',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini mate 21',
    initial: {
      id: 'drop-mini-xiangqi-mined-021',
      board: {
        a7: {
          color: 'red',
          role: 'soldier',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        a5: {
          color: 'black',
          role: 'soldier',
        },
        f6: {
          color: 'red',
          role: 'chariot',
        },
        g6: {
          color: 'black',
          role: 'horse',
        },
        f1: {
          color: 'red',
          role: 'chariot',
        },
        a1: {
          color: 'red',
          role: 'cannon',
        },
        b6: {
          color: 'black',
          role: 'cannon',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        b5: {
          color: 'black',
          role: 'soldier',
        },
        a6: {
          color: 'red',
          role: 'chariot',
        },
        d5: {
          color: 'black',
          role: 'cannon',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        c5: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'chariot',
        },
        f4: {
          color: 'red',
          role: 'cannon',
        },
        c6: {
          color: 'black',
          role: 'general',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 22,
      progressClock: 7,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {},
        black: {},
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a1rn,a5bs,a6rr,a7rs,b2rs,b5bs,b6bn,c1rh,c2rs,c5bs,c6bg,c7bh,d1rg,d5bn,e1rh,e2rs,e6bs,f1rr,f2rs,f4rn,f6rr,f7br,g3rs,g6bh|h:r:h0c0c0s0|b:h0c0c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        from: 'a6',
        to: 'b6',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'chariot'],
  },
  {
    id: 'drop-mini-xiangqi-mined-022',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini drop mate 22',
    initial: {
      id: 'drop-mini-xiangqi-mined-022',
      board: {
        a1: {
          color: 'red',
          role: 'chariot',
        },
        a7: {
          color: 'black',
          role: 'chariot',
        },
        b1: {
          color: 'red',
          role: 'cannon',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d7: {
          color: 'black',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'general',
        },
        e7: {
          color: 'black',
          role: 'horse',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        c6: {
          color: 'black',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        d4: {
          color: 'black',
          role: 'cannon',
        },
        d3: {
          color: 'red',
          role: 'cannon',
        },
        b5: {
          color: 'black',
          role: 'cannon',
        },
        a3: {
          color: 'red',
          role: 'soldier',
        },
        f6: {
          color: 'black',
          role: 'soldier',
        },
        f3: {
          color: 'red',
          role: 'soldier',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 7,
      progressClock: 0,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          chariot: 1,
        },
        black: {
          chariot: 1,
          horse: 1,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|black|a1rr,a3rs,a6bs,a7br,b1rn,b5bn,c1rh,c2rs,c6bs,c7bh,d2rs,d3rn,d4bn,d6bs,d7bg,e1rg,e2rs,e6bs,e7bh,f3rs,f6bs|h:r:h0c0c1s0|b:h1c0c1s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        drop: 'chariot',
        to: 'f1',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'drop', 'chariot'],
  },
  {
    id: 'drop-mini-xiangqi-mined-023',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini mate 23',
    initial: {
      id: 'drop-mini-xiangqi-mined-023',
      board: {
        a1: {
          color: 'red',
          role: 'chariot',
        },
        b1: {
          color: 'red',
          role: 'cannon',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        d7: {
          color: 'black',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        a6: {
          color: 'black',
          role: 'soldier',
        },
        c6: {
          color: 'black',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        b3: {
          color: 'red',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        g5: {
          color: 'black',
          role: 'soldier',
        },
        a5: {
          color: 'black',
          role: 'cannon',
        },
        g2: {
          color: 'red',
          role: 'chariot',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        c3: {
          color: 'red',
          role: 'soldier',
        },
        f3: {
          color: 'red',
          role: 'soldier',
        },
        b7: {
          color: 'black',
          role: 'horse',
        },
        f5: {
          color: 'black',
          role: 'horse',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        c1: {
          color: 'red',
          role: 'chariot',
        },
        d4: {
          color: 'black',
          role: 'cannon',
        },
        g7: {
          color: 'red',
          role: 'cannon',
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 16,
      progressClock: 2,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {
          chariot: 1,
        },
        black: {},
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|black|a1rr,a2rs,a5bn,a6bs,b1rn,b3rs,b7bh,c1rr,c3rs,c6bs,c7bh,d1rg,d4bn,d7bg,e1rh,e6bs,f3rs,f5bh,g2rr,g3rs,g5bs,g6bs,g7rn|h:r:h0c0c1s0|b:h0c0c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        from: 'a5',
        to: 'd5',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate'],
  },
  {
    id: 'drop-mini-xiangqi-mined-024',
    variant: DROP_MINI_XIANGQI_SPEC_ID,
    title: 'Drop Mini mate 24',
    initial: {
      id: 'drop-mini-xiangqi-mined-024',
      board: {
        a1: {
          color: 'red',
          role: 'chariot',
        },
        b7: {
          color: 'black',
          role: 'cannon',
        },
        c1: {
          color: 'red',
          role: 'horse',
        },
        c7: {
          color: 'black',
          role: 'horse',
        },
        d1: {
          color: 'red',
          role: 'general',
        },
        d7: {
          color: 'black',
          role: 'general',
        },
        e1: {
          color: 'red',
          role: 'horse',
        },
        e7: {
          color: 'black',
          role: 'horse',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        f6: {
          color: 'red',
          role: 'cannon',
        },
        b6: {
          color: 'black',
          role: 'soldier',
        },
        b4: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'black',
          role: 'chariot',
        },
        e3: {
          color: 'red',
          role: 'soldier',
        },
        f4: {
          color: 'red',
          role: 'soldier',
        },
        a3: {
          color: 'red',
          role: 'soldier',
        },
        a7: {
          color: 'black',
          role: 'chariot',
        },
        g7: {
          color: 'black',
          role: 'cannon',
        },
        d3: {
          color: 'red',
          role: 'soldier',
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 13,
      progressClock: 0,
      rules: {
        dropRegion: 'not-enemy-palace',
        dropAttack: 'allow-immediate-general-threat',
        reserve: 'immediate',
      },
      hands: {
        red: {},
        black: {
          cannon: 1,
        },
      },
      cooldownHands: {
        red: {},
        black: {},
      },
      positionCounts: {
        'not-enemy-palace/allow-immediate-general-threat/immediate|red|a1rr,a3rs,a7br,b4bs,b6bs,b7bn,c1rh,c2rs,c7bh,d1rg,d2rs,d3rs,d6bs,d7bg,e1rh,e3rs,e6bs,e7bh,f4rs,f6rn,g1rr,g2br,g7bn|h:r:h0c0c0s0|b:h0c1c0s0|c:r:h0c0c0s0|b:h0c0c0s0': 1,
      },
    },
    solution: [
      {
        from: 'f6',
        to: 'f7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate'],
  },
];
