// Generated by the Fortress Xiangqi mate-puzzle miner
// (scripts/variant-lab/fortress-xiangqi-puzzle-miner.ts). Do not hand-edit;
// re-run the miner and paste its `--emit-module` output here.
//
// The local structural type mirrors `FortressXiangqiPuzzle` in
// puzzles-fortress-xiangqi.ts so the array is assignable when spread there,
// while keeping this file free of a circular import.

import type { FORTRESS_XIANGQI_SPEC_ID } from './game-specs.js';
import type {
  FortressXiangqiColor,
  FortressXiangqiGameState,
  FortressXiangqiMove,
} from './variants-fortress-xiangqi.js';

type MinedFortressXiangqiPuzzleTheme =
  | 'back-rank'
  | 'cannon'
  | 'chariot'
  | 'checkmate'
  | 'drop'
  | 'horse'
  | 'palace-net'
  | 'treasure';

type MinedFortressXiangqiPuzzle = {
  id: string;
  variant: typeof FORTRESS_XIANGQI_SPEC_ID;
  title: string;
  initial: FortressXiangqiGameState;
  solution: FortressXiangqiMove[];
  goal: { type: 'checkmate'; winner?: FortressXiangqiColor };
  themes: MinedFortressXiangqiPuzzleTheme[];
};

export const MINED_FORTRESS_XIANGQI_PUZZLES: readonly MinedFortressXiangqiPuzzle[] = [
  {
    id: 'fortress-xiangqi-mined-v2-001',
    variant: 'fortress-xiangqi',
    title: 'Red Cannon drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-001',
      board: {
        a1: {
          color: 'red',
          role: 'treasure',
        },
        b8: {
          color: 'black',
          role: 'horse',
        },
        c1: {
          color: 'red',
          role: 'general',
        },
        d8: {
          color: 'red',
          role: 'cannon',
        },
        f8: {
          color: 'black',
          role: 'general',
        },
        g8: {
          color: 'black',
          role: 'treasure',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'black',
          role: 'chariot',
        },
        b7: {
          color: 'black',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        f5: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        d1: {
          color: 'red',
          role: 'chariot',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        e7: {
          color: 'black',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'advisor',
        },
        d3: {
          color: 'red',
          role: 'elephant',
        },
      },
      hands: {
        red: {
          cannon: 1,
        },
        black: {
          advisor: 1,
          soldier: 3,
          horse: 1,
          elephant: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 23,
      positionCounts: {
        'red|a1rt,a7bs,b2br,b7bs,b8bh,c1rk,d1rr,d3re,d6bs,d8rn,e7bs,f5bs,f7ba,f8bk,g3rs,g6bs,g8bt|h:r:r0h0n1s0t0a0e0|b:r0h1n0s3t0a1e1': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'cannon',
        to: 'c8',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'cannon'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-002',
    variant: 'fortress-xiangqi',
    title: 'Black Soldier drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-002',
      board: {
        a1: {
          color: 'red',
          role: 'treasure',
        },
        b8: {
          color: 'black',
          role: 'horse',
        },
        c1: {
          color: 'red',
          role: 'general',
        },
        d8: {
          color: 'red',
          role: 'cannon',
        },
        f8: {
          color: 'black',
          role: 'general',
        },
        g8: {
          color: 'black',
          role: 'treasure',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'black',
          role: 'chariot',
        },
        b7: {
          color: 'black',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        f5: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        d1: {
          color: 'red',
          role: 'chariot',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        e7: {
          color: 'black',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'advisor',
        },
        d3: {
          color: 'red',
          role: 'elephant',
        },
        c6: {
          color: 'red',
          role: 'cannon',
        },
      },
      hands: {
        red: {},
        black: {
          advisor: 1,
          soldier: 3,
          horse: 1,
          elephant: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 23,
      positionCounts: {
        'black|a1rt,a7bs,b2br,b7bs,b8bh,c1rk,c6rn,d1rr,d3re,d6bs,d8rn,e7bs,f5bs,f7ba,f8bk,g3rs,g6bs,g8bt|h:r:r0h0n0s0t0a0e0|b:r0h1n0s3t0a1e1': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'soldier',
        to: 'c2',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'palace-net', 'drop'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-003',
    variant: 'fortress-xiangqi',
    title: 'Red Cannon mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-003',
      board: {
        a1: {
          color: 'red',
          role: 'treasure',
        },
        b8: {
          color: 'black',
          role: 'horse',
        },
        c1: {
          color: 'red',
          role: 'general',
        },
        d8: {
          color: 'red',
          role: 'cannon',
        },
        f8: {
          color: 'black',
          role: 'general',
        },
        g8: {
          color: 'black',
          role: 'treasure',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'black',
          role: 'chariot',
        },
        b7: {
          color: 'black',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        f5: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        d1: {
          color: 'red',
          role: 'chariot',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        e7: {
          color: 'black',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'advisor',
        },
        d3: {
          color: 'red',
          role: 'elephant',
        },
        c6: {
          color: 'red',
          role: 'cannon',
        },
        a5: {
          color: 'black',
          role: 'soldier',
        },
      },
      hands: {
        red: {},
        black: {
          advisor: 1,
          soldier: 2,
          horse: 1,
          elephant: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 24,
      positionCounts: {
        'red|a1rt,a5bs,a7bs,b2br,b7bs,b8bh,c1rk,c6rn,d1rr,d3re,d6bs,d8rn,e7bs,f5bs,f7ba,f8bk,g3rs,g6bs,g8bt|h:r:r0h0n0s0t0a0e0|b:r0h1n0s2t0a1e1': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        from: 'c6',
        to: 'c8',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'cannon'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-004',
    variant: 'fortress-xiangqi',
    title: 'Black Chariot drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-004',
      board: {
        b8: {
          color: 'red',
          role: 'treasure',
        },
        c1: {
          color: 'red',
          role: 'general',
        },
        g8: {
          color: 'black',
          role: 'general',
        },
        b2: {
          color: 'red',
          role: 'treasure',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        e7: {
          color: 'black',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'advisor',
        },
        d3: {
          color: 'red',
          role: 'elephant',
        },
        a5: {
          color: 'black',
          role: 'soldier',
        },
        g1: {
          color: 'black',
          role: 'horse',
        },
        d2: {
          color: 'black',
          role: 'chariot',
        },
        b4: {
          color: 'black',
          role: 'soldier',
        },
        f4: {
          color: 'black',
          role: 'soldier',
        },
        d7: {
          color: 'black',
          role: 'elephant',
        },
        g5: {
          color: 'red',
          role: 'cannon',
        },
        d4: {
          color: 'black',
          role: 'cannon',
        },
      },
      hands: {
        red: {
          soldier: 4,
          horse: 1,
        },
        black: {
          advisor: 1,
          chariot: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 34,
      positionCounts: {
        'black|a5bs,b2rt,b4bs,b8rt,c1rk,d2br,d3re,d4bn,d6bs,d7be,e7bs,f4bs,f7ba,g1bh,g3rs,g5rn,g8bk|h:r:r0h1n0s4t0a0e0|b:r1h0n0s0t0a1e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'chariot',
        to: 'd1',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'chariot'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-005',
    variant: 'fortress-xiangqi',
    title: 'Black Treasure drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-005',
      board: {
        b8: {
          color: 'red',
          role: 'treasure',
        },
        c1: {
          color: 'red',
          role: 'general',
        },
        g8: {
          color: 'black',
          role: 'general',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        e7: {
          color: 'black',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'advisor',
        },
        d3: {
          color: 'red',
          role: 'elephant',
        },
        a5: {
          color: 'black',
          role: 'soldier',
        },
        g1: {
          color: 'black',
          role: 'chariot',
        },
        b4: {
          color: 'black',
          role: 'soldier',
        },
        f4: {
          color: 'black',
          role: 'soldier',
        },
        d7: {
          color: 'black',
          role: 'elephant',
        },
        d4: {
          color: 'black',
          role: 'cannon',
        },
        c7: {
          color: 'red',
          role: 'horse',
        },
        f8: {
          color: 'black',
          role: 'chariot',
        },
        a3: {
          color: 'red',
          role: 'soldier',
        },
        e1: {
          color: 'red',
          role: 'soldier',
        },
      },
      hands: {
        red: {
          soldier: 1,
          horse: 1,
        },
        black: {
          advisor: 1,
          treasure: 1,
          soldier: 1,
          cannon: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 39,
      positionCounts: {
        'black|a3rs,a5bs,b4bs,b8rt,c1rk,c7rh,d3re,d4bn,d6bs,d7be,e1rs,e7bs,f4bs,f7ba,f8br,g1br,g3rs,g8bk|h:r:r0h1n0s1t0a0e0|b:r0h0n1s1t1a1e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'treasure',
        to: 'b2',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'treasure'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-006',
    variant: 'fortress-xiangqi',
    title: 'Black Treasure drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-006',
      board: {
        g8: {
          color: 'black',
          role: 'general',
        },
        d6: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'black',
          role: 'chariot',
        },
        e7: {
          color: 'black',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'advisor',
        },
        d3: {
          color: 'red',
          role: 'elephant',
        },
        a5: {
          color: 'black',
          role: 'soldier',
        },
        d7: {
          color: 'black',
          role: 'elephant',
        },
        d4: {
          color: 'black',
          role: 'cannon',
        },
        a3: {
          color: 'red',
          role: 'soldier',
        },
        e1: {
          color: 'red',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'general',
        },
        g5: {
          color: 'black',
          role: 'treasure',
        },
        c4: {
          color: 'black',
          role: 'soldier',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        g4: {
          color: 'black',
          role: 'soldier',
        },
        a8: {
          color: 'red',
          role: 'horse',
        },
        a4: {
          color: 'red',
          role: 'horse',
        },
      },
      hands: {
        red: {
          chariot: 1,
        },
        black: {
          advisor: 1,
          soldier: 2,
          cannon: 1,
          treasure: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 45,
      positionCounts: {
        'black|a3rs,a4rh,a5bs,a7bs,a8rh,c2rk,c4bs,d3re,d4bn,d6bs,d7be,e1rs,e7bs,f7ba,g3br,g4bs,g5bt,g8bk|h:r:r1h0n0s0t0a0e0|b:r0h0n1s2t1a1e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'treasure',
        to: 'b1',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'treasure'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-007',
    variant: 'fortress-xiangqi',
    title: 'Red Treasure drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-007',
      board: {
        g8: {
          color: 'black',
          role: 'general',
        },
        e7: {
          color: 'black',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'advisor',
        },
        d7: {
          color: 'black',
          role: 'elephant',
        },
        c2: {
          color: 'red',
          role: 'general',
        },
        g5: {
          color: 'red',
          role: 'soldier',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        a8: {
          color: 'red',
          role: 'horse',
        },
        a4: {
          color: 'red',
          role: 'chariot',
        },
        g2: {
          color: 'black',
          role: 'soldier',
        },
        d5: {
          color: 'black',
          role: 'cannon',
        },
        d8: {
          color: 'black',
          role: 'treasure',
        },
        e2: {
          color: 'red',
          role: 'soldier',
        },
        c4: {
          color: 'black',
          role: 'horse',
        },
        f4: {
          color: 'red',
          role: 'cannon',
        },
        a3: {
          color: 'black',
          role: 'chariot',
        },
      },
      hands: {
        red: {
          treasure: 1,
          soldier: 5,
        },
        black: {
          advisor: 1,
          elephant: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 57,
      positionCounts: {
        'red|a3br,a4rr,a7bs,a8rh,c2rk,c4bh,d5bn,d7be,d8bt,e2rs,e7bs,f4rn,f7ba,g2bs,g5rs,g8bk|h:r:r0h0n0s5t1a0e0|b:r0h0n0s0t0a1e1': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'treasure',
        to: 'f8',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'treasure'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-008',
    variant: 'fortress-xiangqi',
    title: 'Red Cannon mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-008',
      board: {
        a1: {
          color: 'red',
          role: 'treasure',
        },
        a8: {
          color: 'black',
          role: 'chariot',
        },
        b1: {
          color: 'red',
          role: 'general',
        },
        b8: {
          color: 'black',
          role: 'horse',
        },
        c1: {
          color: 'red',
          role: 'advisor',
        },
        d8: {
          color: 'black',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'advisor',
        },
        f1: {
          color: 'red',
          role: 'horse',
        },
        f8: {
          color: 'black',
          role: 'general',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'black',
          role: 'cannon',
        },
        b7: {
          color: 'black',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        d7: {
          color: 'black',
          role: 'soldier',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'chariot',
        },
        g7: {
          color: 'black',
          role: 'treasure',
        },
        f5: {
          color: 'red',
          role: 'soldier',
        },
        d3: {
          color: 'red',
          role: 'cannon',
        },
        b3: {
          color: 'red',
          role: 'elephant',
        },
      },
      hands: {
        red: {},
        black: {
          soldier: 2,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 8,
      positionCounts: {
        'red|a1rt,a2rs,a7bs,a8br,b1rk,b2bn,b3re,b7bs,b8bh,c1ra,d2rs,d3rn,d7bs,d8be,e8ba,f1rh,f2rs,f5rs,f7bs,f8bk,g2rr,g7bt|h:r:r0h0n0s0t0a0e0|b:r0h0n0s2t0a0e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        from: 'd3',
        to: 'd8',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'cannon'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-009',
    variant: 'fortress-xiangqi',
    title: 'Red Cannon drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-009',
      board: {
        a8: {
          color: 'red',
          role: 'cannon',
        },
        f1: {
          color: 'red',
          role: 'chariot',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'general',
        },
        b7: {
          color: 'black',
          role: 'soldier',
        },
        d7: {
          color: 'black',
          role: 'horse',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'soldier',
        },
        g7: {
          color: 'black',
          role: 'soldier',
        },
        f3: {
          color: 'red',
          role: 'elephant',
        },
        f6: {
          color: 'black',
          role: 'elephant',
        },
        d3: {
          color: 'red',
          role: 'soldier',
        },
        e1: {
          color: 'red',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        c6: {
          color: 'red',
          role: 'treasure',
        },
        e6: {
          color: 'black',
          role: 'advisor',
        },
        e4: {
          color: 'black',
          role: 'soldier',
        },
        g8: {
          color: 'black',
          role: 'general',
        },
      },
      hands: {
        red: {
          advisor: 1,
          cannon: 1,
          chariot: 1,
          soldier: 1,
          treasure: 1,
          horse: 1,
        },
        black: {},
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 18,
      positionCounts: {
        'red|a7bs,a8rn,b2rk,b7bs,c6rt,d3rs,d7bh,e1rs,e4bs,e6ba,f1rr,f2rs,f3re,f6be,f7bs,g3rs,g7bs,g8bk|h:r:r1h1n1s1t1a1e0|b:r0h0n0s0t0a0e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'cannon',
        to: 'b8',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'cannon'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-010',
    variant: 'fortress-xiangqi',
    title: 'Red Chariot drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-010',
      board: {
        a8: {
          color: 'red',
          role: 'cannon',
        },
        f1: {
          color: 'red',
          role: 'chariot',
        },
        b7: {
          color: 'black',
          role: 'soldier',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'soldier',
        },
        g7: {
          color: 'black',
          role: 'soldier',
        },
        f3: {
          color: 'red',
          role: 'elephant',
        },
        f6: {
          color: 'black',
          role: 'elephant',
        },
        d3: {
          color: 'black',
          role: 'soldier',
        },
        e1: {
          color: 'red',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        c6: {
          color: 'red',
          role: 'treasure',
        },
        e6: {
          color: 'black',
          role: 'advisor',
        },
        a2: {
          color: 'red',
          role: 'general',
        },
        a3: {
          color: 'red',
          role: 'cannon',
        },
        d2: {
          color: 'black',
          role: 'soldier',
        },
        e7: {
          color: 'red',
          role: 'soldier',
        },
        a5: {
          color: 'black',
          role: 'soldier',
        },
        f8: {
          color: 'black',
          role: 'general',
        },
      },
      hands: {
        red: {
          advisor: 1,
          chariot: 1,
          horse: 2,
        },
        black: {
          treasure: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 24,
      positionCounts: {
        'red|a2rk,a3rn,a5bs,a8rn,b7bs,c6rt,d2bs,d3bs,e1rs,e6ba,e7rs,f1rr,f2rs,f3re,f6be,f7bs,f8bk,g3rs,g7bs|h:r:r1h2n0s0t0a1e0|b:r0h0n0s0t1a0e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'chariot',
        to: 'e8',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'chariot'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-011',
    variant: 'fortress-xiangqi',
    title: 'Red Soldier drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-011',
      board: {
        a8: {
          color: 'red',
          role: 'cannon',
        },
        f1: {
          color: 'red',
          role: 'chariot',
        },
        b7: {
          color: 'red',
          role: 'chariot',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'soldier',
        },
        g7: {
          color: 'black',
          role: 'soldier',
        },
        f3: {
          color: 'red',
          role: 'elephant',
        },
        f6: {
          color: 'black',
          role: 'elephant',
        },
        d3: {
          color: 'black',
          role: 'soldier',
        },
        e1: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        c6: {
          color: 'red',
          role: 'treasure',
        },
        e6: {
          color: 'black',
          role: 'advisor',
        },
        a2: {
          color: 'red',
          role: 'general',
        },
        a3: {
          color: 'red',
          role: 'cannon',
        },
        e7: {
          color: 'red',
          role: 'soldier',
        },
        a5: {
          color: 'black',
          role: 'soldier',
        },
        f8: {
          color: 'black',
          role: 'general',
        },
        d1: {
          color: 'red',
          role: 'horse',
        },
        e3: {
          color: 'red',
          role: 'horse',
        },
        d4: {
          color: 'black',
          role: 'treasure',
        },
      },
      hands: {
        red: {
          advisor: 1,
          soldier: 1,
        },
        black: {
          soldier: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 28,
      positionCounts: {
        'red|a2rk,a3rn,a5bs,a8rn,b7rr,c6rt,d1rh,d3bs,d4bt,e1bs,e3rh,e6ba,e7rs,f1rr,f2rs,f3re,f6be,f7bs,f8bk,g3rs,g7bs|h:r:r0h0n0s1t0a1e0|b:r0h0n0s1t0a0e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'soldier',
        to: 'e8',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'drop'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-012',
    variant: 'fortress-xiangqi',
    title: 'Black Chariot drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-012',
      board: {
        a8: {
          color: 'red',
          role: 'cannon',
        },
        f3: {
          color: 'red',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        a3: {
          color: 'red',
          role: 'cannon',
        },
        a5: {
          color: 'black',
          role: 'soldier',
        },
        d1: {
          color: 'red',
          role: 'horse',
        },
        c3: {
          color: 'black',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        a1: {
          color: 'black',
          role: 'soldier',
        },
        c5: {
          color: 'red',
          role: 'soldier',
        },
        d8: {
          color: 'red',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'general',
        },
        f8: {
          color: 'black',
          role: 'general',
        },
        e7: {
          color: 'red',
          role: 'chariot',
        },
        c8: {
          color: 'black',
          role: 'soldier',
        },
        b6: {
          color: 'red',
          role: 'treasure',
        },
      },
      hands: {
        red: {
          treasure: 1,
          advisor: 2,
          soldier: 1,
          elephant: 2,
          horse: 1,
        },
        black: {
          chariot: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 42,
      positionCounts: {
        'black|a1bs,a3rn,a5bs,a8rn,b2rk,b6rt,c3bs,c5rs,c8bs,d1rh,d8rs,e7rr,f3rs,f8bk,g3rs,g6bs|h:r:r0h1n0s1t1a2e2|b:r1h0n0s0t0a0e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'chariot',
        to: 'c2',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'chariot'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-013',
    variant: 'fortress-xiangqi',
    title: 'Red Treasure drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-013',
      board: {
        f1: {
          color: 'red',
          role: 'horse',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        g8: {
          color: 'black',
          role: 'advisor',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        b7: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'soldier',
        },
        g7: {
          color: 'black',
          role: 'soldier',
        },
        a3: {
          color: 'red',
          role: 'soldier',
        },
        d8: {
          color: 'black',
          role: 'elephant',
        },
        b4: {
          color: 'red',
          role: 'horse',
        },
        f3: {
          color: 'red',
          role: 'elephant',
        },
        c3: {
          color: 'red',
          role: 'advisor',
        },
        d3: {
          color: 'red',
          role: 'soldier',
        },
        f5: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'red',
          role: 'treasure',
        },
        a4: {
          color: 'red',
          role: 'cannon',
        },
        e8: {
          color: 'black',
          role: 'general',
        },
        c2: {
          color: 'red',
          role: 'general',
        },
        g5: {
          color: 'black',
          role: 'cannon',
        },
      },
      hands: {
        red: {
          soldier: 1,
          chariot: 1,
          treasure: 1,
        },
        black: {
          soldier: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 28,
      positionCounts: {
        'red|a3rs,a4rn,a7bs,b2rs,b4rh,b7bs,c2rk,c3ra,d3rs,d6rt,d8be,e8bk,f1rh,f3re,f5bs,g1rr,g2rs,g5bn,g7bs,g8ba|h:r:r1h0n0s1t1a0e0|b:r0h0n0s1t0a0e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'treasure',
        to: 'e7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'treasure'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-014',
    variant: 'fortress-xiangqi',
    title: 'Red Chariot mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-014',
      board: {
        f1: {
          color: 'red',
          role: 'horse',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        g8: {
          color: 'black',
          role: 'advisor',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        b7: {
          color: 'black',
          role: 'soldier',
        },
        g7: {
          color: 'red',
          role: 'chariot',
        },
        a3: {
          color: 'red',
          role: 'soldier',
        },
        b4: {
          color: 'red',
          role: 'horse',
        },
        f3: {
          color: 'red',
          role: 'elephant',
        },
        c3: {
          color: 'red',
          role: 'advisor',
        },
        d3: {
          color: 'red',
          role: 'soldier',
        },
        f5: {
          color: 'black',
          role: 'soldier',
        },
        d6: {
          color: 'red',
          role: 'treasure',
        },
        a4: {
          color: 'red',
          role: 'cannon',
        },
        e8: {
          color: 'black',
          role: 'general',
        },
        c2: {
          color: 'red',
          role: 'general',
        },
        a1: {
          color: 'red',
          role: 'treasure',
        },
        f7: {
          color: 'black',
          role: 'soldier',
        },
        a8: {
          color: 'black',
          role: 'soldier',
        },
        b6: {
          color: 'black',
          role: 'elephant',
        },
      },
      hands: {
        red: {
          soldier: 2,
          cannon: 1,
        },
        black: {},
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 32,
      positionCounts: {
        'red|a1rt,a3rs,a4rn,a7bs,a8bs,b2rs,b4rh,b6be,b7bs,c2rk,c3ra,d3rs,d6rt,e8bk,f1rh,f3re,f5bs,f7bs,g1rr,g7rr,g8ba|h:r:r0h0n1s2t0a0e0|b:r0h0n0s0t0a0e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        from: 'g7',
        to: 'g8',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'chariot'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-015',
    variant: 'fortress-xiangqi',
    title: 'Black Soldier drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-015',
      board: {
        a1: {
          color: 'red',
          role: 'treasure',
        },
        a8: {
          color: 'black',
          role: 'chariot',
        },
        b1: {
          color: 'red',
          role: 'general',
        },
        d8: {
          color: 'black',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'advisor',
        },
        f1: {
          color: 'red',
          role: 'horse',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        g8: {
          color: 'black',
          role: 'treasure',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'advisor',
        },
        b7: {
          color: 'black',
          role: 'soldier',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        d7: {
          color: 'black',
          role: 'horse',
        },
        f7: {
          color: 'black',
          role: 'general',
        },
        g7: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        b8: {
          color: 'black',
          role: 'cannon',
        },
        d1: {
          color: 'red',
          role: 'elephant',
        },
        a3: {
          color: 'red',
          role: 'soldier',
        },
        c2: {
          color: 'black',
          role: 'soldier',
        },
      },
      hands: {
        red: {
          soldier: 2,
          cannon: 1,
        },
        black: {
          soldier: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 9,
      positionCounts: {
        'black|a1rt,a3rs,a7bs,a8br,b1rk,b2ra,b7bs,b8bn,c2bs,d1re,d2rs,d7bh,d8be,e8ba,f1rh,f7bk,g1rr,g3rs,g7bs,g8bt|h:r:r0h0n1s2t0a0e0|b:r0h0n0s1t0a0e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'soldier',
        to: 'c1',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'palace-net', 'drop'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-016',
    variant: 'fortress-xiangqi',
    title: 'Red Chariot mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-016',
      board: {
        a8: {
          color: 'red',
          role: 'horse',
        },
        f1: {
          color: 'red',
          role: 'horse',
        },
        a7: {
          color: 'black',
          role: 'cannon',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        g4: {
          color: 'red',
          role: 'chariot',
        },
        b6: {
          color: 'black',
          role: 'soldier',
        },
        b3: {
          color: 'black',
          role: 'cannon',
        },
        g5: {
          color: 'black',
          role: 'elephant',
        },
        b1: {
          color: 'red',
          role: 'general',
        },
        g8: {
          color: 'red',
          role: 'soldier',
        },
        d8: {
          color: 'red',
          role: 'chariot',
        },
        a4: {
          color: 'red',
          role: 'soldier',
        },
        f6: {
          color: 'black',
          role: 'general',
        },
        g7: {
          color: 'black',
          role: 'elephant',
        },
        c4: {
          color: 'red',
          role: 'treasure',
        },
        b4: {
          color: 'black',
          role: 'treasure',
        },
      },
      hands: {
        red: {
          soldier: 4,
          advisor: 1,
        },
        black: {
          advisor: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 55,
      positionCounts: {
        'red|a4rs,a7bn,a8rh,b1rk,b3bn,b4bt,b6bs,c4rt,d2rs,d8rr,e6bs,f1rh,f6bk,g4rr,g5be,g6bs,g7be,g8rs|h:r:r0h0n0s4t0a1e0|b:r0h0n0s0t0a1e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        from: 'g4',
        to: 'f4',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'chariot'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-017',
    variant: 'fortress-xiangqi',
    title: 'Black Treasure mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-017',
      board: {
        a1: {
          color: 'red',
          role: 'general',
        },
        a8: {
          color: 'black',
          role: 'chariot',
        },
        d1: {
          color: 'black',
          role: 'cannon',
        },
        d8: {
          color: 'black',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'general',
        },
        f1: {
          color: 'red',
          role: 'horse',
        },
        g8: {
          color: 'black',
          role: 'treasure',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        d7: {
          color: 'red',
          role: 'cannon',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        f7: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        d3: {
          color: 'black',
          role: 'soldier',
        },
        b5: {
          color: 'black',
          role: 'soldier',
        },
        c7: {
          color: 'black',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'horse',
        },
        f5: {
          color: 'red',
          role: 'soldier',
        },
        f4: {
          color: 'red',
          role: 'soldier',
        },
        e6: {
          color: 'black',
          role: 'elephant',
        },
        a3: {
          color: 'black',
          role: 'treasure',
        },
      },
      hands: {
        red: {
          advisor: 1,
          chariot: 1,
          soldier: 1,
        },
        black: {
          advisor: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 19,
      positionCounts: {
        'black|a1rk,a3bt,a7bs,a8br,b5bs,c7bs,d1bn,d3bs,d7rn,d8be,e6be,e8bk,f1rh,f2rs,f4rs,f5rs,f7bs,g2rh,g3rs,g8bt|h:r:r1h0n0s1t0a1e0|b:r0h0n0s0t0a1e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        from: 'a3',
        to: 'b2',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'palace-net', 'treasure'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-018',
    variant: 'fortress-xiangqi',
    title: 'Black Cannon drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-018',
      board: {
        a1: {
          color: 'red',
          role: 'treasure',
        },
        a8: {
          color: 'black',
          role: 'chariot',
        },
        b1: {
          color: 'red',
          role: 'general',
        },
        b8: {
          color: 'black',
          role: 'horse',
        },
        c1: {
          color: 'red',
          role: 'advisor',
        },
        d1: {
          color: 'red',
          role: 'elephant',
        },
        d8: {
          color: 'black',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'general',
        },
        f1: {
          color: 'red',
          role: 'horse',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        g8: {
          color: 'black',
          role: 'treasure',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        d7: {
          color: 'black',
          role: 'soldier',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        g2: {
          color: 'red',
          role: 'soldier',
        },
        g7: {
          color: 'black',
          role: 'soldier',
        },
        c2: {
          color: 'red',
          role: 'soldier',
        },
        b6: {
          color: 'black',
          role: 'soldier',
        },
        d4: {
          color: 'red',
          role: 'cannon',
        },
        e7: {
          color: 'black',
          role: 'soldier',
        },
        a3: {
          color: 'red',
          role: 'advisor',
        },
      },
      hands: {
        red: {},
        black: {
          cannon: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'black',
      },
      moveNumber: 5,
      positionCounts: {
        'black|a1rt,a2rs,a3ra,a7bs,a8br,b1rk,b2rs,b6bs,b8bh,c1ra,c2rs,d1re,d4rn,d7bs,d8be,e7bs,e8bk,f1rh,f2rs,g1rr,g2rs,g7bs,g8bt|h:r:r0h0n0s0t0a0e0|b:r0h0n1s0t0a0e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'cannon',
        to: 'b4',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'black',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'cannon'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-019',
    variant: 'fortress-xiangqi',
    title: 'Red Cannon mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-019',
      board: {
        a1: {
          color: 'red',
          role: 'treasure',
        },
        a8: {
          color: 'black',
          role: 'chariot',
        },
        b8: {
          color: 'black',
          role: 'horse',
        },
        c1: {
          color: 'red',
          role: 'general',
        },
        d1: {
          color: 'red',
          role: 'elephant',
        },
        d8: {
          color: 'black',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'general',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        g8: {
          color: 'black',
          role: 'treasure',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        d7: {
          color: 'black',
          role: 'soldier',
        },
        f2: {
          color: 'red',
          role: 'soldier',
        },
        g7: {
          color: 'black',
          role: 'soldier',
        },
        e7: {
          color: 'black',
          role: 'soldier',
        },
        a3: {
          color: 'red',
          role: 'advisor',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        f4: {
          color: 'red',
          role: 'cannon',
        },
        b5: {
          color: 'black',
          role: 'soldier',
        },
        g4: {
          color: 'red',
          role: 'cannon',
        },
        d3: {
          color: 'black',
          role: 'horse',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        f8: {
          color: 'black',
          role: 'advisor',
        },
      },
      hands: {
        red: {},
        black: {},
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 11,
      positionCounts: {
        'red|a1rt,a2rs,a3ra,a7bs,a8br,b2rs,b5bs,b8bh,c1rk,d1re,d2rs,d3bh,d7bs,d8be,e7bs,e8bk,f2rs,f4rn,f8ba,g1rr,g3rs,g4rn,g7bs,g8bt|h:r:r0h0n0s0t0a0e0|b:r0h0n0s0t0a0e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        from: 'g4',
        to: 'g8',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'cannon'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-020',
    variant: 'fortress-xiangqi',
    title: 'Red Cannon mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-020',
      board: {
        a1: {
          color: 'red',
          role: 'treasure',
        },
        a8: {
          color: 'black',
          role: 'chariot',
        },
        b8: {
          color: 'black',
          role: 'horse',
        },
        c1: {
          color: 'red',
          role: 'general',
        },
        d1: {
          color: 'red',
          role: 'elephant',
        },
        d8: {
          color: 'black',
          role: 'elephant',
        },
        e8: {
          color: 'black',
          role: 'general',
        },
        g1: {
          color: 'red',
          role: 'chariot',
        },
        g8: {
          color: 'black',
          role: 'treasure',
        },
        a2: {
          color: 'red',
          role: 'soldier',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        d7: {
          color: 'black',
          role: 'soldier',
        },
        f2: {
          color: 'black',
          role: 'horse',
        },
        g7: {
          color: 'black',
          role: 'soldier',
        },
        e7: {
          color: 'black',
          role: 'soldier',
        },
        a3: {
          color: 'red',
          role: 'advisor',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        b5: {
          color: 'black',
          role: 'soldier',
        },
        g4: {
          color: 'red',
          role: 'cannon',
        },
        d2: {
          color: 'red',
          role: 'soldier',
        },
        f8: {
          color: 'black',
          role: 'advisor',
        },
        c4: {
          color: 'red',
          role: 'cannon',
        },
      },
      hands: {
        red: {},
        black: {
          soldier: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 12,
      positionCounts: {
        'red|a1rt,a2rs,a3ra,a7bs,a8br,b2rs,b5bs,b8bh,c1rk,c4rn,d1re,d2rs,d7bs,d8be,e7bs,e8bk,f2bh,f8ba,g1rr,g3rs,g4rn,g7bs,g8bt|h:r:r0h0n0s0t0a0e0|b:r0h0n0s1t0a0e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        from: 'g4',
        to: 'g8',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'cannon'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-021',
    variant: 'fortress-xiangqi',
    title: 'Red Treasure drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-021',
      board: {
        a1: {
          color: 'red',
          role: 'general',
        },
        a8: {
          color: 'black',
          role: 'chariot',
        },
        b8: {
          color: 'black',
          role: 'horse',
        },
        d8: {
          color: 'black',
          role: 'elephant',
        },
        f1: {
          color: 'red',
          role: 'horse',
        },
        g8: {
          color: 'black',
          role: 'general',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        b7: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        c3: {
          color: 'red',
          role: 'advisor',
        },
        f3: {
          color: 'red',
          role: 'soldier',
        },
        a3: {
          color: 'red',
          role: 'soldier',
        },
        f6: {
          color: 'black',
          role: 'soldier',
        },
        b4: {
          color: 'red',
          role: 'soldier',
        },
        b3: {
          color: 'red',
          role: 'soldier',
        },
        d6: {
          color: 'red',
          role: 'chariot',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        a5: {
          color: 'black',
          role: 'elephant',
        },
        c7: {
          color: 'red',
          role: 'treasure',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
      },
      hands: {
        red: {
          cannon: 2,
          treasure: 1,
        },
        black: {
          advisor: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 24,
      positionCounts: {
        'red|a1rk,a3rs,a5be,a7bs,a8br,b2rs,b3rs,b4rs,b7bs,b8bh,c3ra,c7rt,d6rr,d8be,f1rh,f3rs,f6bs,g3rs,g6bs,g8bk|h:r:r0h0n2s0t1a0e0|b:r0h0n0s0t0a1e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'treasure',
        to: 'f7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'treasure'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-022',
    variant: 'fortress-xiangqi',
    title: 'Red Treasure drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-022',
      board: {
        a1: {
          color: 'red',
          role: 'general',
        },
        a8: {
          color: 'black',
          role: 'chariot',
        },
        b8: {
          color: 'black',
          role: 'horse',
        },
        d8: {
          color: 'black',
          role: 'elephant',
        },
        f1: {
          color: 'red',
          role: 'horse',
        },
        g8: {
          color: 'black',
          role: 'general',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        c3: {
          color: 'red',
          role: 'advisor',
        },
        f3: {
          color: 'red',
          role: 'soldier',
        },
        a3: {
          color: 'red',
          role: 'soldier',
        },
        f6: {
          color: 'black',
          role: 'soldier',
        },
        b4: {
          color: 'red',
          role: 'soldier',
        },
        b3: {
          color: 'red',
          role: 'soldier',
        },
        d6: {
          color: 'red',
          role: 'chariot',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        a5: {
          color: 'black',
          role: 'elephant',
        },
        c7: {
          color: 'black',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        e7: {
          color: 'red',
          role: 'cannon',
        },
      },
      hands: {
        red: {
          cannon: 1,
          treasure: 1,
        },
        black: {
          advisor: 1,
          treasure: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 25,
      positionCounts: {
        'red|a1rk,a3rs,a5be,a7bs,a8br,b2rs,b3rs,b4rs,b8bh,c3ra,c7bs,d6rr,d8be,e7rn,f1rh,f3rs,f6bs,g3rs,g6bs,g8bk|h:r:r0h0n1s0t1a0e0|b:r0h0n0s0t1a1e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'treasure',
        to: 'f7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'treasure'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-023',
    variant: 'fortress-xiangqi',
    title: 'Red Treasure drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-023',
      board: {
        a1: {
          color: 'red',
          role: 'general',
        },
        a8: {
          color: 'black',
          role: 'chariot',
        },
        b8: {
          color: 'black',
          role: 'horse',
        },
        d8: {
          color: 'red',
          role: 'chariot',
        },
        f1: {
          color: 'red',
          role: 'horse',
        },
        g8: {
          color: 'black',
          role: 'general',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        c3: {
          color: 'red',
          role: 'advisor',
        },
        f3: {
          color: 'red',
          role: 'soldier',
        },
        a3: {
          color: 'red',
          role: 'soldier',
        },
        f6: {
          color: 'black',
          role: 'soldier',
        },
        b4: {
          color: 'red',
          role: 'soldier',
        },
        b3: {
          color: 'red',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        a5: {
          color: 'black',
          role: 'elephant',
        },
        c7: {
          color: 'black',
          role: 'soldier',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        e7: {
          color: 'red',
          role: 'cannon',
        },
        f8: {
          color: 'black',
          role: 'treasure',
        },
      },
      hands: {
        red: {
          cannon: 1,
          treasure: 1,
          elephant: 1,
        },
        black: {
          advisor: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 26,
      positionCounts: {
        'red|a1rk,a3rs,a5be,a7bs,a8br,b2rs,b3rs,b4rs,b8bh,c3ra,c7bs,d8rr,e7rn,f1rh,f3rs,f6bs,f8bt,g3rs,g6bs,g8bk|h:r:r0h0n1s0t1a0e1|b:r0h0n0s0t0a1e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'treasure',
        to: 'f7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'treasure'],
  },
  {
    id: 'fortress-xiangqi-mined-v2-024',
    variant: 'fortress-xiangqi',
    title: 'Red Treasure drop mate in 1',
    initial: {
      id: 'fortress-xiangqi-mined-v2-024',
      board: {
        a1: {
          color: 'red',
          role: 'general',
        },
        a8: {
          color: 'black',
          role: 'chariot',
        },
        b8: {
          color: 'black',
          role: 'horse',
        },
        d8: {
          color: 'red',
          role: 'chariot',
        },
        f1: {
          color: 'red',
          role: 'horse',
        },
        g8: {
          color: 'black',
          role: 'general',
        },
        a7: {
          color: 'black',
          role: 'soldier',
        },
        g3: {
          color: 'red',
          role: 'soldier',
        },
        c3: {
          color: 'red',
          role: 'advisor',
        },
        f3: {
          color: 'red',
          role: 'soldier',
        },
        a3: {
          color: 'red',
          role: 'soldier',
        },
        f6: {
          color: 'black',
          role: 'soldier',
        },
        b4: {
          color: 'red',
          role: 'soldier',
        },
        b3: {
          color: 'red',
          role: 'soldier',
        },
        b2: {
          color: 'red',
          role: 'soldier',
        },
        a5: {
          color: 'black',
          role: 'elephant',
        },
        g6: {
          color: 'black',
          role: 'soldier',
        },
        e7: {
          color: 'red',
          role: 'cannon',
        },
        f8: {
          color: 'black',
          role: 'treasure',
        },
        e2: {
          color: 'red',
          role: 'cannon',
        },
        b7: {
          color: 'black',
          role: 'soldier',
        },
      },
      hands: {
        red: {
          treasure: 1,
          elephant: 1,
        },
        black: {
          advisor: 1,
        },
      },
      status: {
        type: 'playing',
        turn: 'red',
      },
      moveNumber: 27,
      positionCounts: {
        'red|a1rk,a3rs,a5be,a7bs,a8br,b2rs,b3rs,b4rs,b7bs,b8bh,c3ra,d8rr,e2rn,e7rn,f1rh,f3rs,f6bs,f8bt,g3rs,g6bs,g8bk|h:r:r0h0n0s0t1a0e1|b:r0h0n0s0t0a1e0': 1,
      },
      moveLog: [],
    },
    solution: [
      {
        drop: 'treasure',
        to: 'f7',
      },
    ],
    goal: {
      type: 'checkmate',
      winner: 'red',
    },
    themes: ['checkmate', 'palace-net', 'drop', 'treasure'],
  },
];
