// GENERATED by shogi4/tools/gen_rules_diagrams.py — do not edit by hand.
// Inline SVG diagrams for the Shogi4 rules article. They reference the
// public-domain Oca tiles copied to apps/web/public/shogi4/pieces/.
// Regenerate (from the shogi4 repo): python3 tools/gen_rules_diagrams.py

export const SHOGI4_START_BOARD = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 274 274" width="100%" style="max-width:480px" role="img" class="shogi4-diagram">
<rect x="22" y="12" width="240" height="240" rx="9" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="82" y1="12" x2="82" y2="252" stroke="#ddcca6" stroke-width="1"/>
<line x1="22" y1="72" x2="262" y2="72" stroke="#ddcca6" stroke-width="1"/>
<line x1="142" y1="12" x2="142" y2="252" stroke="#ddcca6" stroke-width="1"/>
<line x1="22" y1="132" x2="262" y2="132" stroke="#ddcca6" stroke-width="1"/>
<line x1="202" y1="12" x2="202" y2="252" stroke="#ddcca6" stroke-width="1"/>
<line x1="22" y1="192" x2="262" y2="192" stroke="#ddcca6" stroke-width="1"/>
<image href="/shogi4/pieces/crane.png" x="23.2" y="193.2" width="57.6" height="57.6"/>
<image href="/shogi4/pieces/fox.png" x="83.2" y="193.2" width="57.6" height="57.6"/>
<image href="/shogi4/pieces/raccoon.png" x="143.2" y="193.2" width="57.6" height="57.6"/>
<image href="/shogi4/pieces/tapir.png" x="203.2" y="193.2" width="57.6" height="57.6"/>
<image href="/shogi4/pieces/carp.png" x="23.2" y="133.2" width="57.6" height="57.6"/>
<image href="/shogi4/pieces/dark/carp.png" x="203.2" y="73.2" width="57.6" height="57.6" transform="rotate(180 232.0 102.0)"/>
<image href="/shogi4/pieces/dark/tapir.png" x="23.2" y="13.2" width="57.6" height="57.6" transform="rotate(180 52.0 42.0)"/>
<image href="/shogi4/pieces/dark/raccoon.png" x="83.2" y="13.2" width="57.6" height="57.6" transform="rotate(180 112.0 42.0)"/>
<image href="/shogi4/pieces/dark/fox.png" x="143.2" y="13.2" width="57.6" height="57.6" transform="rotate(180 172.0 42.0)"/>
<image href="/shogi4/pieces/pheasant.png" x="203.2" y="13.2" width="57.6" height="57.6" transform="rotate(180 232.0 42.0)"/>
<text x="52.0" y="267" text-anchor="middle" fill="#9a8c6a" font-family="system-ui,sans-serif" font-size="13">a</text>
<text x="112.0" y="267" text-anchor="middle" fill="#9a8c6a" font-family="system-ui,sans-serif" font-size="13">b</text>
<text x="172.0" y="267" text-anchor="middle" fill="#9a8c6a" font-family="system-ui,sans-serif" font-size="13">c</text>
<text x="232.0" y="267" text-anchor="middle" fill="#9a8c6a" font-family="system-ui,sans-serif" font-size="13">d</text>
<text x="13" y="226.0" text-anchor="middle" fill="#9a8c6a" font-family="system-ui,sans-serif" font-size="13">1</text>
<text x="13" y="166.0" text-anchor="middle" fill="#9a8c6a" font-family="system-ui,sans-serif" font-size="13">2</text>
<text x="13" y="106.0" text-anchor="middle" fill="#9a8c6a" font-family="system-ui,sans-serif" font-size="13">3</text>
<text x="13" y="46.0" text-anchor="middle" fill="#9a8c6a" font-family="system-ui,sans-serif" font-size="13">4</text>
</svg>`;

export const SHOGI4_RULES_THUMBNAIL = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 262 262" width="100%" role="img" class="shogi4-diagram">
<rect x="10" y="12" width="240" height="240" rx="9" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="70" y1="12" x2="70" y2="252" stroke="#ddcca6" stroke-width="1"/>
<line x1="10" y1="72" x2="250" y2="72" stroke="#ddcca6" stroke-width="1"/>
<line x1="130" y1="12" x2="130" y2="252" stroke="#ddcca6" stroke-width="1"/>
<line x1="10" y1="132" x2="250" y2="132" stroke="#ddcca6" stroke-width="1"/>
<line x1="190" y1="12" x2="190" y2="252" stroke="#ddcca6" stroke-width="1"/>
<line x1="10" y1="192" x2="250" y2="192" stroke="#ddcca6" stroke-width="1"/>
<image href="/shogi4/pieces/crane.png" x="11.2" y="193.2" width="57.6" height="57.6"/>
<image href="/shogi4/pieces/fox.png" x="71.2" y="193.2" width="57.6" height="57.6"/>
<image href="/shogi4/pieces/raccoon.png" x="131.2" y="193.2" width="57.6" height="57.6"/>
<image href="/shogi4/pieces/tapir.png" x="191.2" y="193.2" width="57.6" height="57.6"/>
<image href="/shogi4/pieces/carp.png" x="11.2" y="133.2" width="57.6" height="57.6"/>
<image href="/shogi4/pieces/dark/carp.png" x="191.2" y="73.2" width="57.6" height="57.6" transform="rotate(180 220.0 102.0)"/>
<image href="/shogi4/pieces/dark/tapir.png" x="11.2" y="13.2" width="57.6" height="57.6" transform="rotate(180 40.0 42.0)"/>
<image href="/shogi4/pieces/dark/raccoon.png" x="71.2" y="13.2" width="57.6" height="57.6" transform="rotate(180 100.0 42.0)"/>
<image href="/shogi4/pieces/dark/fox.png" x="131.2" y="13.2" width="57.6" height="57.6" transform="rotate(180 160.0 42.0)"/>
<image href="/shogi4/pieces/pheasant.png" x="191.2" y="13.2" width="57.6" height="57.6" transform="rotate(180 220.0 42.0)"/>
</svg>`;

export const SHOGI4_PAIR_CARP = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 382 180" width="100%" style="max-width:600px" role="img" class="shogi4-diagram">
<rect x="12" y="12" width="156" height="156" rx="8" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="64" y1="12" x2="64" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="12" y1="64" x2="168" y2="64" stroke="#ddcca6" stroke-width="1"/>
<line x1="116" y1="12" x2="116" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="12" y1="116" x2="168" y2="116" stroke="#ddcca6" stroke-width="1"/>
<circle cx="90.0" cy="38.0" r="6.2" fill="#15705c"/>
<image href="/shogi4/pieces/carp.png" x="66.1" y="66.1" width="47.8" height="47.8"/>
<rect x="214" y="12" width="156" height="156" rx="8" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="266" y1="12" x2="266" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="214" y1="64" x2="370" y2="64" stroke="#ddcca6" stroke-width="1"/>
<line x1="318" y1="12" x2="318" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="214" y1="116" x2="370" y2="116" stroke="#ddcca6" stroke-width="1"/>
<circle cx="292.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="240.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="344.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="240.0" cy="142.0" r="6.2" fill="#15705c"/>
<circle cx="344.0" cy="142.0" r="6.2" fill="#15705c"/>
<image href="/shogi4/pieces/koi.png" x="268.1" y="66.1" width="47.8" height="47.8"/>
<line x1="176.0" y1="90.0" x2="200.0" y2="90.0" stroke="#8a7a55" stroke-width="2.5"/>
<path d="M 198.0 85.0 L 206.0 90.0 L 198.0 95.0 Z" fill="#8a7a55"/>
</svg>`;

export const SHOGI4_PAIR_TAPIR = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 382 180" width="100%" style="max-width:600px" role="img" class="shogi4-diagram">
<rect x="12" y="12" width="156" height="156" rx="8" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="64" y1="12" x2="64" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="12" y1="64" x2="168" y2="64" stroke="#ddcca6" stroke-width="1"/>
<line x1="116" y1="12" x2="116" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="12" y1="116" x2="168" y2="116" stroke="#ddcca6" stroke-width="1"/>
<circle cx="90.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="38.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="142.0" cy="38.0" r="6.2" fill="#15705c"/>
<image href="/shogi4/pieces/tapir.png" x="66.1" y="66.1" width="47.8" height="47.8"/>
<rect x="214" y="12" width="156" height="156" rx="8" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="266" y1="12" x2="266" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="214" y1="64" x2="370" y2="64" stroke="#ddcca6" stroke-width="1"/>
<line x1="318" y1="12" x2="318" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="214" y1="116" x2="370" y2="116" stroke="#ddcca6" stroke-width="1"/>
<circle cx="292.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="240.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="344.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="240.0" cy="142.0" r="6.2" fill="#15705c"/>
<circle cx="344.0" cy="142.0" r="6.2" fill="#15705c"/>
<image href="/shogi4/pieces/baku.png" x="268.1" y="66.1" width="47.8" height="47.8"/>
<line x1="176.0" y1="90.0" x2="200.0" y2="90.0" stroke="#8a7a55" stroke-width="2.5"/>
<path d="M 198.0 85.0 L 206.0 90.0 L 198.0 95.0 Z" fill="#8a7a55"/>
</svg>`;

export const SHOGI4_PAIR_RACCOON = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 382 180" width="100%" style="max-width:600px" role="img" class="shogi4-diagram">
<rect x="12" y="12" width="156" height="156" rx="8" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="64" y1="12" x2="64" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="12" y1="64" x2="168" y2="64" stroke="#ddcca6" stroke-width="1"/>
<line x1="116" y1="12" x2="116" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="12" y1="116" x2="168" y2="116" stroke="#ddcca6" stroke-width="1"/>
<circle cx="38.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="142.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="38.0" cy="142.0" r="6.2" fill="#15705c"/>
<circle cx="142.0" cy="142.0" r="6.2" fill="#15705c"/>
<image href="/shogi4/pieces/raccoon.png" x="66.1" y="66.1" width="47.8" height="47.8"/>
<rect x="214" y="12" width="156" height="156" rx="8" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="266" y1="12" x2="266" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="214" y1="64" x2="370" y2="64" stroke="#ddcca6" stroke-width="1"/>
<line x1="318" y1="12" x2="318" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="214" y1="116" x2="370" y2="116" stroke="#ddcca6" stroke-width="1"/>
<circle cx="292.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="240.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="344.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="240.0" cy="142.0" r="6.2" fill="#15705c"/>
<circle cx="344.0" cy="142.0" r="6.2" fill="#15705c"/>
<image href="/shogi4/pieces/tanuki.png" x="268.1" y="66.1" width="47.8" height="47.8"/>
<line x1="176.0" y1="90.0" x2="200.0" y2="90.0" stroke="#8a7a55" stroke-width="2.5"/>
<path d="M 198.0 85.0 L 206.0 90.0 L 198.0 95.0 Z" fill="#8a7a55"/>
</svg>`;

export const SHOGI4_PAIR_FOX = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 382 180" width="100%" style="max-width:600px" role="img" class="shogi4-diagram">
<rect x="12" y="12" width="156" height="156" rx="8" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="64" y1="12" x2="64" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="12" y1="64" x2="168" y2="64" stroke="#ddcca6" stroke-width="1"/>
<line x1="116" y1="12" x2="116" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="12" y1="116" x2="168" y2="116" stroke="#ddcca6" stroke-width="1"/>
<circle cx="90.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="90.0" cy="142.0" r="6.2" fill="#15705c"/>
<circle cx="38.0" cy="90.0" r="6.2" fill="#15705c"/>
<circle cx="142.0" cy="90.0" r="6.2" fill="#15705c"/>
<image href="/shogi4/pieces/fox.png" x="66.1" y="66.1" width="47.8" height="47.8"/>
<rect x="214" y="12" width="156" height="156" rx="8" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="266" y1="12" x2="266" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="214" y1="64" x2="370" y2="64" stroke="#ddcca6" stroke-width="1"/>
<line x1="318" y1="12" x2="318" y2="168" stroke="#ddcca6" stroke-width="1"/>
<line x1="214" y1="116" x2="370" y2="116" stroke="#ddcca6" stroke-width="1"/>
<circle cx="292.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="240.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="344.0" cy="38.0" r="6.2" fill="#15705c"/>
<circle cx="240.0" cy="90.0" r="6.2" fill="#15705c"/>
<circle cx="344.0" cy="90.0" r="6.2" fill="#15705c"/>
<circle cx="292.0" cy="142.0" r="6.2" fill="#15705c"/>
<image href="/shogi4/pieces/kitsune.png" x="268.1" y="66.1" width="47.8" height="47.8"/>
<line x1="176.0" y1="90.0" x2="200.0" y2="90.0" stroke="#8a7a55" stroke-width="2.5"/>
<path d="M 198.0 85.0 L 206.0 90.0 L 198.0 95.0 Z" fill="#8a7a55"/>
</svg>`;

export const SHOGI4_MOVE_ROYAL = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 192" width="100%" style="max-width:540px" role="img" class="shogi4-diagram">
<rect x="12" y="12" width="168" height="168" rx="8" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="68" y1="12" x2="68" y2="180" stroke="#ddcca6" stroke-width="1"/>
<line x1="12" y1="68" x2="180" y2="68" stroke="#ddcca6" stroke-width="1"/>
<line x1="124" y1="12" x2="124" y2="180" stroke="#ddcca6" stroke-width="1"/>
<line x1="12" y1="124" x2="180" y2="124" stroke="#ddcca6" stroke-width="1"/>
<circle cx="40.0" cy="40.0" r="6.7" fill="#15705c"/>
<circle cx="96.0" cy="40.0" r="6.7" fill="#15705c"/>
<circle cx="152.0" cy="40.0" r="6.7" fill="#15705c"/>
<circle cx="40.0" cy="96.0" r="6.7" fill="#15705c"/>
<circle cx="152.0" cy="96.0" r="6.7" fill="#15705c"/>
<circle cx="40.0" cy="152.0" r="6.7" fill="#15705c"/>
<circle cx="96.0" cy="152.0" r="6.7" fill="#15705c"/>
<circle cx="152.0" cy="152.0" r="6.7" fill="#15705c"/>
<image href="/shogi4/pieces/crane.png" x="70.2" y="70.2" width="51.5" height="51.5"/>
<rect x="204" y="12" width="168" height="168" rx="8" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="260" y1="12" x2="260" y2="180" stroke="#ddcca6" stroke-width="1"/>
<line x1="204" y1="68" x2="372" y2="68" stroke="#ddcca6" stroke-width="1"/>
<line x1="316" y1="12" x2="316" y2="180" stroke="#ddcca6" stroke-width="1"/>
<line x1="204" y1="124" x2="372" y2="124" stroke="#ddcca6" stroke-width="1"/>
<circle cx="232.0" cy="40.0" r="6.7" fill="#15705c"/>
<circle cx="288.0" cy="40.0" r="6.7" fill="#15705c"/>
<circle cx="344.0" cy="40.0" r="6.7" fill="#15705c"/>
<circle cx="232.0" cy="96.0" r="6.7" fill="#15705c"/>
<circle cx="344.0" cy="96.0" r="6.7" fill="#15705c"/>
<circle cx="232.0" cy="152.0" r="6.7" fill="#15705c"/>
<circle cx="288.0" cy="152.0" r="6.7" fill="#15705c"/>
<circle cx="344.0" cy="152.0" r="6.7" fill="#15705c"/>
<image href="/shogi4/pieces/pheasant.png" x="262.2" y="70.2" width="51.5" height="51.5"/>
</svg>`;

export const SHOGI4_JUMP = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 106 204" width="100%" style="max-width:180px" role="img" class="shogi4-diagram">
<defs><marker id="s4arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 Z" fill="#15705c"/></marker></defs>
<rect x="12" y="12" width="60" height="180" rx="8" fill="#f4ead2" stroke="#c9b07f" stroke-width="2"/>
<line x1="12" y1="72" x2="72" y2="72" stroke="#ddcca6" stroke-width="1"/>
<line x1="12" y1="132" x2="72" y2="132" stroke="#ddcca6" stroke-width="1"/>
<circle cx="42.0" cy="42.0" r="18.0" fill="none" stroke="#15705c" stroke-width="2" stroke-dasharray="4 4"/>
<image href="/shogi4/pieces/raccoon.png" x="14.4" y="74.4" width="55.2" height="55.2"/>
<image href="/shogi4/pieces/carp.png" x="14.4" y="134.4" width="55.2" height="55.2"/>
<path d="M 66.0 156.0 Q 96.0 102.0 66.0 48.0" fill="none" stroke="#15705c" stroke-width="2.5" marker-end="url(#s4arrow)"/>
</svg>`;
