import assert from 'node:assert/strict';
import type { IncomingMessage, ServerResponse } from 'node:http';
import test from 'node:test';
import {
  applyCrazyhouseMove,
  type Board,
  type CrazyhouseGameState,
  type CrazyhouseMove,
  createInitialCrazyhouseState,
  DARK_CRAZYHOUSE_SPEC_ID,
  getLegalCrazyhouseMoves,
  isCrazyhouseDrop,
} from '@mistboard/game';
import type { DarkCrazyhouseEvent } from '../dark-crazyhouse-runtime.js';
import type { RecentEveGameRecord } from '../persistence.js';
import {
  type DarkCrazyhousePostgamePersistence,
  darkCrazyhousePostgameForApi,
  tryHandle,
} from './dark-crazyhouse-games.js';
import type { HttpApiContext } from './lib.js';

const ROOM_ID = 'dczh_postgame';
const MOVE_COUNT = 4;

function moveKey(move: CrazyhouseMove): string {
  return isCrazyhouseDrop(move)
    ? `*${move.drop}${move.to}`
    : `${move.from}${move.to}${move.promotion ?? ''}`;
}

// A deterministic scripted line: each side plays its first legal move (stable
// sort), then Black resigns -> White wins. Moves are generated by replaying.
function finishedGameEvents(): DarkCrazyhouseEvent[] {
  const events: DarkCrazyhouseEvent[] = [
    { type: 'room-created', at: 1, roomId: ROOM_ID, gameSpecId: DARK_CRAZYHOUSE_SPEC_ID },
    { type: 'seat-assigned', at: 2, roomId: ROOM_ID, clientId: 'w', seat: 'white' },
    { type: 'seat-assigned', at: 3, roomId: ROOM_ID, clientId: 'b', seat: 'black' },
  ];
  let state: CrazyhouseGameState = createInitialCrazyhouseState(ROOM_ID);
  let at = 4;
  for (let i = 0; i < MOVE_COUNT; i += 1) {
    if (state.status.type !== 'playing') break;
    const color = state.status.turn;
    const first = [...getLegalCrazyhouseMoves(state)].sort((a, b) =>
      moveKey(a).localeCompare(moveKey(b)),
    )[0]!;
    events.push({ type: 'move-played', at: at++, roomId: ROOM_ID, color, move: first });
    state = applyCrazyhouseMove(state, first);
  }
  events.push({ type: 'seat-resigned', at, roomId: ROOM_ID, color: 'black' });
  return events;
}

function gameRecord(overrides: Partial<RecentEveGameRecord> = {}): RecentEveGameRecord {
  return {
    roomId: ROOM_ID,
    variant: DARK_CRAZYHOUSE_SPEC_ID,
    mode: 'pvp',
    result: 'white-wins',
    termination: 'resignation',
    plyCount: MOVE_COUNT,
    startedAt: new Date(1),
    endedAt: new Date(100),
    whiteName: null,
    blackName: null,
    corpusId: null,
    rated: false,
    visibility: 'private',
    participants: [],
    jobId: null,
    gameIndex: null,
    whiteEngineId: null,
    blackEngineId: null,
    timeControl: null,
    initialMs: null,
    incrementMs: null,
    ...overrides,
  };
}

function deps(
  record: RecentEveGameRecord | null,
  events: DarkCrazyhouseEvent[] | null,
): DarkCrazyhousePostgamePersistence {
  return {
    getGameSummary: async () => record,
    loadRoomEvents: async () => events,
  };
}

test('Dark Crazyhouse postgame returns a full-truth view revealing every piece + every square', async () => {
  const payload = await darkCrazyhousePostgameForApi(
    ROOM_ID,
    deps(gameRecord(), finishedGameEvents()),
  );
  assert.ok(payload);
  assert.equal(payload.game.variant, DARK_CRAZYHOUSE_SPEC_ID);
  assert.deepEqual(payload.state.status, {
    type: 'finished',
    winner: 'white',
    reason: 'resignation',
  });
  assert.equal(payload.view.visibleSquares.length, 64);
  for (const [square, piece] of Object.entries(payload.view.board as Board)) {
    assert.ok(piece?.color && piece.role, `truth square ${square} must carry a piece`);
  }
});

// ── The hidden-info regression assertion ────────────────────────────────────
test('Dark Crazyhouse postgame per-seat views never leak the opponent (or its hand)', async () => {
  const payload = await darkCrazyhousePostgameForApi(
    ROOM_ID,
    deps(gameRecord(), finishedGameEvents()),
  );
  assert.ok(payload);
  const white = payload.views?.white;
  const black = payload.views?.black;
  assert.ok(white);
  assert.ok(black);
  assert.equal(white.perspective, 'white');
  assert.equal(black.perspective, 'black');

  for (const [perspective, view] of [
    ['white', white],
    ['black', black],
  ] as const) {
    const visible = new Set(view.visibleSquares);
    for (const [square, piece] of Object.entries(view.board as Board)) {
      if (!piece) continue;
      if (piece.color !== perspective) {
        assert.ok(
          visible.has(square as never),
          `${perspective} sees a hidden opponent on ${square}`,
        );
      }
    }
    assert.equal(typeof view.hand, 'object');
  }
  assert.deepEqual(payload.view.hand, {});
});

test('Dark Crazyhouse postgame history snapshots every perspective per ply', async () => {
  const payload = await darkCrazyhousePostgameForApi(
    ROOM_ID,
    deps(gameRecord(), finishedGameEvents()),
  );
  assert.ok(payload);
  const expectedPlies = Array.from({ length: MOVE_COUNT + 1 }, (_, i) => i);
  assert.deepEqual(
    payload.history?.truth?.map((snapshot) => snapshot.ply),
    expectedPlies,
  );
  assert.equal(payload.history?.white?.length, MOVE_COUNT + 1);
  assert.equal(payload.history?.black?.length, MOVE_COUNT + 1);
});

// ── The reveal gate ─────────────────────────────────────────────────────────
test('Dark Crazyhouse postgame returns null for an unfinished game', async () => {
  const events = finishedGameEvents().slice(0, -1); // drop the resignation
  const payload = await darkCrazyhousePostgameForApi(ROOM_ID, deps(gameRecord(), events));
  assert.equal(payload, null);
});

test('Dark Crazyhouse postgame rejects a non-dark-crazyhouse variant record', async () => {
  const payload = await darkCrazyhousePostgameForApi(
    ROOM_ID,
    deps(gameRecord({ variant: 'jieqi' }), finishedGameEvents()),
  );
  assert.equal(payload, null);
});

test('Dark Crazyhouse postgame returns null when there is no game or event log', async () => {
  assert.equal(await darkCrazyhousePostgameForApi(ROOM_ID, deps(null, finishedGameEvents())), null);
  assert.equal(await darkCrazyhousePostgameForApi(ROOM_ID, deps(gameRecord(), null)), null);
});

// Mock just enough of the http req/res for the flag-gate branch.
function mockResponse(): { response: ServerResponse; status: () => number | null } {
  let status: number | null = null;
  const response = {
    writeHead(code: number) {
      status = code;
      return response;
    },
    end() {
      return response;
    },
  } as unknown as ServerResponse;
  return { response, status: () => status };
}

test('Dark Crazyhouse postgame route returns 404 when the flag is off', async () => {
  const previous = process.env.MISTBOARD_DARK_CRAZYHOUSE_ENABLED;
  delete process.env.MISTBOARD_DARK_CRAZYHOUSE_ENABLED;
  try {
    const request = { method: 'GET' } as IncomingMessage;
    const { response, status } = mockResponse();
    const handled = await tryHandle(
      {} as HttpApiContext,
      request,
      response,
      `/api/dark-crazyhouse/games/${ROOM_ID}`,
      new URL(`http://localhost/api/dark-crazyhouse/games/${ROOM_ID}`),
    );
    assert.equal(handled, true);
    assert.equal(status(), 404);
  } finally {
    if (previous === undefined) delete process.env.MISTBOARD_DARK_CRAZYHOUSE_ENABLED;
    else process.env.MISTBOARD_DARK_CRAZYHOUSE_ENABLED = previous;
  }
});
