import assert from 'node:assert/strict';
import type { IncomingMessage, ServerResponse } from 'node:http';
import test from 'node:test';
import {
  applyCrossroadsChessMove,
  createInitialCrossroadsChessState,
  DARK_CROSSROADS_CHESS_SPEC_ID,
  getCrossroadsChessLegalMoves,
} from '@mistboard/game';
import type { DarkCrossroadsChessEvent } from '../dark-crossroads-chess-runtime.js';
import type { RecentEveGameRecord } from '../persistence.js';
import {
  type DarkCrossroadsChessPostgamePersistence,
  darkCrossroadsChessPostgameForApi,
  tryHandle,
} from './dark-crossroads-chess-games.js';
import type { HttpApiContext } from './lib.js';

const ROOM_ID = 'ddchess_postgame';
const MOVE_COUNT = 4;

// A deterministic scripted line: each side plays its alphabetically-first legal
// move, then Red resigns -> White wins. Moves are generated by replaying, so the
// event log only ever holds legal moves (an illegal move would be a no-op on
// replay and silently desync the test).
function finishedGameEvents(): DarkCrossroadsChessEvent[] {
  const events: DarkCrossroadsChessEvent[] = [
    {
      type: 'room-created',
      at: 1,
      roomId: ROOM_ID,
      gameSpecId: DARK_CROSSROADS_CHESS_SPEC_ID,
    },
    { type: 'seat-assigned', at: 2, roomId: ROOM_ID, clientId: 'w', seat: 'white' },
    { type: 'seat-assigned', at: 3, roomId: ROOM_ID, clientId: 'r', seat: 'red' },
  ];
  let state = createInitialCrossroadsChessState(ROOM_ID);
  let at = 4;
  for (let i = 0; i < MOVE_COUNT; i += 1) {
    if (state.status.type !== 'playing') break;
    const color = state.status.turn;
    const moves = [...getCrossroadsChessLegalMoves(state)].sort((a, b) =>
      `${a.from}${a.to}`.localeCompare(`${b.from}${b.to}`),
    );
    const first = moves[0]!;
    const move = { from: first.from, to: first.to };
    events.push({ type: 'move-played', at: at++, roomId: ROOM_ID, color, move });
    state = applyCrossroadsChessMove(state, move);
  }
  events.push({ type: 'seat-resigned', at, roomId: ROOM_ID, color: 'red' });
  return events;
}

function gameRecord(overrides: Partial<RecentEveGameRecord> = {}): RecentEveGameRecord {
  return {
    roomId: ROOM_ID,
    variant: DARK_CROSSROADS_CHESS_SPEC_ID,
    mode: 'pvp',
    result: 'white-wins',
    termination: 'resignation',
    plyCount: MOVE_COUNT,
    startedAt: new Date(1),
    endedAt: new Date(100),
    whiteName: null,
    blackName: null,
    corpusId: null,
    rated: false,
    visibility: 'private',
    participants: [],
    jobId: null,
    gameIndex: null,
    whiteEngineId: null,
    blackEngineId: null,
    timeControl: null,
    initialMs: null,
    incrementMs: null,
    ...overrides,
  };
}

function deps(
  record: RecentEveGameRecord | null,
  events: DarkCrossroadsChessEvent[] | null,
): DarkCrossroadsChessPostgamePersistence {
  return {
    getGameSummary: async () => record,
    loadRoomEvents: async () => events,
  };
}

test('Dark Crossroads postgame returns a full-truth view revealing every piece', async () => {
  const payload = await darkCrossroadsChessPostgameForApi(
    ROOM_ID,
    deps(gameRecord(), finishedGameEvents()),
  );
  assert.ok(payload);
  assert.equal(payload.game.variant, DARK_CROSSROADS_CHESS_SPEC_ID);
  assert.deepEqual(payload.state.status, {
    type: 'finished',
    winner: 'white',
    reason: 'resignation',
  });
  // Truth view: every occupied square is revealed (shrouded:false, carries piece).
  for (const [square, entry] of Object.entries(payload.view.board)) {
    assert.equal(entry?.shrouded, false, `truth square ${square} must be revealed`);
    assert.ok(entry && 'piece' in entry, `truth square ${square} must carry a piece`);
  }
});

// ── The hidden-info regression assertion ────────────────────────────────────
test('Dark Crossroads postgame per-seat views never leak the opponent under fog', async () => {
  const payload = await darkCrossroadsChessPostgameForApi(
    ROOM_ID,
    deps(gameRecord(), finishedGameEvents()),
  );
  assert.ok(payload);
  const white = payload.views?.white;
  const red = payload.views?.red;
  assert.ok(white);
  assert.ok(red);
  assert.equal(white.perspective, 'white');
  assert.equal(red.perspective, 'red');

  for (const [perspective, view] of [
    ['white', white],
    ['red', red],
  ] as const) {
    const visible = new Set(view.visibleSquares);
    for (const [square, entry] of Object.entries(view.board)) {
      if (!entry) continue;
      if (entry.shrouded) {
        // A shrouded silhouette must carry only color, never piece identity.
        assert.equal('piece' in entry, false, `${perspective} leaks a shrouded piece on ${square}`);
      } else if (entry.piece.color !== perspective) {
        // A fully-seen opponent piece must sit on a square the viewer can see.
        assert.ok(
          visible.has(square as never),
          `${perspective} sees a hidden opponent piece on ${square}`,
        );
      }
    }
  }
});

test('Dark Crossroads postgame history snapshots every perspective per ply', async () => {
  const payload = await darkCrossroadsChessPostgameForApi(
    ROOM_ID,
    deps(gameRecord(), finishedGameEvents()),
  );
  assert.ok(payload);
  const expectedPlies = Array.from({ length: MOVE_COUNT + 1 }, (_, i) => i);
  assert.deepEqual(
    payload.history?.truth?.map((snapshot) => snapshot.ply),
    expectedPlies,
  );
  assert.equal(payload.history?.white?.length, MOVE_COUNT + 1);
  assert.equal(payload.history?.red?.length, MOVE_COUNT + 1);
});

// ── The reveal gate ─────────────────────────────────────────────────────────
test('Dark Crossroads postgame returns null for an unfinished game', async () => {
  const events = finishedGameEvents().slice(0, -1); // drop the resignation
  const payload = await darkCrossroadsChessPostgameForApi(ROOM_ID, deps(gameRecord(), events));
  assert.equal(payload, null);
});

test('Dark Crossroads postgame rejects a non-dark-crossroads variant record', async () => {
  const payload = await darkCrossroadsChessPostgameForApi(
    ROOM_ID,
    deps(gameRecord({ variant: 'jieqi' }), finishedGameEvents()),
  );
  assert.equal(payload, null);
});

test('Dark Crossroads postgame returns null when there is no game or event log', async () => {
  assert.equal(
    await darkCrossroadsChessPostgameForApi(ROOM_ID, deps(null, finishedGameEvents())),
    null,
  );
  assert.equal(await darkCrossroadsChessPostgameForApi(ROOM_ID, deps(gameRecord(), null)), null);
});

// Mock just enough of the http req/res for the flag-gate branch, which fires
// before any persistence call.
function mockResponse(): { response: ServerResponse; status: () => number | null } {
  let status: number | null = null;
  const response = {
    writeHead(code: number) {
      status = code;
      return response;
    },
    end() {
      return response;
    },
  } as unknown as ServerResponse;
  return { response, status: () => status };
}

test('Dark Crossroads postgame route returns 404 when the flag is off', async () => {
  const previous = process.env.MISTBOARD_DARK_CROSSROADS_CHESS_ENABLED;
  delete process.env.MISTBOARD_DARK_CROSSROADS_CHESS_ENABLED;
  try {
    const request = { method: 'GET' } as IncomingMessage;
    const { response, status } = mockResponse();
    const handled = await tryHandle(
      {} as HttpApiContext,
      request,
      response,
      `/api/dark-crossroads-chess/games/${ROOM_ID}`,
      new URL(`http://localhost/api/dark-crossroads-chess/games/${ROOM_ID}`),
    );
    assert.equal(handled, true);
    assert.equal(status(), 404);
  } finally {
    if (previous === undefined) delete process.env.MISTBOARD_DARK_CROSSROADS_CHESS_ENABLED;
    else process.env.MISTBOARD_DARK_CROSSROADS_CHESS_ENABLED = previous;
  }
});
