import assert from 'node:assert/strict';
import test from 'node:test';
import {
  applyShogiMove,
  createInitialShogiState,
  DARK_SHOGI_SPEC_ID,
  getLegalShogiMoves,
  isShogiDrop,
  type ShogiMove,
} from '@mistboard/game';
import type { DarkShogiEvent } from '../dark-shogi-runtime.js';
import { darkShogiTenant } from '../dark-shogi-tenant.js';
import type { RecentEveGameRecord } from '../persistence.js';
import { createTenantRuntimeRoomFromEvents } from '../variant-tenant/runtime.js';
import { type DarkShogiPostgamePersistence, darkShogiPostgameForApi } from './dark-shogi-games.js';

const ROOM_ID = 'dsg_postgame';
const MOVE_COUNT = 4;

function moveKey(move: ShogiMove): string {
  return isShogiDrop(move)
    ? `*${move.drop}${move.to}`
    : `${move.from}${move.to}${move.promote ? 'q' : ''}`;
}

// A deterministic scripted line: each side plays its first legal move (stable
// sort), then White resigns -> Black wins. Moves are generated by replaying, so
// the event log only ever holds legal moves.
function finishedGameEvents(): DarkShogiEvent[] {
  const events: DarkShogiEvent[] = [
    { type: 'room-created', at: 1, roomId: ROOM_ID, gameSpecId: DARK_SHOGI_SPEC_ID },
    { type: 'seat-assigned', at: 2, roomId: ROOM_ID, clientId: 'b', seat: 'black' },
    { type: 'seat-assigned', at: 3, roomId: ROOM_ID, clientId: 'w', seat: 'white' },
  ];
  let state = createInitialShogiState(ROOM_ID);
  let at = 4;
  for (let i = 0; i < MOVE_COUNT; i += 1) {
    if (state.status.type !== 'playing') break;
    const color = state.status.turn;
    const first = [...getLegalShogiMoves(state)].sort((a, b) =>
      moveKey(a).localeCompare(moveKey(b)),
    )[0]!;
    events.push({ type: 'move-played', at: at++, roomId: ROOM_ID, color, move: first });
    state = applyShogiMove(state, first);
  }
  events.push({ type: 'seat-resigned', at, roomId: ROOM_ID, color: 'white' });
  return events;
}

function gameRecord(overrides: Partial<RecentEveGameRecord> = {}): RecentEveGameRecord {
  return {
    roomId: ROOM_ID,
    variant: DARK_SHOGI_SPEC_ID,
    mode: 'pvp',
    result: 'black-wins',
    termination: 'resignation',
    plyCount: MOVE_COUNT,
    startedAt: new Date(1),
    endedAt: new Date(100),
    whiteName: null,
    blackName: null,
    corpusId: null,
    rated: false,
    visibility: 'private',
    participants: [],
    jobId: null,
    gameIndex: null,
    whiteEngineId: null,
    blackEngineId: null,
    timeControl: null,
    initialMs: null,
    incrementMs: null,
    ...overrides,
  };
}

function deps(
  record: RecentEveGameRecord | null,
  events: DarkShogiEvent[] | null,
): DarkShogiPostgamePersistence {
  return {
    getGameSummary: async () => record,
    loadRoomEvents: async () => events,
  };
}

function liveFinishedRoom() {
  const hydrated = createTenantRuntimeRoomFromEvents(darkShogiTenant, finishedGameEvents());
  assert.ok(hydrated.ok);
  return hydrated.room;
}

test('Dark Shogi postgame returns a full-truth view revealing every piece + every square', async () => {
  const payload = await darkShogiPostgameForApi(ROOM_ID, deps(gameRecord(), finishedGameEvents()));
  assert.ok(payload);
  assert.equal(payload.game.variant, DARK_SHOGI_SPEC_ID);
  assert.deepEqual(payload.state.status, {
    type: 'finished',
    winner: 'black',
    reason: 'resignation',
  });
  // Truth view: all 81 squares visible, every board entry a fully-known piece.
  assert.equal(payload.view.visibleSquares.length, 81);
  for (const [square, piece] of Object.entries(payload.view.board)) {
    assert.ok(piece?.color && piece.role, `truth square ${square} must carry a piece`);
  }
});

// ── The hidden-info regression assertion ────────────────────────────────────
test('Dark Shogi postgame per-seat views never leak the opponent (or its hand) under fog', async () => {
  const payload = await darkShogiPostgameForApi(ROOM_ID, deps(gameRecord(), finishedGameEvents()));
  assert.ok(payload);
  const black = payload.views?.black;
  const white = payload.views?.white;
  assert.ok(black);
  assert.ok(white);
  assert.equal(black.perspective, 'black');
  assert.equal(white.perspective, 'white');

  for (const [perspective, view] of [
    ['black', black],
    ['white', white],
  ] as const) {
    const visible = new Set(view.visibleSquares);
    for (const [square, piece] of Object.entries(view.board)) {
      if (!piece) continue;
      // A fully-seen opponent piece must sit on a square the viewer can see
      // (shogi has no shrouded silhouettes — off-vision enemies are absent).
      if (piece.color !== perspective) {
        assert.ok(
          visible.has(square as never),
          `${perspective} sees a hidden opponent on ${square}`,
        );
      }
    }
    // The reserve on a per-seat view is the viewer's own — present as an object.
    assert.equal(typeof view.hand, 'object');
  }
  // The truth view does not carry a single side's reserve (hands come from the
  // per-color views), so it stays empty.
  assert.deepEqual(payload.view.hand, {});
});

test('Dark Shogi postgame history snapshots every perspective per ply', async () => {
  const payload = await darkShogiPostgameForApi(ROOM_ID, deps(gameRecord(), finishedGameEvents()));
  assert.ok(payload);
  const expectedPlies = Array.from({ length: MOVE_COUNT + 1 }, (_, i) => i);
  assert.deepEqual(
    payload.history?.truth?.map((snapshot) => snapshot.ply),
    expectedPlies,
  );
  assert.equal(payload.history?.black?.length, MOVE_COUNT + 1);
  assert.equal(payload.history?.white?.length, MOVE_COUNT + 1);
});

test('Dark Shogi postgame can render from a finished live room without persistence', async () => {
  const room = liveFinishedRoom();
  const payload = await darkShogiPostgameForApi(ROOM_ID, {
    getGameSummary: async () => {
      throw new Error('persistence should not be queried');
    },
    getLiveRoom: () => room,
    isPersistenceEnabled: () => false,
    loadRoomEvents: async () => {
      throw new Error('persistence should not be queried');
    },
  });
  assert.ok(payload);
  assert.equal(payload.game.roomId, ROOM_ID);
  assert.equal(payload.game.variant, DARK_SHOGI_SPEC_ID);
  assert.equal(payload.game.visibility, 'public');
  assert.equal(payload.timeline.filter((entry) => entry.type === 'move-played').length, MOVE_COUNT);
  assert.equal(payload.history?.truth?.at(-1)?.ply, MOVE_COUNT);
});

// ── The reveal gate ─────────────────────────────────────────────────────────
test('Dark Shogi postgame returns null for an unfinished game', async () => {
  const events = finishedGameEvents().slice(0, -1); // drop the resignation
  const payload = await darkShogiPostgameForApi(ROOM_ID, deps(gameRecord(), events));
  assert.equal(payload, null);
});

test('Dark Shogi postgame rejects a non-dark-shogi variant record', async () => {
  const payload = await darkShogiPostgameForApi(
    ROOM_ID,
    deps(gameRecord({ variant: 'jieqi' }), finishedGameEvents()),
  );
  assert.equal(payload, null);
});

test('Dark Shogi postgame returns null when there is no game or event log', async () => {
  assert.equal(await darkShogiPostgameForApi(ROOM_ID, deps(null, finishedGameEvents())), null);
  assert.equal(await darkShogiPostgameForApi(ROOM_ID, deps(gameRecord(), null)), null);
});

test('Dark Shogi postgame does not require launch env flags', async () => {
  const previous = process.env.MISTBOARD_DARK_SHOGI_ENABLED;
  delete process.env.MISTBOARD_DARK_SHOGI_ENABLED;
  try {
    const payload = await darkShogiPostgameForApi(
      ROOM_ID,
      deps(gameRecord(), finishedGameEvents()),
    );
    assert.ok(payload);
    assert.equal(payload.game.variant, DARK_SHOGI_SPEC_ID);
  } finally {
    if (previous === undefined) delete process.env.MISTBOARD_DARK_SHOGI_ENABLED;
    else process.env.MISTBOARD_DARK_SHOGI_ENABLED = previous;
  }
});
