// Take an MP4 generated by Wan/SVD/etc. and produce a seamlessly-looping
// animated WebP suitable as a board-square overlay (or a looped MP4 for
// preview).
//
// Strategy: PALINDROME by default — forward then reverse, concatenated.
// Mathematically perfect loop (end frame = start frame) and looks natural for
// directionless motion like fog. For directional content (use --mode crossfade)
// we cross-fade the last second into the first second.
//
// Usage:
//   node scripts/loop-video.mjs --in apps/web/public/pixel-lab-assets/video/fog-mistveil.mp4 \
//     --out fog-mistveil --mode palindrome
//
// Outputs both .mp4 (looped) and .webp (animated, ~50% the size, browser-friendly)
// into apps/web/public/pixel-lab-assets/video/<out>-loop.{mp4,webp}.

import { spawn } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (next && !next.startsWith('--')) {
        args[key] = next;
        i++;
      } else {
        args[key] = true;
      }
    }
  }
  return args;
}

function run(cmd, args) {
  return new Promise((res, rej) => {
    const p = spawn(cmd, args, { stdio: ['ignore', 'inherit', 'inherit'] });
    p.on('exit', (code) => (code === 0 ? res() : rej(new Error(`${cmd} exited ${code}`))));
    p.on('error', rej);
  });
}

const args = parseArgs(process.argv.slice(2));
if (!args.in || !args.out) {
  console.error(
    'Usage: node scripts/loop-video.mjs --in <path.mp4> --out <name> [--mode palindrome|crossfade]',
  );
  process.exit(1);
}

const mode = typeof args.mode === 'string' ? args.mode : 'palindrome';
const inPath = resolve(REPO_ROOT, args.in);
const outDir = resolve(REPO_ROOT, 'apps/web/public/pixel-lab-assets/video');
const outMp4 = resolve(outDir, `${args.out}-loop.mp4`);
const outWebp = resolve(outDir, `${args.out}-loop.webp`);

console.log(`[${mode}] ${inPath} -> ${outMp4}`);

if (mode === 'palindrome') {
  // Forward, then concat with reverse. Drop the last frame of forward and first
  // frame of reverse to avoid duplicate-frame pause at the turnaround.
  await run('ffmpeg', [
    '-y',
    '-i',
    inPath,
    '-filter_complex',
    '[0:v]split[fwd][src];[src]reverse,trim=start_frame=1[rev];[fwd][rev]concat=n=2:v=1:a=0[v]',
    '-map',
    '[v]',
    '-c:v',
    'libx264',
    '-pix_fmt',
    'yuv420p',
    '-an',
    outMp4,
  ]);
} else if (mode === 'crossfade') {
  // Cross-fade last 1s into first 1s. Requires knowing input duration; use 1s default xfade.
  await run('ffmpeg', [
    '-y',
    '-i',
    inPath,
    '-filter_complex',
    '[0:v]split[a][b];[b]trim=start=4,setpts=PTS-STARTPTS[bt];[a][bt]xfade=transition=fade:duration=1:offset=4[v]',
    '-map',
    '[v]',
    '-c:v',
    'libx264',
    '-pix_fmt',
    'yuv420p',
    '-an',
    outMp4,
  ]);
} else {
  throw new Error(`unknown mode: ${mode}`);
}

// Animated WebP conversion is optional — browsers play <video> natively, and
// homebrew's ffmpeg often lacks libwebp encoder. Skip unless --webp is set.
if (args.webp) {
  console.log(`[webp] ${outMp4} -> ${outWebp}`);
  await run('ffmpeg', [
    '-y',
    '-i',
    outMp4,
    '-vcodec',
    'libwebp',
    '-loop',
    '0',
    '-preset',
    'picture',
    '-an',
    '-vsync',
    '0',
    outWebp,
  ]);
}

console.log(`done -> ${outMp4.replace(REPO_ROOT + '/', '')}`);
